### ISSUE TITLE
UglyToad.PdfPig.Fonts.Exceptions.InvalidFontFormatException:

### ISSUE THREAD

**Issue by uwerichter** [UglyToad/PdfPig#101]
Hi, it comes up with some like this:

UglyToad.PdfPig.Fonts.Exceptions.InvalidFontFormatException: No font descriptor indirect reference found in the TrueType font: <Type, /Font>, <Subtype, /TrueType>, <Name, /F3H>, <BaseFont, /Arial>, <Encoding, /WinAnsiEncoding>, <FirstChar, 32>, <LastChar, 255>, <Widths, [ 278, 278, 355, 556, 556, 889, 667, 

...
Any cure for that?

**Comment by EliotJones** [comment]
Are you able to share the file at all please? If not is there more detail in the exception message after the long array of numbers? 

In the meantime I'll take a look at the specification and see if I've missed an edge case.

**Comment by uwerichter** [comment]
Hi Eliot,

here are the codes ...
************* Ausnahmetext **************
UglyToad.PdfPig.Fonts.Exceptions.InvalidFontFormatException: No font descriptor indirect reference found in the TrueType font: <Type, /Font>, <Subtype, /TrueType>, <Name, /F3H>, <BaseFont, /Arial>, <Encoding, /WinAnsiEncoding>, <FirstChar, 32>, <LastChar, 255>, <Widths, [ 278, 278, 355, 556, 556, 889, 667, 191, 333, 333, 389, 584, 278, 333, 278, 278, 556, 556, 556, 556, 556, 556, 556, 556, 556, 556, 278, 278, 584, 584, 584, 556, 1015, 667, 667, 722, 722, 667, 611, 778, 722, 278, 500, 667, 556, 833, 722, 778, 667, 778, 722, 667, 611, 722, 667, 944, 667, 667, 611, 278, 278, 278, 469, 556, 333, 556, 556, 500, 556, 556, 278, 556, 556, 222, 222, 500, 222, 833, 556, 556, 556, 556, 333, 500, 278, 556, 500, 722, 500, 500, 500, 334, 260, 334, 584, 500, 556, 500, 222, 556, 333, 1000, 556, 556, 333, 1000, 667, 333, 1000, 500, 611, 500, 500, 222, 222, 333, 333, 350, 556, 1000, 333, 1000, 500, 333, 944, 500, 500, 667, 278, 333, 556, 556, 556, 556, 260, 556, 333, 737, 370, 556, 584, 333, 737, 333, 400, 549, 333, 333, 333, 576, 537, 278, 333, 333, 365, 556, 834, 834, 834, 611, 667, 667, 667, 667, 667, 667, 1000, 722, 667, 667, 667, 667, 278, 278, 278, 278, 722, 722, 778, 778, 778, 778, 778, 584, 778, 722, 722, 722, 722, 667, 667, 611, 556, 556, 556, 556, 556, 556, 889, 500, 556, 556, 556, 556, 278, 278, 278, 278, 556, 556, 556, 556, 556, 556, 556, 549, 611, 556, 556, 556, 556, 500, 556, 500 ]>.
   bei UglyToad.PdfPig.Fonts.Parser.FontDictionaryAccessHelper.GetFontDescriptor(IPdfTokenScanner pdfScanner, FontDescriptorFactory fontDescriptorFactory, DictionaryToken dictionary, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Fonts\Parser\FontDictionaryAccessHelper.cs:Zeile 61.
   bei UglyToad.PdfPig.Fonts.Parser.Handlers.TrueTypeFontHandler.Generate(DictionaryToken dictionary, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Fonts\Parser\Handlers\TrueTypeFontHandler.cs:Zeile 80.
   bei UglyToad.PdfPig.Fonts.FontFactory.Get(DictionaryToken dictionary, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Fonts\FontFactory.cs:Zeile 54.
   bei UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs:Zeile 137.
   bei UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Content\ResourceStore.cs:Zeile 39.
   bei UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Parser\PageFactory.cs:Zeile 68.
   bei UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\Content\Pages.cs:Zeile 69.
   bei UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:Zeile 163.
   bei UglyToad.PdfPig.PdfDocument.<GetPages>d__29.MoveNext() in C:\git\csharp\UglyToad.PdfPig\src\UglyToad.PdfPig\PdfDocument.cs:Zeile 174.
   bei DBEntities.Common.ScanPdf.GetText(String filename) in \\Mac\Home\Documents\Develop\DotNetProjekte\DBEntities\DBEntities\Common\ScanPdf.cs:Zeile 17.

**Comment by uwerichter** [comment]
Here is the doc

[SKM_C300i19121713530.pdf](https://github.com/UglyToad/PdfPig/files/3973350/SKM_C300i19121713530.pdf)

**Comment by EliotJones** [comment]
Thank you for sharing those documents, I'll take a look.

Reopening this to track the work to fix it :)

**Comment by EliotJones** [comment]
I've pushed out a fixed version for this now, please give version 0.0.11 a try and let me know if it fixes this: https://www.nuget.org/packages/PdfPig/

**Comment by uwerichter** [comment]
Hi Eliot,

works like a charm, you saved my week!

Cheers Uwe
