### ISSUE TITLE
Parallel.For in DocumentLayoutAnalysis

### ISSUE THREAD

**Issue by huzhiguan** [UglyToad/PdfPig#104]
I noticed that inside namespace `DocumentLayoutAnalysis`, some algorithms are using `Parallel.For` to accelerate processing speed. From a user's standpoint, would it be better to get more visibility and control over the thread usage? For example, a place we can set `MaxDegreeOfParallelism` when needed. Thanks!

**Comment by BobLd** [comment]
Hi, that is a good point and will be useful. I should find some time to work on it soon.

**Comment by BobLd** [comment]
Hi, can you have a look at #105? Let me know if you have any comment

**Comment by huzhiguan** [comment]
> Hi, can you have a look at #105? Let me know if you have any comment

It looks good to me, thanks for the quick update!

**Comment by EliotJones** [comment]
Hi, this should be available via Nuget in the latest 0.1.0 release, are you happy to close this now?
