### ISSUE TITLE
A mistake that potentially become a "performance booster" for WhitespaceCoverExtractor in DocumentLayoutAnalysis

### ISSUE THREAD

**Issue by huzhiguan** [UglyToad/PdfPig#114]
https://github.com/UglyToad/PdfPig/blob/7296c3c125f827e6efd65002500e3bfe7f8befaf/src/UglyToad.PdfPig/DocumentLayoutAnalysis/WhitespaceCoverExtractor.cs#L313-L332

At line 321, the `return false` should be replaced by `continue`. According to Berg's paper, `IsEmptyEnough` should be used to 

> Checks whether the rectangle represented by whitespaceCandidate is empty enough to be considered a whitespace rectangle

A correct implementation should check intersections between the current `Bound` with all obstacles. If there is an overlap, we need to check if that intersection and the sum of all intersection with all obstacles are smaller enough to be treated as empty. If not, the function should return false.

In our current implementation, this function actually returns false if we found the current `Bound` has no intersection with one of the obstacles. This should be a bug but while we are doing some testing with the right version and the bug version, the result tells a different story.

I tested both versions with a 171-page documents, the average processing time per page with `return false` version is 2.7645 seconds. The average processing time per page with `continue` version is 9.6976 seconds. There are in total of 8 pages that have different whitespace count. The `retrun false` version found more whitespaces region for 7 of the 8 pages. 

Example:
![image](https://user-images.githubusercontent.com/961144/71595564-c5b29c00-2b01-11ea-87f1-b15b78975451.png)

**Comment by BobLd** [comment]
Hi huzhiguan, thanks for creating the issue and taking the time to run the analysis. Results are very interesting. 

I need to run some tests to understand these empty intersections cases. I'll try to do it soon
