### ISSUE TITLE
How to distribute DocumentLayoutAnalysis?

### ISSUE THREAD

**Issue by EliotJones** [UglyToad/PdfPig#119]
Now that the solution has been restructured into multiple projects we no longer include the DocumentLayoutAnalysis code when calling `dotnet pack` on `UglyToad.PdfPig.csproj`. This is because the layout analysis projects sits above the main project as a leaf node:
![image](https://user-images.githubusercontent.com/7862346/71782028-3e679b80-2fcd-11ea-9294-a3292141c1eb.png)

The options for including this, as far as I can tell are:
1. Publish as a separate nuget package.
2. Include the `UglyToad.PdfPig.DocumentLayoutAnalysis.dll` in the `UglyToad.PdfPig.dll` by using IL repack to merge the assemblies into a single dll. https://github.com/gluck/il-repack I tried this approach on a couple of the debug dlls and it seemed to work, but it's trickier to do it for every framework and then include the result in the output of `dotnet pack`.
3. Create a top level project, `UglyToad.PdfPig.Package.csproj` which has the package name `UglyToad.PdfPig` and references both projects.

**Comment by EliotJones** [comment]
Settled on approach 3 since it supports more projects built on top of the main project.

**Comment by EliotJones** [comment]
Timings for the new approach (0.1.0) versus code before the projects were split up (Doubles and Optimized) using becnhmarking from #47.

```
Running file Sample00_5_pages.pdf

PdfPig 0.1.0             ... Time (ms): 245  Letters: 7402
PdfPig-Optimized         ... Time (ms): 181  Letters: 7402
PdfBox 1.8               ... Time (ms): 538  Letters: 7402
PdfPig Doubles           ... Time (ms): 188  Letters: 7402

Running file Sample05_29_pages.pdf

PdfPig 0.1.0             ... Time (ms): 283  Letters: 76363
PdfPig-Optimized         ... Time (ms): 271  Letters: 76363
PdfBox 1.8               ... Time (ms): 1265  Letters: 76363
PdfPig Doubles           ... Time (ms): 353  Letters: 76363

Running file Sample10_64_pages.pdf

PdfPig 0.1.0             ... Time (ms): 2078  Letters: 103719
PdfPig-Optimized         ... Time (ms): 2140  Letters: 103719
PdfBox 1.8               ... Time (ms): 3721  Letters: 103719
PdfPig Doubles           ... Time (ms): 2612  Letters: 103719

Running file Sample20_397_Pages.pdf

PdfPig 0.1.0             ... Time (ms): 6285  Letters: 1349279
PdfPig-Optimized         ... Time (ms): 6841  Letters: 1349279
PdfBox 1.8               ... Time (ms): 19957  Letters: 1349279
PdfPig Doubles           ... Time (ms): 7254  Letters: 1349279
```

**Comment by EliotJones** [comment]
It looks like source link no longer works with the new approach, it may be that we need to add the source link package to the top level project.

**Comment by BobLd** [comment]
Hi Eliot, what do you mean by _source link_?

**Comment by EliotJones** [comment]
@BobLd it's a new dotnet thing which enables stepping into source code using GitHub. https://github.com/dotnet/sourcelink Basically if the consumer of a nuget package has source link enabled in their Visual Studio they can step into the code that produced the package. However it seems like they changed how it worked in some version prior to 0.0.11 so it stopped working anyway.
