### ISSUE TITLE
New Feature: PDF/A-1B Compliance

### ISSUE THREAD

**Issue by EliotJones** [UglyToad/PdfPig#127]
The generated PDFs are currently not compliant with the PDF/A-1B validation profile.

From the attached veraPDF report it looks like compliance might be a fairly small project which will provide benefits for consumers and producers of documents.

[Validation Report.pdf](https://github.com/UglyToad/PdfPig/files/4056271/Validation.Report.pdf)

The PDF/A specification is not available to mere mortals like us so we should use the validation report to guide which features to implement.

**Comment by Martin005** [comment]
@EliotJones I have found PDF/A-1 specification just lying on the internet: http://www.csygen.com/pdf/iso_19005.PDF 😃

**Comment by EliotJones** [comment]
@Martin005 thank you that's very useful, hopefully I'll get some time to start implementing this soon, I had completely forgotten 😆

**Comment by EliotJones** [comment]
Compliance modes for PDF/A-1B and PDF/A1-A have been added and will be available in the next release. They are used as follows:

```
var builder = new PdfDocumentBuilder
{
    ArchiveStandard = PdfAStandard.A1B
};
```

These seem to pass veraPdf's checks. They will need further testing to make sure they work with the new JPG image support and any further additions to PDF building such as #156 bookmarks.

Leaving this issue open since it seems like adding PDF/A-2 compliance might be possible and an easy win.

**Comment by EliotJones** [comment]
Available in the current prerelease through to PDF/A-2A compliance
