### ISSUE TITLE
TryGetForm throws exception: 'Fields' not in dictionary 

### ISSUE THREAD

**Issue by davidpene** [UglyToad/PdfPig#131]
```
System.Collections.Generic.KeyNotFoundException: The given key 'Fields' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at UglyToad.PdfPig.AcroForms.AcroFormFactory.GetAcroForm(Catalog catalog)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at UglyToad.PdfPig.PdfDocument.TryGetForm(AcroForm& form)
   ...
```

Not sure if it is this line [acroDictionary access](https://github.com/UglyToad/PdfPig/blob/efc258b0f0845a78ad714e26a02782020008e62f/src/UglyToad.PdfPig/AcroForms/AcroFormFactory.cs#L86)

**Comment by EliotJones** [comment]
Thanks, that looks like the corresponding line. According to the spec it shouldn't be possible for this situation to ever occur but it seems like returning `null` here should be ok. I will make this change soon.

Do you happen to know if the corresponding document actually contains a form or is returning false for `TryGetForm` acceptable here?

**Comment by EliotJones** [comment]
I've pushed this change now, would you be able to check if the change works for your document please (or is it easier for you if I provide a NuGet package containing the change)?

**Comment by davidpene** [comment]
Hey @EliotJones sorry for the late reply, we had a public holiday.
I'm not able to get an example document because we have this running in production 😄 

Thanks for the fix!

**Comment by EliotJones** [comment]
I'm assuming this is now fixed, feel free to reopen the issue if not.
