### ISSUE TITLE
Trying to type with TrueTypeFont in 0.1.0

### ISSUE THREAD

**Issue by FlaySkayCZ** [UglyToad/PdfPig#137]
Hello,

I'am trying to write Czech letters (using ISO 8859-2) as Standard14Font does not to support these character I've tried to implement using newly added https://github.com/UglyToad/PdfPig#truetype-010 . Code I've used is as follows:

```
string BytesPath = "C:/TNR_Liborius_VII.ttf";
            byte[] fontBytes = File.ReadAllBytes(BytesPath);
            TrueTypeDataBytes input = new TrueTypeDataBytes(fontBytes);
            TrueTypeFont addedFont = TrueTypeFontParser.Parse(input);
```

Then when I try to use this addedFont with :

`page.AddText("My new text incliding ěščřž", 100, new PdfPoint(100, 100), addedFont);`

and that trows error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	CS0029	Cannot implicitly convert type '**UglyToad.PdfPig.Fonts.TrueType.TrueTypeFont**' to '**UglyToad.PdfPig.Writer.PdfDocumentBuilder.AddedFont**'	fakturace	C:\fakturace\fakturace\Views\TestPage.xaml.cs	132	Active

Could you point me to documentation describing how to use this new part of PdfPig, or is there any project where is this working and I can use it to implement it in my case ?

Thank you

**Comment by EliotJones** [comment]
Thanks for your question.

The new `TrueType` parsing classes can't currently be used with `PdfDocumentBuilder` (they're used by it internally but the document builder does some extra stuff first). While `PdfDocumentBuilder` uses the TrueType parser internally in order to use a TrueType font for writing text you still need to add it to the document builder, for example you would use `builder.AddTrueTypeFont()` like this:

```
PdfDocumentBuilder builder = new PdfDocumentBuilder();
PdfPageBuilder page = builder.AddPage(PageSize.A4);
string BytesPath = "C:/TNR_Liborius_VII.ttf";
byte[] fontBytes = File.ReadAllBytes(BytesPath);
PdfDocumentBuilder.AddedFont addedFont = builder.AddTrueTypeFont(fontBytes);
page.AddText("My new text including ěščřž", 100, new PdfPoint(100, 100), addedFont);
```

Let me know if this works for your use-case and I'll update the documentation on the Wiki to make this easier to get started with,

**Comment by FlaySkayCZ** [comment]
I've been as well trying to use this method, which you've just recomended for a while now but the result is either blank space where the characters should be, or is some wrongly created text for example: 
> !"#$%&'()$$*

I've tried few fonts which contains Czech letters, but I can't get it to work. 
Do you have any idea what may be causing this ? 

Thank you for your time and effort.

**Comment by EliotJones** [comment]
Ah ok, it's likely something is going wrong internally to PdfPig when it finds the corresponding characters for the Unicode symbols for these Czech characters, I'll download the font myself and take a look, either today or tomorrow. Was it this font here? https://fonts2u.com/tnr-liborius-vii.font

**Comment by EliotJones** [comment]
I tried creating a file with the version of TNR Liborius VII I linked but I get an exception:

```
System.InvalidOperationException : The font does not contain a character: ě.
```

For the input text `My new text including ěščřž`. 

It looks like the only Czech letter that font contains is Latin Small Letter S With Caron `š`. If I open the .ttf file with Windows' Character Map there are other letters that appear to have Carons but they are incorrectly mapped to different Unicode letters:

![image](https://user-images.githubusercontent.com/7862346/74827772-e0d1a900-5305-11ea-8903-f2f7beb30b85.png)

For example in the image the letter that looks like small c with caron `č` is actually mapped to Latin Small Letter E With Grave `è`, similarly the small e with caron `ě` is actually I With Grave `ì`. I thought the difference might be the assigned values for Unicode vs ISO 8859-2 encodings but they appear to share the same values for the letters with carons.

Similarly if I try to write those characters with the font in LibreOffice the letters with carons, except `s` default to a fallback font:

![image](https://user-images.githubusercontent.com/7862346/74828213-9ef53280-5306-11ea-84e8-78a6b1fc9ffb.png)

I'm worried that you're not getting the same exception when you try to output the file, are you able to share a font which displays the blank or wrong output you mentioned please?

**Comment by FlaySkayCZ** [comment]
https://github.com/UglyToad/PdfPig/issues/137#issuecomment-587382183
To this comment, sorry for late response.
I've tried this font :
http://www.eaglefonts.com/128803.lightbox.htm
I've looked at your link and it seems it isn't in ttf format.

Regarding this: https://github.com/UglyToad/PdfPig/issues/137#issuecomment-588161964
I get the same error only with Standard14Font.Helvetica for example
System.InvalidOperationException : The font does not contain a character: ě.

![image](https://user-images.githubusercontent.com/49071283/74831803-3d3cc480-5316-11ea-936d-ea20d83ea97f.png)

For example this is TNR Liborius VII.ttf character map with highlither ě.

**Comment by EliotJones** [comment]
Hmm, this is very strange, I'm not sure what is going on.

Here's the sample text created using the font you linked and PdfPig:

![image](https://user-images.githubusercontent.com/7862346/74933102-3926aa80-53db-11ea-8e1b-be318bb45e42.png)

To create this document I had to use the following code:

```
var builder = new PdfDocumentBuilder();
var ft = builder.AddTrueTypeFont(File.ReadAllBytes(@"C:\Temp\TNR_Liborius_VII.ttf"));
var pg = builder.AddPage(PageSize.A4, false);
var txt = pg.AddText("My new text including Ìšèøz¡ýáíé", 12, new PdfPoint(15, pg.PageSize.Height - 20), ft);
File.WriteAllBytes(@"C:\temp\czech.pdf", builder.Build());
```

As you can see from the code, to generate the correct visual glyphs for `Escrz` with carons I had to use the text `Ìšèøz¡ýáíé` (the font doesn't appear to contain a z with caron so the best I could do was normal z followed by a caron).

Here's the same sample text in Libre Office (I unfortunately don't have Word) in Liberation Serif (top) and TNR Liborius (bottom):

![image](https://user-images.githubusercontent.com/7862346/74933329-a5a1a980-53db-11ea-80ef-f1eb1cff9db7.png)

This shows that the correct appearing glyphs in TNR Liborius seem to map to entirely the wrong values. This can also be seen in the image of the character map you shared where you have selected `small e with caron` but at the bottom right of the image Character Map says that character is mapped to the unicode value `Latin small letter I with Grave`.

I'm not actually sure how Word generated the correct text, for one thing the TNR Liborius font doesn't have any glyph with the appearance of `Latin small letter z with Caron` so I've no idea how it's displaying that. I'm going to see if there's anything related to the machine locale going on here by setting my machine to whatever the correct locale is for Czech.

**Comment by EliotJones** [comment]
I uncovered a bug with text positions when the thread's current culture is set to a European style decimal separator culture type. I've pushed a fix for this which may explain why you were getting blank text (it would have been placed off the page). But even with the Czech language pack and the thread culture as Czech I still can't generate a PDF containing the characters: `ě-čřž` unless I use the other unicode values.

**Comment by mareksip** [comment]
The below stackoverflow post suggest to use CIDFont instead of Font for writing to PDF.

As well, the second option suggest to use existing Unicode character mappings from Adobe.

> It may be possible to construct a single CMap which would cover every Unicode code point, but I have my doubts, it would certainly be a huge task. However certain CMaps already exist. Adobe publish a standard list on their web site which includes CMaps such as UniCNS-UCS2-H and UniCNS-UCS2-V or UniGB-UTF8-H etc.

Hope it helps.

Cheers.

https://stackoverflow.com/questions/54272712/writing-unicode-into-pdf

**Comment by EliotJones** [comment]
Thanks for the pointers. As far as I'm aware it should only be necessary to use a CID Font where the number of symbols being written exceeds the encoding size of a simple font (Adobe Type 1 or TrueType) or the text includes combining diacritics / other multi-code-point unicode values (CJK). In simple fonts the encoding allows selecting up to 256 distinct glyphs which can be outside the range of ASCII/Win-1252 encodings.

The current code has a check in place for when we exceed this limit: https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Writer/Fonts/TrueTypeWritingFont.cs#L147 but it might be that we're running into a combining diacritic issue here. 

I'll try making the output text by combining the latin small letters and the combining diacritic for the caron character and see what happens. For example in C# interactive:

    > "z\u030C"
    "ž"
    > "a\u030C"
    "ǎ"

Out of interest have the changes in #98 been working for you at all? It seemed to work for me when I tested it but I'm worried I'm missing a test scenario which is going wrong (other than the one in this current issue).

**Comment by EliotJones** [comment]
Ok, so I think the next step to work out what's going on is if you can test the following code on your machine please:

    var builder = new PdfDocumentBuilder();
    var addedFont = builder.AddTrueTypeFont(File.ReadAllBytes(@"C:\Users\eliot\Downloads\Open_Sans\OpenSans-Regular.ttf"));

    var page = builder.AddPage(PageSize.A4);
    page.AddText("My new text including ěščřž", 12, new PdfPoint(100, page.PageSize.Top - 50), addedFont);
    page.AddText("My new text including Ìšèøz¡ýáíé", 12, new PdfPoint(100, page.PageSize.Top - 100), addedFont);

    File.WriteAllBytes(@"C:\temp\czech.pdf", builder.Build());

Where the path to the font is replaced by the path to the following font https://fonts.google.com/specimen/Open+Sans?selection.family=Open+Sans. Choose Select This Font, then use the download icon in the popup box:

![image](https://user-images.githubusercontent.com/7862346/75254548-6eb30580-57d8-11ea-9f5b-4890374c7a76.png)

Unzip the resulting font folder and use the path to OpenSans-Regular.ttf.

You'll need to use a PdfPig NuGet package version with the fix for European locales, I've attached a custom build version to this post.

[PdfPig.0.1.1-alpha001.zip](https://github.com/UglyToad/PdfPig/files/4250369/PdfPig.0.1.1-alpha001.zip)

**Comment by FlaySkayCZ** [comment]
Hello, I've tried your code and it works! 

![image](https://user-images.githubusercontent.com/49071283/75344555-23156000-589b-11ea-8264-e690c0b27b8e.png)

Afterwards I've tried my code and it works as well, all of the special symbols are created correctly using your custom PdfPig.0.1.1-alpha001.zip package, while using other .ttf font than OpenSans-Regular.ttf.

**Comment by EliotJones** [comment]
Thanks for trying that. It looks like the primary problem was the locale issue when writing the PDF content. That's a relief 😌 

The next NuGet version containing this fix should be out by the middle of next week.

**Comment by FlaySkayCZ** [comment]
Thanks, I will be using your alpha001 package and afterward will miggrate to Nugget version. If anything goes haywire I will immediately contact you.

**Comment by mareksip** [comment]
What a good news! Thanks alot for your effort @EliotJones . This features also closes #98 as we have been testing your suggestions with @FlaySkayCZ

**Comment by EliotJones** [comment]
Glad to hear it's working now, is it ok to go ahead and close this issue?

**Comment by mareksip** [comment]
@EliotJones Yes. Thanks alot!
