### ISSUE TITLE
Letters bounding boxes issue with this document

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#141]
The letters bounding boxes are not correctly computed in the following document: https://www.apple.com/environment/pdf/Apple_Environmental_Responsibility_Report_2019.pdf

Example:
![image](https://user-images.githubusercontent.com/38405645/75169778-0a813a80-5721-11ea-8740-ce69524c299b.png)

I'm not sure what causes the problem..

**Comment by EliotJones** [comment]
Looks like this was a bug in the handling of the byte value `28` in Adobe Type 2 charstrings. It should be fixed on the latest master, please give it a go and let me know.

**Comment by BobLd** [comment]
Thanks Eliot! Will give it a try today

**Comment by BobLd** [comment]
Okay, works like a charm:
![image](https://user-images.githubusercontent.com/38405645/75260058-e5ec9780-57e0-11ea-9d8f-83e6ac05b35a.png)

Thanks Eliot!
