### ISSUE TITLE
issue while using 'PageSize.Custom'

### ISSUE THREAD

**Issue by mayurjansari** [UglyToad/PdfPig#147]
getting this exception while using PageSize.Cutom
_System.ArgumentException
Message : No rectangle found for Page Size Custom.
StackTrace :    at UglyToad.PdfPig.Writer.PdfDocumentBuilder.AddPage(PageSize size, Boolean isPortrait)
   at PdfCard.FormMain.CreateRowCardPig(String inputFile, String outputFile, DataRow row) in FormMain.cs:line 413
   at PdfCard.FormMain.CreateCard() in FormMain.cs:line 342_

code
```
PdfDocumentBuilder builder = new PdfDocumentBuilder();
PdfPageBuilder page = builder.AddPage(UglyToad.PdfPig.Content.PageSize.Custom);
page.PageSize = new UglyToad.PdfPig.Core.PdfRectangle(canvas.Left, canvas.Top, canvas.Right, canvas.Bottom);
PdfDocumentBuilder.AddedFont font = builder.AddTrueTypeFont(File.ReadAllBytes(fontFile));
var xy = new UglyToad.PdfPig.Core.PdfPoint(ms.Bounds.Left / zoom, ms.Bounds.Top / zoom);
if (Debugger.IsAttached)
       page.DrawRectangle(xy, ms.Bounds.Width / zoom, ms.Bounds.Height / zoom, 0.5m); page.AddText(text, (decimal)ms.Font.Size / zoom, xy, font);
File.WriteAllBytes(outputFile, builder.Build());
```

**Comment by EliotJones** [comment]
Hi there,

Custom page sizes aren't currently supported by `PdfDocumentBuilder`. I'll look at adding support for providing a `PdfRectangle` to specify the page size either tomorrow or next week.

**Comment by EliotJones** [comment]
Hi @mayurjansari 
I have now released a NuGet package which supports providing a custom width and height when adding a page, please take a look and let me know if it works for your use-case. https://www.nuget.org/packages/PdfPig/0.1.1-alpha001

(You'll need to show pre-release packages to install it)

**Comment by mayurjansari** [comment]
```
 PdfPageBuilder page = builder.AddPage(canvas.Width, canvas.Height);
```
working great.

```
PdfPageBuilder page = builder.AddPage(UglyToad.PdfPig.Content.PageSize.Custom);
page.PageSize = new UglyToad.PdfPig.Core.PdfRectangle(canvas.Left, canvas.Top, canvas.Right, canvas.Bottom);
```
this will give 
System.ArgumentException
Message : Cannot use $Custom for $AddPage using the $PageSize enum, call the overload with width and height instead.
Parameter name: size
StackTrace :    at UglyToad.PdfPig.Writer.PdfDocumentBuilder.AddPage(PageSize size, Boolean isPortrait)
