### ISSUE TITLE
Read text from a particular area

### ISSUE THREAD

**Issue by theonlyremedy** [UglyToad/PdfPig#148]
Is it possible to read text from a particular rectangular area using PdfPig? I would like to choose areas on a page and fetch text there. This will be really helpful for extracting tabular data. I know the height of the row and size of each cell, but with current page layout analysis, I'm unable to extract text in a row. I would appreciate some help on how to read text in table.

**Comment by BobLd** [comment]
Hi,

Quick question: how do you extract the information about the table's cells?

Concerning your question, if you already have the `PdfRectangle` of each table cell, you can do something like:
```csharp
using UglyToad.PdfPig.Geometry;

var wordsInCell = words.Where(w => cell.BoundingBox.Contains(w.BoundingBox)).ToList();
```
where `words` are the words in the page. It will give you the words that are included in the cell.

**NB**: the `Contains()` method is not yet available in the Nuget version of PdfPig, have a look [here](https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Geometry/GeometryExtensions.cs) to check how it is implemented.

**Comment by theonlyremedy** [comment]
Dear @BobLd ,
I'm not trying a generic approach that fits all documents. In this particular document that I'm working on, I know the exact location from where a table starts and then I know the width of each cell and height of each row. The main problem I faced with layout analysis is that some of the cells have text that are wrapped, so I was able to get only a part of it, the second part was really far down  in the list of words.

Thanks for pointing about contains method. That helped me a lot.

**Comment by BobLd** [comment]
Okay understood and good point with the xml documentation. 

I guess you would need to create a `PdfRectangle` with the area you want and then use the method I described above. 

If you are still facing some issues, would you be able to share a sample document?

**Comment by theonlyremedy** [comment]
@BobLd ,
I was able to achieve with a minor change. I used BoundingBox.Centroid, so its just checks if the point was in the area of cell, didn't require the extension method.

```
var wordsInCell = words.Where(w => cell.BoundingBox.Contains(w.BoundingBox.Centroid)).ToList();
```

Thanks for all the help :) All the best guys, great work with the library.
