### ISSUE TITLE
Table?

### ISSUE THREAD

**Issue by maxima120** [UglyToad/PdfPig#152]
How do I extract table text? I need to know where columns start/end

**Comment by BobLd** [comment]
What kind of table is it: Is is explicit (table is drawn) or implicit (table is not drawn)? 
Do you have a sample document?

**Comment by sir-deenicus** [comment]
I also have this question. Is there a way to extract tables a la grobid here: https://github.com/kermitt2/grobid/pull/546 ?

**Comment by maxima120** [comment]
I am talking about a drawn table in this particular case. No i dont have a document to share. But you can use anything with tabular data. an invoice for example? 

I dont know how PDF works. But even if there is a difference between explicit and implicit data - there is no difference for users like me. 

If there is a table of any kind - i would need to have a separator in the text or a set of objects clearly representing the data in the document (like rows and cells) etc. something i can work with to parse the document correctly.

**Comment by BobLd** [comment]
thanks @sir-deenicus for pointing out this implementation in grobid. The algo doesn't seems to be too complicated, I'll give it a look when I have time.

@maxima120, pdf documents do not keep information about table, so you need a method to rebuild it.

You have several research papers that tries to to tackle this problem:
- _pdf2table: A Method to Extract Table Information from PDF Files_ by Burcu Yildiz, Katharina Kaiser, and Silvia Miksch
- _PDF-TREX: An Approach for Recognizing and Extracting Tables from PDF Documents_ by Ermelinda Oro, Massimo Ruffolo
- _TAO: System for Table Detection and Extraction from PDF Documents_ by Martha O. Perez-Arriaga, Trilce Estrada, and Soraya Abad-Mota
- _Algorithmic Extraction of Data in Tables in PDF Documents_ by Anssi Nurminen

I've started implementing the algo you can find in [Nurminen](https://pdfs.semanticscholar.org/a9b1/67a86fb189bfcd366c3839f33f0404db9c10.pdf). It's early stage but you can have a look at the [BaseTableExtractor.cs](https://github.com/BobLd/PdfPig/blob/table-extractor-2/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor/BaseTableExtractor.cs) in my [table-extractor-2](https://github.com/BobLd/PdfPig/tree/table-extractor-2) branch. This will only work with explicit table.

**Comment by maxima120** [comment]
@BobLd thank you. so I gather there is no algorithmic solution (despite "algorithmic" in the title of the paper). Fine, that what i wanted to know.

<rant>why the world still uses dinosaurs like jpeg and pdf while we are already 1/5th into 21st century?</rant>
