### ISSUE TITLE
Ability to add outlines\bookmarks to an existing PdfDocument

### ISSUE THREAD

**Issue by icnocop** [UglyToad/PdfPig#156]
Hi.

Thank you for PdfPig.

I'd like to request the ability to add outlines\bookmarks to an existing PdfDocument.

Thank you.

**Comment by EliotJones** [comment]
Hi, this sounds like a useful feature request. I'll add it to the backlog, thank you.

**Comment by horoxix** [comment]
Add another person wanting this feature.

Has there been any movement on this? 

Thanks!
