### ISSUE TITLE
PdfDocumentFormatException Could not read the first token in the document at position 0.

### ISSUE THREAD

**Issue by marcelgruber** [UglyToad/PdfPig#164]
Hello! I'm consistently seeing this error message when reading multiple PDFs similar to and including [this PDF](https://github.com/UglyToad/PdfPig/files/4462536/ACH_20002.pdf).

```
Exception: UglyToad.PdfPig.Core.PdfDocumentFormatException
Message: Could not read the first token in the document at position 0.
Source: UglyToad.PdfPig
   at UglyToad.PdfPig.Parser.FileStructure.FileHeaderParser.Parse(ISeekableTokenScanner scanner, Boolean isLenientParsing, ILog log)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, ILog log, Boolean isLenientParsing, IReadOnlyList`1 passwords)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options)
   at UglyToad.PdfPig.PdfDocument.Open(Byte[] fileBytes, ParsingOptions options)
```

The failing code is 
```
using (var document = PdfDocument.Open(seekableStream.Stream))
{
	foreach (var page in document.GetPages())
	{
		result.Append(page.Text).Append(" ");
	}
}
```

**Comment by icnocop** [comment]
Have you tried to call `seekableStream.Position = 0;` before the call to `Open`?

**Comment by marcelgruber** [comment]
@icnocop Just tried it and the error messages are gone. Thank you. 

Are you aware of what might have been causing the initial issue? I've used PDFSharp in the past and never had to explicitly set the stream position.

**Comment by icnocop** [comment]
PDFSharp may internally reset the position of the stream.

Basically, when you read a stream to the end, it's position will be set to end.

In order to re-read the stream, you have to reset it's position back to the beginning.

**Comment by marcelgruber** [comment]
Thank you Sir. Hopefully this issue serves as a good reference for people in the future who run into a similar error.
