### ISSUE TITLE
Fix Bezier curve behaviour in Type 2 charstring for CFF font

### ISSUE THREAD

**Issue by EliotJones** [UglyToad/PdfPig#17]
It looks like the interpretation of Bezier curves in Type2CharStringParser has gone slightly wrong:
![image](https://user-images.githubusercontent.com/7862346/48673182-be674380-eb36-11e8-96ca-d3cd57c677c5.png)

This is probably in one of the curveto commands.

This B is from the ```PigProductionHandbookTests.CanReadContent``` test. Take a look and see where the error is and fix it.

**Comment by prepare** [comment]
I want to check this (Type 2 charstring parsing) too. 

Could you cut the
decoded form of 'embeded' CFF font in that pdf
and pasted here in base64 string?

**Comment by EliotJones** [comment]
Thanks, this was definitely an error I made when writing one of the commands from the spec and I haven't got round to using your implementation to correct my mistake yet but I've attached the string (hopefully the correct format).

``` AQAEAgABAQEWTEFaRktTK015cmlhZFByby1Cb2xkAAEBASD4HAH4FAT4HQwV+zf7jhwE6PpxBfeJD/exEeYcFlkSAAMBAQSeq2ZfaUNvcHlyaWdodCAyMDAwLCAyMDA0IEFkb2JlIFN5c3RlbXMgSW5jb3Jwb3JhdGVkLiBBbGwgUmlnaHRzIFJlc2VydmVkLiBVLlMuIFBhdGVudCBENDU0LDU4Mi5NeXJpYWQgaXMgYSByZWdpc3RlcmVkIHRyYWRlbWFyayBvZiBBZG9iZSBTeXN0ZW1zIEluY29ycG9yYXRlZC4vRlNUeXBlIDggZGVmAAABAAEAAAgCAA0PACIIAC4GADYDAEIIAEwFAFMIAGgBAG8AAHcAAYcAAEYCAAEATQBQAG0AoQDWAPMBBwEvAUoBnQHAAgoCdQK8AxcDjgO0BEIEvgUJBUoFmwYYBmoGyQb3Bx0HgAevB8cILQh8CM4JJgmOCfkKXwqZCtYLUwupDCAMkwziDVkNrQ38DowO1w8TD1IPaA/rEDwQgxD3EUIRnhHlEjkSdxLoEz4TmBPQE+oUHhQxFGMUrCCLvfjsvQGLvfgkvQOLBPiI+VD8iAb3jvvFFfs+95MF9+gG+yD7wBX3PveTBfySB/wGXhX3PveT9z77kwX8Bvi/Ffc++5P7PvuTBQ78KQ75P3cBpfdoA+r5PxV+M3ErbTXnlBi41rftquwIDvu5+wj5uwHH9wsD90L5RxVVPVD7GIr7Vgj7Vcf7GcE+HvUGU+he9xn3RBr3R7f3GsTnHg77ufsI+bsB9xz3CwP3IfsIFcDZx/cXjPdXCPdXTvcXVtgeIQbDLrj7GftFGvtFXfsbVC8eDil2AY33dwPy+wIVu9m49Kzx+y+BGH0wcCNsMggO+7H3aPEBqfeaA6n3zhUl95rxBw6A9037OHYSvfdHE2D3H4AVwa+ywB8ToMJnsVZWZmRVHhNgVrBkvh4O+6j5QXcBm/fPA/cJYxX3avlpBSYG+2r9aQUOV4D3B/hO9wcBq/ct9033LAP3rPkpFfs8O/sp+1Af+0yM1fsr9zwb9zrc9x73XfdGR/cv+0IfifsHFciqP/sk+yhrQVBQZ9L3KYwf9yuKsdLDGw5XoHb5HncB94D3JwP3gBb3J/ke+xIG+0A7pPsG9xDGBY0GDleL9xH4MvcOAffn9ywD+IsW9xH7iY0Hx70F6d/a4vcBGvcKOuH7JzM/bWZaHrb7AQWlrbynwxvWq2FWH4k/RkL7IvsTNz8YLwcOV4D3DPdI9wH3I/cMEvfV9y77HPcyE+ixrhVzsdJ13xv3OfDf9wfgTMY9mR+NBxPw26eywdAa5D7U+x83PXNyZB6q+wIFm6bDosAby6tuZFRKeFiKH1D7AckGE+jOy25LWmNlPE1NpZlwHw5XoHb3L/cG9533CAH3y/ckA/hbFvcv2fcGPfgR+04H+4r8IAUo97T7Lwf7JvehFY0H4vciobScsaC1GY8GiGGJY2Qa+yQHDleA9wv3Y/cE7fcRAffu9zAD+HD5HhX7+gZg++kFj6akja8b9xbAYkhGSG1MUFCdmW4fcPsGBXivzXnaG/dD8/b3DddtwVqsH6xdTJlNG3t/i4l9H5nvBfeQBg5XgPcE93f3APX3CQGp9yv3VfcuA/hd+ScVfIx5i2+JJYY3a0pQCEVKXiX7Dhr7L+D7FfdB9yHu9fcV9xsv2PsBTl54amseiAac18fQ9xuWCI2jnYucG/s//E0VRmrJ0IgfnY2Xj5MerJqtpLQbzKtXT0lpWlYfDlegdvih9xEBvPhfA7z5HhX7Efe+iQf7oPyfBfc1Bveg+L4F6wcOV4D0+GTyEqv3L/sZ9yP3Mvcj+xb3LxPU9yj34RUT5ERsXlU9GjPXLvc59yvu2vcK31PBTKMejgcT2MurqcLDGtpM4/ss+xYoQvsCHhPUUqpWymseE+T3F/uGFVJnt7qMH7qor72ZHsd7tWlSGl1oaFUeE9iI+GQVw6JjY2Jsa2iBH1ebY6e3GrSmrb8eDleC9wv3BvcA9273AwGp9yz3TPcvA+WCFZyKpYqljfCP4KrJwwjSzLbu9xsa9yw89xT7O/sjJSD7E/sS6D73Asa1nKmoHo6Kf1pvYWFuGWhzXH5diG2Jeot4jQj3SfhMFdClR0Z4iIGGgh90fW53YhtNbbvDH8+Ksbm+Gw6A90v7Nnb31/dLi3cSvfdHE1gTaPcf98wVwa+yvx/CimiwVhtWZmVVV7Bkvh+M+9cVwa+yvx8TmMKKaLBWG1ZmZVUfE2hXsGS+Hg4pdvhD90uLdxLD90YTsPH7AhW72bj0rPH7LYEYfDBwI2wyCBPQ9yP4QxXBrrK/H8KKaLBWG1ZnZVUfV4qwZL8bDrygdvdB9wb3pfcGi3cSnPj7E9j4NPdBFb/7QQX3OAb7Zfk2BftcBvti/TYF9zIGu/dBBaH3BhWz9yMFE+iWspW+lbMIjQaVY5dZl2O1+yMYDoiE9wX3VPcB9zX3AxLN9yv3Qfct+x33NBP0zY4Vhq3DhtYb9xrdobK8H7Wtp7vIGuJSxT6gHo0HE/jXp67DxxrIablcpB6oWlKULhs/OoWDYx/3KyYVjZiejawb0LJwWFlgajsfWQb7AQS/BhP018hwR0VOcEZxeYuNfB8Of4D3E/hP9xJtdxKu9zQT0Piu9x4Vf21YgV0b+xw74Pcb9yrp1PcNwbZ/fqofE7Cq9w0FE9CZcE+bPBv7YPs4+xT7evtU9wz7Jvd93cqbmacfDuSE9wv4VvcJAc33Lfet9zYDzY4VhrHDhtob9xj3AKfG0h/Mwrrk9xUa9wtf3kW/HrxKOKL7FBs+QoaCUx/3LfsBFY6YoY6tG/cX3UH7IIof+zUxP/sejB54douOfh8OQov3Efc09xD3IPcRAc33LQP4Z/gtFfuM9yD3m/cR/DT9NvhC9xH7qfc094wGDjugdvej9xD3LvcRAc33LQPNFvct96P3hvcQ+4b3LveX9xH8MAYO1oT3D/cr9wv3PfcSAa73NPez9ycD+Qn4FhX7j/sL8/shBoV/b4doG/sRNN33H/cm69P3E9W5fnuwH6v3DgWbakicNBv7cfs3+xT7dIofiiitM8lRCE/J5Gz3Dxvk5KGbuh8O3aB29673GfeXdwHN9y33j/csA835NhX9Nvct9673j/uu9yz5Nvss+5f7j/eXBw771qB2+TZ3Ac33LQPN+TYV/Tb3Lfk2Bw73g6B2+Kv3HwG++XwD+RoW9ykGZvk2BftbBkP7dHVAdDJ4PRmIBnzaduB22En3dRj7XwZg/TYF9yEGl/eUkN+O84/mGY0GmzOiK6E70/uYGPcLBt33m6Xap+ug4RmOBimOKY46Hg7eoHb4hXf3WXcBzfcg96r3IAP3Yhb3Xwf3Aonqh+QejoysPLc0s0MZ9yT7mAX3NPk2+yD7WAYljjCVMh6IBm3XY99j0vsg94sY+0b9NgYO9wKA9w34WvcNAa73Nffa9zUD9//5QRX7W/sV+yv7XvtU9wn7K/dc91n3Gvca93H3TvsF9y/7Yx+H+w0V9MUj+w37F1ApJCVN6PcY9xfH7fIfDnGgdveC9wn3ZfcHAc33K/dK9ysDzRb3K/eFBomZnYqfG+XYoby/H7OxocPNGs1uw2CtHq9eSJ0tGy5JhYNcH/crIBWOlqCOqhvXtmZNRlliOnV7jI5+Hw73AvjI9w0Brvc199r3NQP5Qo0VVpZRl1eaCI8H5LPS9wD3LRr3TPsF9zD7Yvtd+xT7LPte+3D3IvsE9yyBHpuKm4iaheVl227rbwj7r/d2FSVN7fcUjB/3Esfx8/PFJfsP+xhPKiUeDn2gdved9wL3U/cFAc33K/dJ9ysDzRb3K/eduQbJiqh0nTefOJtVlncI9zAGfqV243bXeslxuFyeCI4HxaDIxuEayXW6Y6sesVtFmicbOkKFg1of9ysjFY2WoI6wG9GKtWxNGlBeZT8eTwYOSID3EvhR9xFpdxK89y73JPcwE9izqhV2sdd22Bv3TeLs9wXqU8n7C7cfNKxlnrYarqupzc27eH6mHhO4rfcPBRPYnWNTmz8b+zMrM/sHKdRN9wRkH9xuq3NhGl9mbkVKTKCgYh4O1oD3DvjHdwHM9y33ivcsA8z5NhX8DAf7a+8t9z73RPTu92Qe+A77LPwYB/sLX1M7PV/G9wge+BgHDqiL9yj7E3b5NncSlPkBE3D4Jxb3d/k2Bfs2BjX7tAUTsHQ+djt6OgiIBnvfdth02zn3sRj7Owb3bP02BQ73rYv3Nfs19zj7I3b4hvdEi3cSmvnwEyz36hbL97YFEzSbz5bLl9cIjQaTPpZMmEfE+7YY9zkG90L5NgX7LwZU+6gFE0x9O3w8gUAIiQaB1oDTfNpV97AY+zYGUvuoBROMejh7OoBCCIkGgM994nzcWPepGPs3Bvc0/TYFDpGgdvk2dwGb+NkD+OkW+1z37fdS990F+0IGUvsPemR+bXtgGYkGe7F8rHe0UPcPGPtDBvdQ++H7V/vpBfdCBsP3DqC6nK6ZshmNBp5km2ikXMj7DhgOPID2QHb3e+rR8xKo9yr3IvcoE3z4afe1FfcHV+v7NzJIc3hpHqcpBZ+rwJy9G9aZZnEfhAf7QYz7Bk77ExoTvD3GQ+7FvaCyqx6OBhN8lFoF9x0GhqaJuLoaE7z7KMYVgoqCiYMebIFscmUbaXGessbJntuKHw6CgPcMM3b4E/cJ92Z3Esj3LPdZ9y8TfMj3JhVUiVCJax73FQYTvJHPBY0GUa7CdsQb9wT3BOP3RB/3Kow17PsJG0dYcGFuH4n3q/ssBvcs/EIVlYyUjZQet5WxqrQb0q1PPzNjWUpfaKq0gR+Jk4qUlRoO+zCA9wz3pvcJi3cSrPcwE9D4LvcRFYF0b4VnG0FPuuUf24q/xNsbs6aEg50fE7Cj9wUFE9CXa1+SYxv7Sin7Cfsj+y7wKvcyxb6Wl6YfDoCA9w0ydvgU9wj3ZncSrPcu91j3LBN8+BP5WhX7nYkHrXVcoE8b+wkkLPs5jB8TvPss6Cj3CMrGp8KqHo0GE3ySQwX3GwaJrInFwhr4yAf7LPyAFRO8foqAiIAeYIJobV8bTGK/3tivydC6rGlilB+Mg4yAgxoOPID3Bujz7vABrPcl90f3IQP4gfdYFY2WjqKlGvcNT/cP+zL7Pj77HfsQ+y3qKvc6zciWn70ed/IFfmJhhFcbRE2pyoYfivMVtI+lxcsb0ZtNZh8O+56gdvgN9wT3BPcMgXcS2fctE9j3exb4Dez3BCkHE+ikB7ugsr2fm4iHmB4T2JH3CQUT6JF2cY9pG19WfmdlH19jeUpQGnhL+wTL/A0HDnX7ZfcI7PcE96H3B4B3Eqz3LvdN9ywT7Pig9+wVE9zUjbSNqh77GAYT7IZRBYkGs3JhqEgb+wwlJ/sx+yHhKfcNw7qitKgfjWsGMVRkQ1JVnp1sHm37BwVyt89+yxvT1Jm5wR/CvJ7Y6Rr7LPcnFX6Ke4eAHmeBbHFkG0tnxNTkuL3CtahwY5YfjYOMgYEaDnagdvgN9w/3ZncByPcs9zT3LAPIFvcs97YGloyYj5UeppakpbMbxKFfSx/7ofcs97IH9ydBzipvb4R/dB5zf3d6e3YIifer+ywGDvvhoHb4fXfb9y0SxPc1+zH3LBPo92kW+H37LPx9BxPw1/lSFVpral+MH2GKq2m7G72rrbUft4psrFobDkqgdvh9d/eFdwHI9ywD92n5WhX7LP1a9yz3LQayu/cK+10F908G+1z3t/dD91oF+0sGKPsnf3h/d4B3GYkGDvvgoHb5WncByPcsA8gW9yz5WvssBg73kaB2+A73DoB3Esj3KPcn9yj3KPcoE7zIFvcoBhPc97EHl4yZkJcepJSiqbIbu6FhTR/7pvco97IHl42bj5YeqJWko64bvKJiRB/7nvco97QH9yZEzS1nbYN7cB50fXV4eXEIiQa+dlmrTBs3YF1sdh+IBhO8hM0F+xQGjWCNV04aDnagdvgN9w+AdxLI9yz3NPcsE7jIFvcsBhPY964HmY2Zj5Uep5WkqLUbwqFgTB/7o/cs97YH9yRAzSc6WVxsdx6IBhO4hM4F+xgGjWCNV04aDm2A9wH3uvcAAaz3MfdZ9zED97r4iBX7MSMm+zL7MvcCLfcj9xf3E933R/cnJ/L7Kh+H+wAV0KdBQjNlUFBKaMrf06bW1B8OgvtFdvdP9wn3p/cLgHcSyPcs91n3LhPcyPtaFfcs94eNBmuhuXPGG/cB9wXf90YfE+z3MCvoIERTcFdnHokGE9yEzwX7GAaNXo1USxr3LFsVE+yUjJWNkx64lbGrthvPrlA9OGRUSV9oqrSBH4mUipaXGg77d6B29/v3IYB3Esj3LBOwyBb3LPeMBhPQl4yXjZUeupWxqcMbnJiJiJYf9yQHjYCEi30bXE9tRHIfhwYTsIblBfsXBo1hjVxDGg77QYD297/0Abj3Jsz3JwOsoxV3sMR8yxv3INPP5h+K02S6LqsIT6B4l6IapKCasLW1e3+hHqb0BZptWJhSG/sNPUYvH4pSslTwaQjEeJp/chpyeHtdXlGfnG8eDvuEgPcR95v3BAHd9ykD3fjZFS9K+wTM+1wHRplcp24ecqO0ebwbtq+Rk58fivcHBYh8gop2G119psYf90X3AfcE+wH3GQcOc4D3DzB2+H13Esb3Lfcx9y0TePie+H0V+y0GE7j7twd/in+Hgh5zgXNuYRtWdLbSH/eb+y37swf7K9RN7uO5vameHo4GE3iSRgX3GAaJtIm/yxoOPov3I/sOdvh9dxKU+JQTcJT4fRX3Rvx9BfcsBvdK+H0F+zQGTPt3BROwgGGDZoNjCIgGhLKCsn+0Sfd3GA73LIv3FPdY9zmLdxKW+XYTsJb4fRX3Ivx9BfcjBrz3QAUT0Ji4lbmUyAiNBpVOlGCXW7n7QBj3Iwb3Kvh9BfspBmH7VoBTgVSEUxmJBoHDfsJ+wlr3Vxj7DAZX+11/W31TgVMZiQaDw4HCgb1k91wYDjOgdveNd/eYdwGO+JQDkvh9Ffc2+4T7OvuNBfc7Brnjl6OYo5elGY4Gl3KXcplzvDMY90AG+zf3lPc1930F+zkGYDx+c39yfnEZiQZ+on6kfaRb3BgON/h9dwGR+JYDkfh9FfdH/FMFkX+Mg4YahIiDhoQefHJyc3R/dH1zgniIq/sVGLGQw5vAucK8utnR91b3BvfWGPs3Bk/7hIRvg2aEcRmIBoWlga+DqEL3hBgO+x6L9w33jPcMAaH4PQOhFvg99w37f40Gp6akqqar9yf3TRjm/CT7DPdriQdvbXVzb2r7LvtVGA78Jvg596MBrvcbA675SBWi+6MF5Aai96MFDvst+UB3AaX4KwP3PPg7FZnipOyq4C+DGF1AYClsKQj35ZUVmeKl7KngL4MYXUBgKWwpCA4g92PpAan4TAOp98EVLfhM6QcO+y35P3cBpPgrA+r5PxV9M3ErbTXnlBi41rftquwIwIIVfTNxK20155QYuda27arsCA54oHb4DfcE9wT3DAHZ9y33JPcsA/d7FvgN9yT8Dfcs+H37vZwHwae027uyf36jHqj3BwWdbU2XVxv7KyI/+xsfdkv7BMv8DQcOgJb5Npf7WZb3Kpa9lfxzkQb4SpD7S5H8b5a4kZ+SB4CW+TaX+16W9y+WvJb8dJII+EqR+0yR/G+WuJGokQkeoGBFgpn/DAn3BAr3LAv3LJQMDYwMDveYFPjzFQ==```
