### ISSUE TITLE
Implement OpenType fonts

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#173]
Hi,

It would be very useful to support OpenType fonts. For the moment they are not supported, see `UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory`, l. 242

**Comment by EliotJones** [comment]
This should now be available in version 0.1.2-alpha003 https://www.nuget.org/packages/PdfPig/0.1.2-alpha003 please give it a try and let me know if it works.

**Comment by BobLd** [comment]
I've tested it on several pdfs, it works perfectly. Thanks Eliot!
