### ISSUE TITLE
InvalidCastException

### ISSUE THREAD

**Issue by spetersn** [UglyToad/PdfPig#174]
Hi, many thanks for this library!

I'm getting an issue opening this document:
https://drive.google.com/open?id=1cEO9tKkB2iEEqPDtpsrbOqVGtaVdpcVI

While calling document.GetPage(1) it throws this error:

System.InvalidCastException: 'Unable to cast object of type 'UglyToad.PdfPig.Tokens.IndirectReferenceToken' to type 'UglyToad.PdfPig.Tokens.NumericToken'.'

Could you take a look please?

**Comment by EliotJones** [comment]
Hi, sorry to hear about the issue, I'll try to take a look over the weekend.

**Comment by EliotJones** [comment]
Hi, I have added a fix for this and it's available in this version https://www.nuget.org/packages/PdfPig/0.1.2-alpha002
Please give it a try and let me know

**Comment by spetersn** [comment]
Eliot, thank you very much! It works well now!
