### ISSUE TITLE
startxref is not in the last 1024 bytes

### ISSUE THREAD

**Issue by crcelso** [UglyToad/PdfPig#176]
Hi Eliot, first of all, I would like to thank you for this awesome library! I'm having some problems with pdfs generated by the pdfSharp lib, where after the '%%EOF' tag it contains a lot of '\0' characters and it makes the method GetStartXrefPosition fails. I'm using a function that removes all this trailling characters to solve this. Have you ever had this issue?

**Comment by EliotJones** [comment]
Hi there, glad to hear the library is useful.

I've not encountered this issue before, do you have an example file that replicates the issue I could test against please? It should be fairly easy to fix in the library with an example file to work against.

**Comment by crcelso** [comment]
Sorry, but I am not allowed to send the pdf file. I'm attaching an image showing the end of the file when you open in a text editor like vs code. The last line has a length of more than 4k characters and they are all empty. If you want to simulate this you can read any pdf as bytes and append this array  [10, 0, 0, 0... more 2k zeros] to the end before using the PdfDocument.Open(). The first '10' value is just the new line character. 

![image](https://user-images.githubusercontent.com/52331207/81742204-1b1a9480-9476-11ea-9348-2927ba49e359.png)

**Comment by davidpene** [comment]
Also seeing this in production. Also can't send the PDF sorry :( 
If I can be of anymore help, let me know.

**Comment by EliotJones** [comment]
Thanks for the reproduction, I'll try to get round to looking into it soon, I've been super busy recently so it might not be this weekend.

**Comment by EliotJones** [comment]
This fix is now available in the 0.1.2-alpha003 release which is published on NuGet https://www.nuget.org/packages/PdfPig/0.1.2-alpha003 please try it out and let me know if you encounter any issues.

**Comment by crcelso** [comment]
Thanks, Eliot!! It's working perfectly in all the files that I have for testing.

**Comment by EliotJones** [comment]
Glad to hear it works :)

**Comment by last-Programmer** [comment]
I am getting similar kind of error 

Could not find the startxref within the last 2048 characters.

I am using 0.1.8 version. is there anyway to fix this error. The pdf is generated by crystal reports.

**Comment by crcelso** [comment]
I can't remember the exact solution that I end up using to solve this problem but it was something like below:

1. Catch PdfDocumentFormatException
2. Read file as bytes
3. Detect %%EOF using byte sequence 0x25, 0x25, 0x45, 0x4f, 0x46
4. Copy content to another byte array from the start of the file bytes to the end of the sequence above plus one byte
5. Set the last byte to 10
6. Try to open the fixed file again

I remember that it worked for most cases, but there was still some files that it didn't worked.
