### ISSUE TITLE
Can PdfPig extract table organized by horizontal and vertical lines?

### ISSUE THREAD

**Issue by AlexanderLeung9** [UglyToad/PdfPig#188]
At least recognize them, locate them; then it will be better to extract them to a matrix.

**Comment by BobLd** [comment]
Hi @AlexanderLeung9, that's a great question but it is in fact way more complicated than it seems... 

I have some work in progress in the following branches (I don't really remember the difference between the two 😄): [table-extractor](https://github.com/BobLd/PdfPig/blob/table-extractor/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor.cs) and [table-extractor-2](https://github.com/BobLd/PdfPig/blob/table-extractor-2/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor/BaseTableExtractor.cs). Any feedback welcome

If you want to have a better understanding of the problem, you can have a look at Anssi Nurminen's [Algorithmic Extraction of Data in Tables in Pdf Documents](https://pdfs.semanticscholar.org/a9b1/67a86fb189bfcd366c3839f33f0404db9c10.pdf).

Also, I've put an extended list of research papers here:
- https://github.com/BobLd/DocumentLayoutAnalysis/blob/master/README.md#table

**Comment by AlexanderLeung9** [comment]
Thank you!
However, could you show me how to detect positions and lengths of lines? Because it is the critical start point for me regardless of extracting tabular data.
Thanks and regards!

**Comment by BobLd** [comment]
Sure, you can access the lines in a page by using the following: `var paths = page.ExperimentalAccess.Paths;`

Doing so, you will not only get lines but also curves present in the page (so called `PdfPath`), so you will need to do some filtering. This is what the `GetProcessLines` function does [here](https://github.com/BobLd/PdfPig/blob/f5788dac5d21d3050f9717af09c3f6725b1dc16d/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor/BaseTableExtractor.cs#L215-L226). 

You'll also need to take in account that `PdfPath` can be composed of several lines, so you'll need to 'separate' them, and then filter for vertical and horizontal lines (hence removing diagonal lines).

Another pain point is that sometimes, what you _see_ as a line is in fact a filled rectangle... this is tackled [here](https://github.com/BobLd/PdfPig/blob/f5788dac5d21d3050f9717af09c3f6725b1dc16d/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor/BaseTableExtractor.cs#L228-L257) in the function.

Finally, sometimes what you _see_ as one single line is in fact several lines overlapping... this is handled [here](https://github.com/BobLd/PdfPig/blob/f5788dac5d21d3050f9717af09c3f6725b1dc16d/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TableExtractor/BaseTableExtractor.cs#L275-L298)

If you are only interested in detecting the table region, you can have a look at this function [here](https://github.com/allenai/pdffigures2/blob/217b0daebfa65faf9cdf7bcbe70f6612207d7102/src/main/scala/org/allenai/pdffigures2/Box.scala#L62-L98) from the [pdffigures2](https://github.com/allenai/pdffigures2) library. You could see the `List[Box]` parameter as `List<PdfRectangle>` from your `PdfPath`s in PdfPig.
You can get this list of boxes using `var boxes = page.ExperimentalAccess.Paths.Select(p => p.GetBoundingRectangle()).Where(bb => bb.HasValue).Select(bb => bb.Value).ToList();`
The pdffigures2's function will extract regions of overlapping paths. Then you'd need to use some heuristics do determine if it is a table or not. As far as I understand, in the pdffigures2 library they look for a caption containing the word 'Table' close to the region.

Hope this helps

**Comment by AlexanderLeung9** [comment]
Thank you!
In my comprehension, BaseTableExtractor.GetCandidates() implements the Box.mergeBoxes() of python, is it? I am really interested in detecting the table region.
Besides, what's the "ClusteringAlgorithms.GroupIndexes()", could you show me?

**Comment by BobLd** [comment]
The `Box.mergeBoxes()` (written in scala) is not used in `BaseTableExtractor`, it uses instead a different method: 
- The `BaseTableExtractor` method checks if 2 lines should be merged using the `ShouldMerge()` method. 
- The `Box.mergeBoxes()` checks instead the bouding boxes and merges the overlapping ones. As far as I remember, every time their algo find overlapping bounding boxes, it merges them to create a single bounding box and the algo continues. It does not check lines, but their bounding boxes.

The advantage of pdffigures2's `Box.mergeBoxes()` is that it can also detect chart/graph areas.

The `ClusteringAlgorithms.GroupIndexes()` is `internal` for the moment and is available [here](https://github.com/UglyToad/PdfPig/blob/98af575ee32b1a00b5a79430ef524ff0d5edb8bd/src/UglyToad.PdfPig.DocumentLayoutAnalysis/Clustering.cs#L226-L249). It takes as input the adjacency list and uses [DFS](https://en.wikipedia.org/wiki/Depth-first_search) to group the elements.
You could implement something similar to `Box.mergeBoxes()` by doing the following (__This is not tested__):

```csharp
var bboxes = page.ExperimentalAccess.Paths.Select(p => p.GetBoundingRectangle()).Where(bb => bb.HasValue).Select(bb => bb.Value).ToList();
int[] overlappingIndexes = Enumerable.Repeat(-1, bboxes.Count).ToArray();
for (var b = 0; b < bboxes.Count; b++)
{
    var current1 = bboxes[b];

    for (var c = 0; c < bboxes.Count; c++)
    {
        if (b == c) continue;
        var current2 = bboxes[c];

        // check if overlap
        if (GeometryExtensions.IntersectsWith(current1, current2))
        {
            if (overlappingIndexes [c] != b)
            {
                overlappingIndexes [b] = c;
                break;
            }
        }
    }
}

var indexesToMerge = ClusteringAlgorithms.GroupIndexes(overlappingIndexes);

var groupedBboxes = new List<List<PdfRectangle>>();
foreach (var group in indexesToMerge)
{
    groupedBboxes.Add(group.Select(i => elements[i]).ToList());
}
```

Results would be different from `Box.mergeBoxes()` as this method does not create a new boudning box every time it founds 2 that overlap.

**Comment by BobLd** [comment]
Also I forgot to mention, since you want to work with paths, it's better to set `ClipPaths` to `true`:
```csharp
PdfDocument.Open(path, new ParsingOptions() { ClipPaths = clipPaths })
```

**Comment by AlexanderLeung9** [comment]
Thank you a lot!
However, I can't access ClusteringAlgorithms.GroupIndexes() outside the library, and I don't know what "elements" is at the last line of code.
When I inspected the bboxes, I found too many rectangles while my document has only several. The amount of bboxes is at least ten times of actual rectangles even if I removed some that are zero area.

**Comment by AlexanderLeung9** [comment]
[aaa.pdf](https://github.com/UglyToad/PdfPig/files/4922301/aaa.pdf)
Such as this file, I got 15 rectangles which puzzled me very much.
![bboxes](https://user-images.githubusercontent.com/52726330/87492439-25772b80-c67d-11ea-940d-33c23b58ab25.png)

**Comment by AlexanderLeung9** [comment]
However, this file I got only one rectangle. Why is their difference so large?
[Doc1.pdf](https://github.com/UglyToad/PdfPig/files/4922320/Doc1.pdf)

**Comment by AlexanderLeung9** [comment]
By the way, the version of PdfPig I use is 0.1.1.0.

**Comment by BobLd** [comment]
It's an interesting example of what I was describing.
- __aaa.pdf__
     - Contains clipping paths, so don't forget to use the `ClipPath` option when you open the document, this lowers the number of paths to 12 😄:
     ```csharp 
     PdfDocument.Open(path, new ParsingOptions() { ClipPaths = true })
     ```
     - The 'lines' you see are in fact rectangles filled with black color. so you need minimum 4 filled rectangles to draw the 'rectangle' you see. Below is a screenshot to show you how it's done. The paths are draw in yellow (ignore the fact that they are not perfectly overlapping the image)
![image](https://user-images.githubusercontent.com/38405645/87542046-31bdb180-c69a-11ea-8fde-993ec8f8089d.png)

- __Doc1.pdf__
     - It uses the most straighforward way to draw a rectangle: it is actually a stroked rectangle. It is not filled and there are no clipping paths.
![image](https://user-images.githubusercontent.com/38405645/87542375-c2948d00-c69a-11ea-9309-b5f96dba7b67.png)

**Comment by AlexanderLeung9** [comment]
I'm sorry I can't find any ParsingOptions with ClipPaths in version 0.1.1.0. Do I need to upgrade to which version? Or what version are you using?

**Comment by BobLd** [comment]
I forgot about that, please use the latest version (0.1.2.0 I think)

**Comment by AlexanderLeung9** [comment]
OK, I saw! Thanks!
However, Why are there 8 rectangles whose width and height are small than 1? And can I judge actual "lines" by detecting if their width and height are larger than or equal to 1?
![捕获](https://user-images.githubusercontent.com/52726330/87655865-56de1d00-c78b-11ea-96ad-dd5557f060e7.PNG)

**Comment by BobLd** [comment]
Closing the issue - Use the .Net ports of [Tabula](https://github.com/BobLd/tabula-sharp) or [Camelot](https://github.com/BobLd/camelot-sharp) to extract pdf table data.

Feel free to reopen it if need be
