### ISSUE TITLE
Some tests fail when not using the invariant culture

### ISSUE THREAD

**Issue by Poltuu** [UglyToad/PdfPig#190]
That's because ToString() is used instead of ToString(CultureInfo.InvariantCulture) in many places.
I have a commit if you are intereseted

**Comment by EliotJones** [comment]
Hi, thanks for your issue report. Sorry you encountered this issue. If you have time to open a PR that would be great, otherwise I can try to fix it when I next have some free time.

**Comment by EliotJones** [comment]
I switched to French on my system and fixed any tests I saw failing, though I might have missed other issues. Let me know if this fixes tests for you.

**Comment by Poltuu** [comment]
I's all good now 👍
