### ISSUE TITLE
System.IO.EndOfStreamException: Could not read a buffer of 2 bytes

### ISSUE THREAD

**Issue by davidpene** [UglyToad/PdfPig#192]
Seeing this exception in our logs.
Unfortunately I don't have access to a file to replicate the issue.

> System.IO.EndOfStreamException: Could not read a buffer of 2 bytes. at UglyToad.PdfPig.Fonts.TrueType.TrueTypeDataBytes.ReadBuffered(Byte[] buffer, Int32 length) at UglyToad.PdfPig.Fonts.TrueType.TrueTypeDataBytes.ReadSignedShort() at UglyToad.PdfPig.Fonts.TrueType.Parser.Os2TableParser.Parse(TrueTypeHeaderTable header, TrueTypeDataBytes data, Builder register) at UglyToad.PdfPig.Fonts.TrueType.Parser.TableParser.Parse[T](TrueTypeHeaderTable table, TrueTypeDataBytes data, Builder register) at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.ParseTables(Single version, IReadOnlyDictionary`2 tables, TrueTypeDataBytes data) at UglyToad.PdfPig.Fonts.TrueType.Parser.TrueTypeFontParser.Parse(TrueTypeDataBytes data) at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.ReadDescriptorFile(FontDescriptor descriptor) at UglyToad.PdfPig.PdfFonts.Parser.Parts.CidFontFactory.Generate(DictionaryToken dictionary) at UglyToad.PdfPig.PdfFonts.Parser.Handlers.Type0FontHandler.Generate(DictionaryToken dictionary) at UglyToad.PdfPig.PdfFonts.FontFactory.Get(DictionaryToken dictionary) at UglyToad.PdfPig.Content.ResourceStore.LoadFontDictionary(DictionaryToken fontDictionary) at UglyToad.PdfPig.Content.ResourceStore.LoadResourceDictionary(DictionaryToken resourceDictionary) at UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean clipPaths) at UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, Boolean clipPaths) at UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) at...

**Comment by EliotJones** [comment]
Hi, sorry you're running into this. I'm not really sure what the cause could be unfortunately without a file. I've had a guess but I might need to take several guesses to find a fix.

**Comment by EliotJones** [comment]
Closing this since I'm not sure if the fix worked but it has been inactive quite a while.
