### ISSUE TITLE
Why are there 8 more rectangles whose width and height are small than 1?

### ISSUE THREAD

**Issue by AlexanderLeung9** [UglyToad/PdfPig#194]
Why are there 8 more rectangles whose width and height are small than 1 in the PDF "aaa.pdf"? Are they necessary really? If not, can they be eliminated in code of the library.

        public static void Test()
        {
            using (PdfDocument document = PdfDocument.Open(@"aaa.pdf", new ParsingOptions { ClipPaths = true }))
            {
                Page page = document.GetPage(1);
                var bboxes = page.ExperimentalAccess.Paths.Select(p => p.GetBoundingRectangle()).Where(bb =>
                  bb.HasValue && bb.Value.Width > 0 && bb.Value.Height > 0).Select(bb => bb.Value).ToList();
                int count = bboxes.Count;
            }
        }

[aaa.pdf](https://github.com/UglyToad/PdfPig/files/5013344/aaa.pdf)
![捕获](https://user-images.githubusercontent.com/52726330/89137075-3a9ef600-d569-11ea-8796-c032f791b2d3.PNG)

**Comment by EliotJones** [comment]
Hi @AlexanderLeung9 , it looks like these rectangles are present in the underlying document. The page content stream defines 8 rectangles of the given width and height. It looks like the PDF producer (Microsoft Word) must put rectangles in at the 'corners' of the visible rectangle for some reason. We shouldn't exclude them from the page content because it should correspond exactly to the underlying content stream, the best approach is to write some post-processing logic to exclude them for your use-case, e.g.

```
var usefulRectangles = bboxes.Where(x => x.Width > 1 || x.Height > 1).ToList();
```

By doing this on a consumer side we preserve data that might be useful for other use-cases.

The page's content stream with the rectangles defined at the end:

```
q
90.51 753.81 414.42 15.63 re
W* n
 /P <</MCID 0/Lang (en-US)>> BDC q
90.504 753.84 414.43 15.6 re
W* n
BT
/F1 10.56 Tf
1 0 0 1 95.664 758.04 Tm
/GS7 gs
0 g
/GS8 gs
0 G
 -0.0182 Tc[(aaa)] TJ
ET
Q
 EMC  /P <</MCID 1/Lang (en-US)>> BDC q
90.504 753.84 414.43 15.6 re
W* n
BT
/F1 10.56 Tf
1 0 0 1 110.78 758.04 Tm
0 g
0 G
[( )] TJ
ET
Q
 EMC Q
 /P <</MCID 2>> BDC 0 g
90.024 769.44 0.48 0.48 re
f*
90.024 769.44 0.48 0.48 re
f*
90.504 769.44 414.43 0.48 re
f*
504.94 769.44 0.48001 0.48 re
f*
504.94 769.44 0.48001 0.48 re
f*
90.024 753.84 0.48 15.6 re
f*
90.024 753.36 0.48 0.48 re
f*
90.024 753.36 0.48 0.48 re
f*
90.504 753.36 414.43 0.48 re
f*
504.94 753.84 0.48001 15.6 re
f*
504.94 753.36 0.48001 0.48 re
f*
504.94 753.36 0.48001 0.48 re
f*
 EMC  /P <</MCID 3/Lang (en-US)>> BDC BT
/F1 10.56 Tf
1 0 0 1 90.024 741.94 Tm
0 g
0 G
[( )] TJ
ET
 EMC 
```

**Comment by AlexanderLeung9** [comment]
Thanks a lot!
But the relationships among PdfPath, PdfSubpath and PdfRectangle still puzzle me a lot. What do they correspond to in an actual document? Last month @BobLd told me some lines are defined as rectangles. So, when a line is a line, and when a line is a rectangle, or a path somewhat...?
I think it should be a lengthy illustration to clarify those concepts, so I have an example now. Could you please teach me how to recognize lines in the table (16 * 3 matrix) of the "1__2.pdf" given by me? Besides, draw attention to exclude two underlines below the table. I think I can understand well from an actual example.
Thank you very much!

[1__2.pdf](https://github.com/UglyToad/PdfPig/files/5019581/1__2.pdf)

**Comment by InusualZ** [comment]
> 
> 
> Thanks a lot!
> But the relationships among PdfPath, PdfSubpath and PdfRectangle still puzzle me a lot. What do they correspond to in an actual document? Last month @BobLd told me some lines are defined as rectangles. So, when a line is a line, and when a line is a rectangle, or a path somewhat...?
> I think it should be a lengthy illustration to clarify those concepts, so I have an example now. Could you please teach me how to recognize lines in the table (16 * 3 matrix) of the "1__2.pdf" given by me? Besides, draw attention to exclude two underlines below the table. I think I can understand well from an actual example.
> Thank you very much!
> 
> [1__2.pdf](https://github.com/UglyToad/PdfPig/files/5019581/1__2.pdf)

Yeah, It's a complex topic like you have seen. I think you would have to use a combination of "test" to discard some PdfSubPath.
Maybe you can have detection margin? Like, only recognizing only rect inside a given area? 

**PdfPath** is a object that describe a set of PdfSubPath that share the same filling/stroking properties.
 
**PdfSubPath**  is a object that contain a set of command that draw a certain path (any shape).

**PdfRectangle** is used as bounding box, to see the area that a set of PdfSubPath cover.

Maybe @BobLd have a better description for them.

**Comment by EliotJones** [comment]
@InusualZ gives a good overview of the paths API, as an additional demonstration this image draws each line command in a subpath in the document you provided in a different color (the same color for all lines in the same subpath and lines with length < 1 are drawn as dots):

![1__2-out](https://user-images.githubusercontent.com/7862346/89418791-716f3a80-d728-11ea-9aa2-794067539c1b.png)

As you can see what looks like a fairly simple table of 21 lines is actually made up of a load of different line commands, over 300 of them. I'm going to look into it further when I next have time but it's going to take a bit of post-processing to extract the lines here.

On the rectangle vs line thing, I think it's basically that a line is the same thing as a rectangle, so for example:

![image](https://user-images.githubusercontent.com/7862346/89419320-273a8900-d729-11ea-8c56-e3db81146c94.png)

A filled rectangle is visually indistinguishable from a line, unfortunately PDF producers can use both approaches to render lines. For now I'd focus on building detection around just lines, but it's important to be aware rectangles can be used to appear as lines too.

Getting the lines out and finding the actual lines would be something like this:

```
bool IsHorizontal(PdfSubpath.Line l) => Math.Abs(l.From.Y - l.To.Y) < double.Epsilon;
bool IsVertical(PdfSubpath.Line l) => Math.Abs(l.From.X - l.To.X) < double.Epsilon;

var usefulLines = page.ExperimentalAccess.Paths
    .SelectMany(x => x.SelectMany(y => y.Commands))
    .OfType<PdfSubpath.Line>()
    .Where(x => x.Length >= 1)
    .ToList();

var horizontalGroups = usefulLines.Where(IsHorizontal)
    .GroupBy(x => (int) x.From.Y)
    .ToDictionary(x => x.Key, x => x.ToList());

var verticalGroups = usefulLines.Where(IsVertical)
    .GroupBy(x => (int) x.From.X)
    .ToDictionary(x => x.Key, x => x.ToList());
```

But because this document uses double lines as cell borders you will need some additional processing. The cells in this table are drawn a bit like this:
![image](https://user-images.githubusercontent.com/7862346/89421100-86010200-d72b-11ea-9368-e0aeff20725a.png)

**Comment by AlexanderLeung9** [comment]
> > Thanks a lot!
> > But the relationships among PdfPath, PdfSubpath and PdfRectangle still puzzle me a lot. What do they correspond to in an actual document? Last month @BobLd told me some lines are defined as rectangles. So, when a line is a line, and when a line is a rectangle, or a path somewhat...?
> > I think it should be a lengthy illustration to clarify those concepts, so I have an example now. Could you please teach me how to recognize lines in the table (16 * 3 matrix) of the "1__2.pdf" given by me? Besides, draw attention to exclude two underlines below the table. I think I can understand well from an actual example.
> > Thank you very much!
> > [1__2.pdf](https://github.com/UglyToad/PdfPig/files/5019581/1__2.pdf)
> 
> Yeah, It's a complex topic like you have seen. I think you would have to use a combination of "test" to discard some PdfSubPath.
> Maybe you can have detection margin? Like, only recognizing rect inside a given area?
> 
> **PdfPath** is a object that describe a set of PdfSubPath that share the same filling/stroking properties.
> 
> **PdfSubPath** is a object that contain a set of command that draw a certain path (any shape).
> 
> **PdfRectangle** is used as bounding box, to see the area that a set of PdfSubPath cover.
> 
> Maybe @BobLd have a better description for them.

Thank you for explaining. The suggestion you provided is so wonderful that I used before. However, there are still some documents that can not be extracted tabular data by detecting a specified region first. Because words around the table vary a lot. So the unique solution to solve the exceptions is to detect table lines.

**Comment by AlexanderLeung9** [comment]
@EliotJones 
Thank you for your explanation and code sample.
I have refined your code to get the final results. You can have a look at it to check if it is correct or if there is anything that I omitted. Besides, as you said, situation of rectangles is also important, so code for this situation is still welcomed. If I encounter situation of rectangles, I will share them out.
My code is as follows, in which List<double> horizontalLines and List<double> verticalLines are what I wanted eventually, so that I can utilize them to organize words of cells into a matrix.

public static void Test()
{
	bool IsHorizontal(PdfSubpath.Line l) => Math.Abs(l.From.Y - l.To.Y) < double.Epsilon;
	bool IsVertical(PdfSubpath.Line l) => Math.Abs(l.From.X - l.To.X) < double.Epsilon;

	using (PdfDocument document = PdfDocument.Open(@"1__1.pdf", new ParsingOptions { ClipPaths = true }))
	{
		Page page = document.GetPage(1);

		var usefulLines = page.ExperimentalAccess.Paths
							.SelectMany(x => x.SelectMany(y => y.Commands))
							.OfType<PdfSubpath.Line>()
							.Where(x => x.Length >= 1)
							.ToArray();

		var verticalGroups = usefulLines.Where(IsVertical)
			.GroupBy(x => (int)x.From.X).OrderBy(y => y.Key)
			.ToDictionary(x => x.Key, x => x.ToList());
		//int vCount = verticalGroups.Sum(g => g.Value.Count);
		double maxTop = verticalGroups.Max(g => g.Value.Max(v => Math.Max(v.From.Y, v.To.Y)));
		double minBottom = verticalGroups.Min(g => g.Value.Min(v => Math.Min(v.From.Y, v.To.Y)));

		var horizontalGroups = usefulLines.Where(IsHorizontal).Where(l => minBottom <= l.From.Y && l.From.Y <= maxTop)
			.GroupBy(x => (int)x.From.Y).OrderByDescending(y => y.Key)
			.ToDictionary(x => x.Key, x => x.ToList());
		//int hCount = horizontalGroups.Sum(g => g.Value.Count);

		List<double> horizontalLines = horizontalGroups.Keys.Select(k => horizontalGroups[k].First().From.Y).ToList();
		// Merge lines that have almost no space to place anything between them.
		for (int i = horizontalLines.Count - 1; i > 0; --i)
		{
			double y1 = horizontalLines[i];
			double y2 = horizontalLines[i - 1];
			if (y2 - y1 < 2)
			{
				if (horizontalGroups[(int)y1].Count > horizontalGroups[(int)y2].Count)
				{
					horizontalLines[i - 1] = y1;
				}
				horizontalLines.RemoveAt(i);
			}
		}

		List<double> verticalLines = verticalGroups.Keys.Select(k => verticalGroups[k].First().From.X).ToList();
		// Merge lines that have almost no space to place anything between them.
		for (int i = verticalLines.Count - 1; i > 0; --i)
		{
			double x2 = verticalLines[i];
			double x1 = verticalLines[i - 1];
			if (x2 - x1 < 2)
			{
				if (verticalGroups[(int)x2].Count > verticalGroups[(int)x1].Count)
				{
					verticalLines[i - 1] = x2;
				}
				verticalLines.RemoveAt(i);
			}
		}
	}
}

**Comment by AlexanderLeung9** [comment]
Hi, masters!

I have several PDF samples that can no be extracted lines correctly while many of others can work normally. I found more lines to be extracted in debugging, but I couldn't see them in PDFs. And I have removed double lines.
Now I share them out, and could you please check if there is something wrong with the inner algorithm of the library?

[error1.pdf](https://github.com/UglyToad/PdfPig/files/5093578/error1.pdf)
[error2.pdf](https://github.com/UglyToad/PdfPig/files/5093582/error2.pdf)
[error3.pdf](https://github.com/UglyToad/PdfPig/files/5093583/error3.pdf)

Thanks and Best Regards!

The code to extract lines is as follows:

    public class TableParms
    {
        public double Top = 0;
        public double Bottom;
        public double Left;
        public double Right = 0;
    }

        public static Tuple<List<double>, List<double>> ExtractTableByLines(Page page, TableParms parms)
        {
            bool IsHorizontal(PdfSubpath.Line l) => Math.Abs(l.From.Y - l.To.Y) < double.Epsilon;
            bool IsVertical(PdfSubpath.Line l) => Math.Abs(l.From.X - l.To.X) < double.Epsilon;
            bool IsInRange(double x) => parms.Left <= x && x <= parms.Right && parms.Bottom <= x && x <= parms.Top;

            if (parms.Right == 0)
                parms.Right = page.Width;
            if (parms.Top == 0)
                parms.Top = page.Height;
            List<Word> words = page.GetWords(wordExtractor).ToList();

            var usefulLines = page.ExperimentalAccess.Paths
                                .SelectMany(x => x.SelectMany(y => y.Commands))
                                .OfType<PdfSubpath.Line>()
                                .Where(x => x.Length >= 1);
            if (parms.Left != 0 || parms.Bottom != 0 || parms.Right != page.Width || parms.Top != page.Height)
                usefulLines = usefulLines.Where(x => IsInRange(x.From.X) && IsInRange(x.From.Y)
                         && IsInRange(x.To.X) && IsInRange(x.To.Y));
            usefulLines = usefulLines.ToArray();

            var verticalList = usefulLines.Where(IsVertical).GroupBy(x => (int)x.From.X).ToList();
            if (verticalList.Count == 0) return null;

            var verticalGroups = verticalList.OrderBy(y => y.Key).ToDictionary(x => x.Key, x => x.ToList());

            double maxTop = verticalGroups.Max(g => g.Value.Max(v => Math.Max(v.From.Y, v.To.Y)));
            double minBottom = verticalGroups.Min(g => g.Value.Min(v => Math.Min(v.From.Y, v.To.Y)));

            var horizontalGroups = usefulLines.Where(IsHorizontal).Where(l => minBottom <= l.From.Y && l.From.Y <= maxTop)
                .GroupBy(x => (int)x.From.Y).OrderByDescending(y => y.Key)
                .ToDictionary(x => x.Key, x => x.ToList());
            if (horizontalGroups.Count == 0) return null;

            List<double> horizontalLines = horizontalGroups.Keys.Select(k => horizontalGroups[k].First().From.Y).ToList();
            // Merge lines that have almost no space to place anything between them.
            for (int i = horizontalLines.Count - 1; i > 0; --i)
            {
                double y1 = horizontalLines[i];
                double y2 = horizontalLines[i - 1];
                if (y2 - y1 < 2)
                {
                    if (horizontalGroups[(int)y1].Count > horizontalGroups[(int)y2].Count)
                    {
                        horizontalLines[i - 1] = y1;
                    }
                    horizontalLines.RemoveAt(i);
                }
            }

            List<double> verticalLines = verticalGroups.Keys.Select(k => verticalGroups[k].First().From.X).ToList();
            // Merge lines that have almost no space to place anything between them.
            for (int i = verticalLines.Count - 1; i > 0; --i)
            {
                double x2 = verticalLines[i];
                double x1 = verticalLines[i - 1];
                if (x2 - x1 < 2)
                {
                    if (verticalGroups[(int)x2].Count > verticalGroups[(int)x1].Count)
                    {
                        verticalLines[i - 1] = x2;
                    }
                    verticalLines.RemoveAt(i);
                }
            }

            var result = new Tuple<List<double>, List<double>>(horizontalLines, verticalLines);
            return result;
    }

**Comment by BobLd** [comment]
Hi @AlexanderLeung9 , maybe take a look at this port of the `tabula` library [here](https://github.com/BobLd/tabula-sharp). It might help you extract the table and does some processing of the `PdfPath` on the page.

**Comment by BobLd** [comment]
below are the result I get with tabula-sharp:

error1.pdf
![image](https://user-images.githubusercontent.com/38405645/93628523-9a991100-f9de-11ea-9294-3d46897dc0a7.png)

error2.pdf
![image](https://user-images.githubusercontent.com/38405645/93628588-b13f6800-f9de-11ea-96e6-6f733e6d4500.png)

error3.pdf
![image](https://user-images.githubusercontent.com/38405645/93628633-c2887480-f9de-11ea-934a-36dc10f71fcd.png)

No nuget package for the moment, I'll try to do one soon.
Use it like this:
```csharp
using Tabula.Extractors;
using UglyToad.PdfPig;

[...]

using (PdfDocument document = PdfDocument.Open("error1.pdf", new ParsingOptions() { ClipPaths = true }))
{
	// extraction
	ObjectExtractor oe = new ObjectExtractor(document);
	PageArea page = oe.Extract(1);

	IExtractionAlgorithm ea = new SpreadsheetExtractionAlgorithm();
	List<Table> tables = ea.Extract(page);
	var table = tables[0]; // or 1
	var rows = table.Rows;
	
	// display
	int[] maxCharCount = new int[table.ColumnCount];
	foreach (var r in rows)
	{
		for (int col = 0; col < table.ColumnCount; col++)
		{
			var c = r[col];
			maxCharCount[col] = Math.Max(maxCharCount[col], c.GetText(false).Length);
		}
		Console.WriteLine();
	}

	foreach (var r in rows)
	{
		for (int col = 0; col < table.ColumnCount; col++)
		{
			var c = r[col];
			Console.Write(c.GetText(false));
			for (int s = c.GetText(false).Length; s < maxCharCount[col]; s++)
			{
				Console.Write(" ");
			}
			Console.Write("|");
		}
		Console.WriteLine();
	}
}
```

**Comment by BobLd** [comment]
Closing the issue - Use the .Net ports of [Tabula](https://github.com/BobLd/tabula-sharp) or [Camelot](https://github.com/BobLd/camelot-sharp) to extract pdf table data.

Feel free to reopen it if need be
