### ISSUE TITLE
Qestion/Feature/Bug: Metadata encoding (Utf-8)

### ISSUE THREAD

**Issue by kalatchev** [UglyToad/PdfPig#203]
AFAIK, Pdf supports unicode string in metadata (Author, Title, Subject, etc). When I try to put Cyrillic string there, I get ? (question marks). Here is my code:
```c#
var builder = new PdfDocumentBuilder
            {
                ArchiveStandard = PdfAStandard.A2A, 
                DocumentInformation = { 
                    Author = "SKYWARE Group", 
                    Title = "Листа с етикети за проби",
                    Subject = "Профилактика: Захарни заводи ЕАД",
                    Creator = "iLabProhy 5.0.0",
                    Keywords = "barcode,labels,samples"
                }, 
                IncludeDocumentInformation = true
            };
```
Note the lines such `Title = "Листа с етикети за проби"`. 
And here is what I get:

<img src="https://user-images.githubusercontent.com/10154711/90981235-7aee0480-e568-11ea-9396-cee5c2bdd5cb.png" width="500px">

Is it possible to use non-latin strings in metadata and if yes - how can I do it?

**Comment by EliotJones** [comment]
Hi @kalatchev yes you're right, PDF supports these strings to be either UTF-16 BE or LE. I don't think writing those values is currently implemented in PdfPig so I'll take a look.

**Comment by kalatchev** [comment]
Thank you, @EliotJones . Hope to see it in next release :-)

**Comment by EliotJones** [comment]
@kalatchev this is now available in this pre-release NuGet, let me know if it works ok https://www.nuget.org/packages/PdfPig/0.1.3-alpha001

**Comment by kalatchev** [comment]
Thanks, @EliotJones :-)

**Comment by EliotJones** [comment]
Thanks for confirming, I'll close this now :)
