### ISSUE TITLE
Getting lines from page

### ISSUE THREAD

**Issue by Luk164** [UglyToad/PdfPig#209]
Getting text from page does not preserve newline characters and results in a mess of text to work with. Would it be possible to get text in an array of lines, similar to when you use a select all and copy function on a document and then separate it by newline?

**Comment by BobLd** [comment]
To help you best, can you tell us what method have you used to extract the text and do you have and pdf document you could share?

Also, try using the following:
```csharp
var words = NearestNeighbourWordExtractor.Instance.GetWords(page.Letters);
var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(words);
```
Each block will contain the arrays of lines you are looking for, and `blocks.Text` should have these lines separated by a newline.

**Comment by Luk164** [comment]
@BobLd I used the simple page.Text accessor. I am sorry but I cannot give an example of the pdf, I do not have any dummy ones and real ones contain sensitive information.

**Comment by BobLd** [comment]
no problem, have you tried my solution?

**Comment by Luk164** [comment]
@BobLd Yes, it did help a little but now there is a bit more lines then there should be. Ideally it should look like this:

`0 ** MEDZISÚČET ZA TRIEDU 988.885,08 107.823,61 102.360,12 26.656,43 4.265,71 994.348,57`

but it looks like this:

`0 ** MEDZISUCET ZA TRIEDU
112 Materiál na sklade
988.885,08
107.823,61
102.360,12
26.656,43
4.265,71
994.348,57`

The PDF contains a table, and it seems that is throwing it off a bit. It is taking values from other rows and mixing them in.

**Comment by Luk164** [comment]
I will create a redacted pdf to show you

**Comment by Luk164** [comment]
Found an image of something simmilar
![image](https://user-images.githubusercontent.com/30559213/92383278-566c5d80-f10e-11ea-98bf-f144ad229e3a.png)

**Comment by Luk164** [comment]
I need to extract the lines with sums

**Comment by Luk164** [comment]
Here is the redacted file
[hk.pdf](https://github.com/UglyToad/PdfPig/files/5182984/hk.pdf)

**Comment by BobLd** [comment]
So basicaly you're trying to extract some text from a table.

Unfortunatly, there is no easy way to do that in pdf documents, and it really depends on the kind of table you are looking at. 
I did some comments on this topics [here](https://github.com/UglyToad/PdfPig/issues/152#issuecomment-598884893). [here](https://github.com/UglyToad/PdfPig/issues/194) and [here](https://github.com/UglyToad/PdfPig/issues/188). Feel free to have a look.

**Comment by Luk164** [comment]
Thanks. BTW the best results I got was literally opening the file in chrome, CTRL+A, CTRL+C and then paste as text - all lines were preserved as they should be. Any Idea if something simmilar can be done with PdfPig?

**Comment by Luk164** [comment]
@BobLd I have found this repo https://github.com/tabulapdf/tabula-java and it gives some pretty good results, now I just need to find some way to make an interop with C#

**Comment by BobLd** [comment]
Interesting, maybe try the `DefaultWordExtractor` to extract words and the following other `IPageSegmenter`:
```csharp
var blocks = DefaultPageSegmenter.Instance.GetBlocks(words);
// or 
var blocks = RecursiveXYCut.Instance.GetBlocks(words);
```

**Comment by EliotJones** [comment]
@Luk164 like BobLd says PDF doesn't readily support text extraction from tables, because it's more like a picture of a text document than a document which preserves structure.

If you wanted to try the text extraction Chrome is based on you might get the output you need from https://github.com/gowengit/docnet which wraps Pdfium for .NET. I'm not sure if Chrome has additional heuristics on top of the Pdfium output but it's worth a try.

PdfPig is more based on providing as much information in the API and as many tools as possible so people can build text extraction for their use case, we have some defaults and algorithms but not currently something like PdfTextStripper in PDFBox or Chrome that tries to get the correct text in all cases (since it's such a difficult thing to generalise).

If all your tables are similar to the one in the linked image something along the lines of:

```
var wordsList = page.GetWords()
                                        .OrderBy(x => x.Bounds.Bottom).ThenBy(x => x.Bounds.Left)
                                        .GroupBy(x => x.Bounds.Bottom)
                                        .ToList();
```

Should get you more or less the words grouped into lines.

**Comment by Luk164** [comment]
@EliotJones I was thinking about the ikvm, but I need it to run on Linux, so that is probably a no-go. I am not skilled enough to port it but maybe some interop would be possible. Anyway, thx for the suggestions!

**Comment by Luk164** [comment]
@EliotJones Thank you once again for your suggestion, the DocNet is performing wonderfully! the results should be good enough for reliable extraction of data via regex,

**Comment by BobLd** [comment]
Hi @Luk164 , I've started porting Tabula to PdfPig [here](https://github.com/BobLd/tabula-sharp/tree/v0.5). Maybe give it a try with the v0.5 branch. No nuget package for the moment, any feedback welcome.

**Comment by Luk164** [comment]
@BobLd I will check it out when I have some time. The DocNet is performing well enough RN, because I am getting the data out using regex anyway, but later it might become useful to get tables out as well.

**Comment by EliotJones** [comment]
Closing this now since hopefully DocNet is working for your purposes and Tabula is now available to install: https://www.nuget.org/packages/Tabula/
