### ISSUE TITLE
Decoder for DCTFilter & CCITTFax

### ISSUE THREAD

**Issue by attarchi** [UglyToad/PdfPig#214]
Hi guys 
@EliotJones 
There are two very useful applicable filter decoder in Java, which haven't been developed in C#. 
Most existed images in PDF files are with filter [DCT ](https://github.com/apache/pdfbox/blob/61ceca8376f08f23f62178bd4fd97e919a690e43/pdfbox/src/main/java/org/apache/pdfbox/filter/DCTFilter.java)and [CCITFax](https://github.com/apache/pdfbox/blob/61ceca8376f08f23f62178bd4fd97e919a690e43/pdfbox/src/main/java/org/apache/pdfbox/filter/CCITTFaxDecoderStream.java). 

anybody can help me in translating them into C#? 
thanks,

**Comment by EliotJones** [comment]
Hi, in the case of theDCT filter the data is encoded as a JPG file, as far as I know. So you should be able to use an image library, such as System.Drawing.Core or ImageSharp, to work with the raw data.
In the version of PDFBox I ported from CCITFax wasn't yet implemented. It looks like it can now be implemented using the link you provided. I'll flag this as a new feature issue. I'm not currently able to work on PdfPig for a while but will try to address it when I get back.
