### ISSUE TITLE
Wrong letter bounding boxes with this document

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#217]
Some (not all) letter bounding boxes are wrong with [this document](https://github.com/UglyToad/PdfPig/files/5233289/data.pdf):
**EDIT**: the problematic font is CMR10 (embeded). After investigation it seems that the original letter bounding box is wrong:
https://github.com/UglyToad/PdfPig/blob/e41ae7d3a243c41fdaafb580710e6809081813d5/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs#L292

this goes through here:
https://github.com/UglyToad/PdfPig/blob/e41ae7d3a243c41fdaafb580710e6809081813d5/src/UglyToad.PdfPig/PdfFonts/Simple/Type1FontSimple.cs#L171
and finaly here:
https://github.com/UglyToad/PdfPig/blob/e41ae7d3a243c41fdaafb580710e6809081813d5/src/UglyToad.PdfPig.Fonts/Type1/CharStrings/Type1CharStrings.cs#L27

My guess is that something goes wrong when running the commands to build the glyph's `PdfSubpath`. A know issue is that the glyph should be generated as a `PdfPath` and not a `PdfSubpath` but nothing changes in this problem when the correction is done.

Any help welcome!

- Page 1:
![image](https://user-images.githubusercontent.com/38405645/93361629-f9268980-f83c-11ea-9250-50933031f3f9.png)
- Page 3:
![image](https://user-images.githubusercontent.com/38405645/93361968-5a4e5d00-f83d-11ea-9226-4a20ae6888df.png)

**Comment by EliotJones** [comment]
So it looks like something goes wrong during interpreting a Type 1 Char String where the commands contain many other subroutines. For the letter `m` in `mpg` from page 1 the following SVG path is generated:
![image](https://user-images.githubusercontent.com/7862346/100555205-3dd49500-3270-11eb-8603-e51bda331e04.png)

From the following CharString sequence:

```
{32, 833, hsbw, 75, 4, callsubr, 78, 344, rmoveto, -268,
 vlineto, -45, -11, 0, -67, vhcurveto, -31, vlineto, 1, 
 callsubr, 113, 0, rmoveto, 2, callsubr, -78, 1, rmoveto, 
 2, callsubr, 51, 2, rmoveto, 2, 
 callsubr, 27, 0, rmoveto, 2, callsubr, 26, 0, rmoveto, 
 2, callsubr, 52, -2, rmoveto, 2, callsubr, 34, -1, rmoveto, 
 2, callsubr, 50, 257, 0, 0, callsubr, 31, vlineto, -67, -11, 0, 45, 
 hvcurveto, 184, vlineto, 104, 71, 56, 64, vhcurveto, 63, 11, -54, -57, 
 hvcurveto, -233, vlineto, -45, -11, 0, -67, vhcurveto, -31, vlineto,
 1, callsubr, 113, 0, rmoveto, 2, callsubr, -78, 1, rmoveto, 2,
 callsubr, 51, 2, rmoveto, 2, callsubr, 27, 0, rmoveto, 2,
 callsubr, 26, 0, rmoveto, 2, callsubr, 52, -2, rmoveto, 2,
 callsubr, 34, -1, rmoveto, 2, callsubr, 50, 535, 0, 0, 
 callsubr, 31, vlineto, -67, -11, 0, 45, hvcurveto, 184,
 vlineto, 104, 71, 56, 64, vhcurveto, 63, 11, -54, -57, 
 hvcurveto, -233, vlineto, -45, -11, 0, -67, vhcurveto, -31,
 vlineto, 1, callsubr, 113, 0, rmoveto, 2, callsubr, -78, 1,
 rmoveto, 2, callsubr, 51, 2, rmoveto, 2, callsubr, 27, 0, 
 rmoveto, 2, callsubr, 26, 0, rmoveto, 2, callsubr, 52, -2, 
 rmoveto, 2, callsubr, 34, -1, rmoveto, 2, callsubr, 50, 813, 0, 0, 
 callsubr, 31, vlineto, -52, 0, -25, 0, -1, 30, rrcurveto, 191,
 vlineto, 0, 86, 0, 31, -31, 36, rrcurveto, -14, 17, -33, 20, -58, 0, 
 rrcurveto, -84, 0, -44, -60, -17, -38, rrcurveto, 
 -14, 87, -74, 11, -45, 0, rrcurveto, -73, 0, -47, -43, -28, -62, 
 rrcurveto, 76, 4, callsubr, 100, callsubr, 75, 4, 
 callsubr, 70, 8, -7, -49, hvcurveto, closepath, endchar}
```

I think it's likely that something goes wrong when flexing commands should be interpreted and are instead being treated as part of the path. But these CharStrings are one of my least favorite things ever to debug so I'm going to leave it for a bit longer because it's such a nightmare.

**Comment by BobLd** [comment]
Hi @EliotJones, thanks for looking at it. I didn't think about drawing the letter as svg. Will give it a 2nd look tomorrow
