### ISSUE TITLE
UnsupervisedReadingOrderDetector Order Row Wise

### ISSUE THREAD

**Issue by ColdFire169** [UglyToad/PdfPig#221]
From what I read in the documentation and source code the UnsupervisedReadingOrderDetector defaults to ordering in a column wise fashion, however I would like to have the ordering row wise. I see that the GetBeforeInReadingRendering method calls the GetBeforeInReadingVertical method and there is also a GetBeforeInReadingHorizontal method, but there is no way to change which method is used apart from editing the source code to switch them. Is there a way to order row wise?

**Comment by BobLd** [comment]
Hi @ColdFire169, I guess the solution is to make the function more customable.  I'll have a look today.

**Comment by BobLd** [comment]
Hi @ColdFire169 , can you have a look [here](https://github.com/BobLd/PdfPig/blob/read-order-improv/src/UglyToad.PdfPig.DocumentLayoutAnalysis/ReadingOrderDetector/UnsupervisedReadingOrderDetector.cs)? 
This improves `UnsupervisedReadingOrderDetector` customisation:
- allows changing the spatial reasoning rule in use
- and using or not rendering order.

If this is good for you, I'll push my PR. Any feedback welcomed

**Comment by ColdFire169** [comment]
Hi @BobLd , that looks good to me.
I appreciate the help and your time.
Thanks.
