### ISSUE TITLE
Ability to convert PDF pages to images

### ISSUE THREAD

**Issue by hnaili** [UglyToad/PdfPig#223]
Hi,

Is there the possiblity to convert pages to images? If not, is it something you are aiming to implement?

Regards

**Comment by EliotJones** [comment]
Hi @hnaili,

Unfortunately this is not currently possible with PdfPig. It's something we'd like to support in future but we don't have development capacity for it at the moment.

In the meantime I'd suggest the following open source C# library for this functionality:  https://github.com/GowenGit/docnet/blob/master/examples/nuget-usage/NugetUsageAnyCpu/PdfToImageExamples.cs. 

I think there may be other C# libraries that support PDF to image too. We hope to add this functionality soon but I don't have any time to work on the project lately.

**Comment by PmE8HW0KRfqa** [comment]
[ImageMagick](https://github.com/ImageMagick/ImageMagick) is great for this sort of thing.

**Comment by BobLd** [comment]
Closing issue, see #280
