### ISSUE TITLE
Getting text using fonts that benefit from Encoding: /Identity-H

### ISSUE THREAD

**Issue by MartaTaszmowicz** [UglyToad/PdfPig#230]
Hi, I found a problem when trying to read the text using 'page.GetWords()'. I want to get a text that uses a font from '/Encoding: /Identity-H'. 
The text object is decoded to Ascia, but there is no cmap table.
How to add CMap for such a font ? 
Is it possible to read such an object in its original form (<005800...>) ?
I add a screenshot maybe it will say more.
![pdfpig](https://user-images.githubusercontent.com/63923908/97776997-28832280-1b6d-11eb-8fa8-adaadfd92d44.png)

Marta

**Comment by InusualZ** [comment]
Sorry for the late response, the head (@EliotJones) of this project is dealing with some personal stuff and he is the most qualified person to answer/resolve this issue. 

Can you provide the pdf that contain the issue or atleast a test pdf?

**Comment by MartaTaszmowicz** [comment]
I attach the file. The problem is the lack of 'ToUnicode' table. 
How can I add this array? Using pdfPig ? I also attach files with arrays for F0 and F1 fonts.
[ToUnicode.txt](https://github.com/UglyToad/PdfPig/files/5518006/ToUnicode.txt)
[testPDF-toUnicode.pdf](https://github.com/UglyToad/PdfPig/files/5518010/testPDF-toUnicode.pdf)

**Comment by EliotJones** [comment]
Hi @MartaTaszmowicz, unfortunately PdfPig doesn't currently support editing existing documents so it's not possible to include the provided CMap in the document using PdfPig. Without the CMap PdfPig defaults to converting the value directly to a UTF16 character based on the value of the bytes, which matches the behaviour if you open the same document in Chrome and copy the text, and the behaviour of PDFBox (Adobe Reader treats them as unrecognized characters).

If you have the original CMaps I guess you could hardcode a conversion from the raw byte values, e.g. `52 == '4'` from the characters in the output of `page.Text` to the actual character value, but I doubt that approach would scale.

**Comment by MartaTaszmowicz** [comment]
Thank you very much for your answer. Each answer allows me to think about my problem differently. I have to think about how to solve my problem, I think I will download the code sources and look deeper.
