### ISSUE TITLE
Help to extract in specified square

### ISSUE THREAD

**Issue by basven1997** [UglyToad/PdfPig#232]
I want to extract text only in a specifick square in the pdf every second page. 
Is that possible?

**Comment by EliotJones** [comment]
Please find an example below:

```
using (var document = PdfDocument.Open(file))
{
    for (var i = 1; i <= document.NumberOfPages; i+=2)
    {
        // For PDF coordinates the y-axis runs from the bottom of the page up
        var bottomLeft = new PdfPoint(20, 100);
        var topRight = new PdfPoint(500, 700);
        var square = new PdfRectangle(bottomLeft, topRight);

        var page = document.GetPage(i);

        var letters = page.Letters.Where(x => square.IntersectsWith(x.GlyphRectangle)).ToList();

        var wordsInRegion = DefaultWordExtractor.Instance.GetWords(letters);
        var textInRegion = string.Join(" ", wordsInRegion.Select(x => x.Text).ToList());
    }
}
```

This will extract all letters from a square [(20, 100), (500, 700)] on every other page starting at page 1. It then uses the default word extractor to get the text but when you have the letters you can construct the text in many other ways, for example `NearestNeighbourWordExtractor`.

**Comment by basven1997** [comment]
Hi @EliotJones thank you very much. Maybe a stupid question..
But my words are vertical instead of horizontal. 

What is the best approach to solve this problem?

![afbeelding](https://user-images.githubusercontent.com/66322541/100254453-9fc88e00-2f42-11eb-9e09-f08c47011266.png)

**Comment by BobLd** [comment]
If you can't have the correct vertical words, maybe give it a try with the the `NearestNeighbourWordExtractor` like this:
```csharp
using (var document = PdfDocument.Open(@"document.pdf"))
{
	for (var i = 0; i < document.NumberOfPages; i++)
	{
		var page = document.GetPage(i + 1);

		var words = page.GetWords(NearestNeighbourWordExtractor.Instance);

		foreach (var word in words)
		{
			// Do something
		}
	}
}
```

**Comment by ZukkyBaig** [comment]
Is there a tool like adobe acrobat or something, that I can create a square with the selector tool and then use the x,y co-ordinates from that into the "new PdfPoint(int x, int y)"? Right now, it seems like a guessing game to get the right square where I want it. There must be a tool to do this quicker.

**Comment by BobLd** [comment]
@ZukkyBaig, maybe have look at this tool [here](https://github.com/BobLd/DocumentLayoutAnalysis/tree/master/DocumentLayoutAnalysis/DlaViewer) that I developped. It's far from perfect but should help you

**Comment by plaisted** [comment]
@BobLd I started playing around with DlaViewer, very cool, thanks for putting it together.

**Comment by BobLd** [comment]
Closed as answered - feel free to reopen if need be
