### ISSUE TITLE
"Brute Force - Infinite loop" Exception from valid PDF

### ISSUE THREAD

**Issue by FAC-jAH** [UglyToad/PdfPig#233]
By "valid" I mean the file opens without problem in Adobe Reader, Firefox, Edge.
Developing in C# .Net Framework 4.5.2   (Visual Studio 2015)

Working on a library to enforce certain document standards for submissions to a web site.    This is one of several documents previously submitted to the system that I cannot read to evaluate.

[ExPig-13441320191_pdf.txt](https://github.com/UglyToad/PdfPig/files/5562756/ExPig-13441320191_pdf.txt)
[13441320191.pdf](https://github.com/UglyToad/PdfPig/files/5562757/13441320191.pdf)

**Comment by FAC-jAH** [comment]
These four exceptions I just entered show up more than once in my test set,  but that is still less than a dozen documents in a random sample of over 3000 documents.   The rest work great.     Even if the problem isn't fixable, a better understanding of what the problem is might let us advise end users how to provide us with a readable file.

**Comment by EliotJones** [comment]
Hi @FAC-jAH thanks for the detailed bug reports and for providing the files. I have fixed all 4 issues (this and #234 #235 #236). I'll try and make a release containing these changes at the weekend.

**Comment by EliotJones** [comment]
@FAC-jAH these fixes should now be available in the published 0.1.4 release https://www.nuget.org/packages/PdfPig/0.1.4. Please give it a go and let me know if it works, thanks.

**Comment by FAC-jAH** [comment]
I'm no longer seeing this error in my test set, thank you.
