### ISSUE TITLE
How to select a specific section using PdfPig?

### ISSUE THREAD

**Issue by ZukkyBaig** [UglyToad/PdfPig#242]
Hi,

I'm new to this library and have just began testing it out. I am creating a test framework to extract text from a pdf document and assert against expected text. I have been able to successfully extract text and assert, however, I wanted it to be more specific and select a section in the pdf to get the text out of. I am have perused the documentation in the readme.md, but it's not entirely clear, and I was wondering if anyone here could help. 

What is the best method to extract text from a fixed section of a PDF document? Using fixed points (how is this achieved with this library) or even highlighting a section on the PDF, which PdfPig could find and extract from?

Thanks in advance.

**Comment by InusualZ** [comment]
See #148, I would come up with an example and put it in the read me. That way it's more clear.

**Comment by ZukkyBaig** [comment]
It stated to create a PdfRectangle, it seems cumbersome to figure out what the exact co-ordinates are? Do you know of a tool which can give me the exact co-ordinates of a highlighted section? I'm using adobe acrobat, with the x,y co-ordinates on display. But the way it is set out, you have to hover the mouse on a specific point and then feed that into PdfRectange(double x1, double y1 ~). 

There must be a tool that you can just select a rectangle and it shows the co-ordinates, which I could easily port over to the codebase.

**Comment by BobLd** [comment]
same as #232

**Comment by ZukkyBaig** [comment]
Thank you, i'm trying it out now.

**Comment by ZukkyBaig** [comment]
What a brilliant application you've developed. You should advertise this DlaViewer more, really helpful. Thank you BobLd.

**Comment by BobLd** [comment]
@EliotJones, maybe we could add a link to DlaViewer in the readme?

**Comment by BobLd** [comment]
Closed as answered - feel free to reopen if need be
