### ISSUE TITLE
Pdf splitter

### ISSUE THREAD

**Issue by Poltuu** [UglyToad/PdfPig#244]
Hi,

I'm contemplating developping a basic pdf splitter functionality based on this library.
I was wondering if you believe it sounds manageable with the current apis (public or internal), and/or if you'd be interested to add this to the library.

At first glance, it seems to me like it's a matter of `PdfPageBuilder` meet `PageContent`, but of course, nothing is that easy with pdfs.

**Comment by InusualZ** [comment]
I have submitted a [PR](https://github.com/UglyToad/PdfPig/pull/245) that would allow to specify a page selection to merge. That would kind of solve this issue. 

Also, your approach is related to #27

**Comment by Poltuu** [comment]
That would indeed :)
If this is accepted, we probably should have a PdfSplitter class using this code, as 
`PdfMerger.Merge(file, null, pages)` does not sounds like pdfsplitting to me

**Comment by InusualZ** [comment]
That can be discussed with @EliotJones. But I think a better approach would be to have a couple of good example.
