### ISSUE TITLE
I can't read the text for KSCms-UHC-H encoding.

### ISSUE THREAD

**Issue by honeyhead** [UglyToad/PdfPig#247]
![image](https://user-images.githubusercontent.com/3714819/101868466-c2081000-3bc0-11eb-94da-dc6aa437a497.png)

I have a question.

I added the text to the PDF using Foxit PDF.

I could read a typical pdf book using pdfpig, but I couldn't read the text in this case.

That font is installed in Windows by default.

I thought it was a problem with CMap, but because it's stored in the CmapParser assembly, I don't think there's a problem finding the cmap. "UglyToad.PdfPig.Resources.CMap.KSCms-UHC-H"

![image](https://user-images.githubusercontent.com/3714819/101868932-b406bf00-3bc1-11eb-9a85-b26a5fbf0a6c.png)

And I did another test because I thought there was a problem with Korean.

I entered "TEST" in English and read it again, but the result was a completely different value.

I think it's hard to figure out whether the TEXT made using the system font is encoded that way or if it's not handling "Adobe-Korea1" Cmap well at the time of PDF generation.

That's why you can't read the text. Of course, modifying PDFs will solve it easily, but I can't tell people who will use my program to always use fonts like Arial.

**Comment by honeyhead** [comment]
[https://www.dropbox.com/s/8wt815k5qqvfbd9/demo.pdf?dl=0](url)

this is sample pdf.

**Comment by honeyhead** [comment]
I think I've found a way. Of course, it's only close, but not the solution.

Type0FontHanlder.cs code contains the following.

var UnicodeCMapName = $"{nonUnicodeCMap.Info.Registry}-{nonUnicodeCMap.Info.Order}-UCS2";

The code indicates that "Adobe-Korea1-UCS2" is to be imported as a result, but the matching value does not seem to match the Korean language.

For that reason, I downloaded the Korean pack to xpdf and added the file "Adobe-Korea1.cidToUnicode" to CMAP in the pdfpig folder, and changed it to the "Adobe-Korea1-UCS2" state value manually when the variable unicodeCMapName obtained the value "Adobe-Korea1cidTonic2".

![image](https://user-images.githubusercontent.com/3714819/101875597-39906c00-3bce-11eb-9342-1197d2db5515.png)

The result comes normally, but it may be because the font name is in Korean, but it is written as "?????"
If you have a problem with CJK (Korean, Chinese, Japanese) please try this method.

**Comment by honeyhead** [comment]
![image](https://user-images.githubusercontent.com/3714819/102036517-6333d800-3e06-11eb-9be4-6d501f53663a.png)


In my opinion, when you import system fonts, you import letters into the language of the country according to the language of the OS.

I'm using the Korean operating system.
The font name was imported as "맑은고딕" instead of "Malgun Gothic".

In that case, the question mark will be marked, so if it is included in the content, you can change it to the font that matches it.

UTF-8 is not able to speak Korean normally.
Perhaps this content is related to Chinese and Japanese.

It has not been resolved whether to change to the font installed in Windows or apply en-US to import the system font.

**Comment by honeyhead** [comment]
Oh, sorry. It's in **_NameTokenizer.cs._**
I hope it helps someone.

**Comment by honeyhead** [comment]
![image](https://user-images.githubusercontent.com/3714819/102036806-274d4280-3e07-11eb-8887-d33fb043e6c0.png)

^__^

**Comment by EliotJones** [comment]
Sorry, not going to have time to look into this, maybe try https://github.com/gowengit/docnet since hopefully Google has better support for CJK fonts
