### ISSUE TITLE
InvalidOperationException : Codespace range contains an unexpected token

### ISSUE THREAD

**Issue by yvainb** [UglyToad/PdfPig#256]
Hi,

Would you tell me why an exception is thrown on the GetWords() of this page [pdfpig_error_CodespaceRangeParser_page.pdf](https://github.com/UglyToad/PdfPig/files/5782438/pdfpig_error_CodespaceRangeParser_page.pdf)

Have a good day.

**Comment by InusualZ** [comment]
I would take a look at the error. Thanks for reporting the bug
