### ISSUE TITLE
Why is the Height of PdfRectangle is negative when Top is greater than Bottom?

### ISSUE THREAD

**Issue by AlexanderLeung9** [UglyToad/PdfPig#261]
PdfRectangle rectangle = new PdfRectangle(left, bottom, top, right);
where 
		left	401.51	double
		bottom	291.45	double
		top	300.17322363281249	double
		right	461.803424	double
result to Height: -170.353424
![rectangle](https://user-images.githubusercontent.com/52726330/104676134-c1afe700-5721-11eb-95f4-1e16ea85ae9a.png)

I see the definition of PdfRectangle in Version 0.1.4.0 as follows:
        //
        // Summary:
        //     Create a new UglyToad.PdfPig.Core.PdfRectangle.
        //
        // Parameters:
        //   x1:
        //     Bottom left point's x coordinate of the rectangle.
        //
        //   y1:
        //     Bottom left point's y coordinate of the rectangle.
        //
        //   x2:
        //     Top right point's x coordinate of the rectangle.
        //
        //   y2:
        //     Top right point's y coordinate of the rectangle.
        public PdfRectangle(double x1, double y1, double x2, double y2);

Please help to clarify my doubt, thanks in advance!

**Comment by BobLd** [comment]
This is not the expected behaviour (Width and Height should be positive). Fixed in #263
