### ISSUE TITLE
Why does the BoundingBox of a word not serve as a rectangle, instead as a line?

### ISSUE THREAD

**Issue by AlexanderLeung9** [UglyToad/PdfPig#265]
The word is "Billing" with its height being 0. What's wrong with it?

![BoundingBox](https://user-images.githubusercontent.com/52726330/104798896-825ac680-5805-11eb-92f5-892a1a86c0c9.png)
![Billing](https://user-images.githubusercontent.com/52726330/104798890-77a03180-5805-11eb-9d54-55a0b9c23dbe.png)

Thanks and Regards

**Comment by Poltuu** [comment]
Hi, can't be sure without the actual pdf, but this is probably related to the font.
As far as I known, the height of a word is 0 is the height of every letter is 0, which might happend if the font does not provide information regarding the characters height, which is a thing for some type3 font. I have encountered this scenario in my pdf parsing experience, and as far as I know, it is a pdf thing.
To anyone reading this, feel free to correct me if anything I said is wrong, I'm no expert in this thing.

**Comment by BobLd** [comment]
I did a PR about Correct letter bbox for Type1 font/flexpoints in #240. Have a look, might be related
