### ISSUE TITLE
Layers collection

### ISSUE THREAD

**Issue by simonedd** [UglyToad/PdfPig#266]
Hi,

Is it possible to get the Layers collection and know the layer of each object? 
Here a sample file with three layers ( "_0_", "_Dimentions_" and "_Text_" ) : [odwriteex.pdf](https://github.com/UglyToad/PdfPig/files/5828825/odwriteex.pdf)

**Comment by BobLd** [comment]
Hi @simonedd, I've started working on that. You can check the progress in https://github.com/UglyToad/PdfPig/pull/282.

Could you provide other document example so that we cover more functionnalities?

**Comment by simonedd** [comment]
Hi @BobLd,

Thanks for working on that, attached other two documents.

[0E49K15_T.pdf](https://github.com/UglyToad/PdfPig/files/5944682/0E49K15_T.pdf)
[Facade.pdf](https://github.com/UglyToad/PdfPig/files/5944687/Facade.pdf)

**Comment by BobLd** [comment]
These 2 documents are quite similar to your first one in fact, so you could use my PR to start working on it. If you are able, could you create a pdf with XObjects and annotations within layers? this is a missing bit

**Comment by simonedd** [comment]
No sorry, I don't have such documents.

**Comment by BobLd** [comment]
I've updated my PR to access the content with recursion. Maybe start using it and let me know if you have errors - it will be useful to improve it

**Comment by simonedd** [comment]
Looking at the code I see that I can get the "Layers" collection, but I also need to know for each element (Path, Letter, ..) which "layer" it belongs to. The final goal is to show/hide all objects of the same layer, is it possible?

**Comment by BobLd** [comment]
Given what you want to do, it might not be the most convenient way, but here is how you can access each element.
A more efficient wawy would be to have a layer property in each element, which is not the cas eat the moment...

```csharp
using (var document = PdfDocument.Open(IntegrationHelpers.GetDocumentPath("odwriteex.pdf")))
{
	var page = document.GetPage(1);
	var layers = page.ExperimentalAccess.GetOptionalContents();

	foreach (var layer in layers)
	{
		Console.WriteLine(layer.Key);

		foreach (var oc in layer.Value)
		{
			var letters = oc.MarkedContent.Letters;
			var images = oc.MarkedContent.Images;
			var path = oc.MarkedContent.Paths;

			// do something
		}
	}
}
```

**Comment by BobLd** [comment]
Closed as answered - feel free to reopen if need be

**Comment by simonedd** [comment]
Hello,

With the attached file I have an exception on this line:` var layers = page.ExperimentalAccess.GetOptionalContents();`
Is it possible to avoid the exception and just skip the problematic optional content?
[JWO_IS_eksport_pdf_..pdf](https://github.com/user-attachments/files/18359050/JWO_IS_eksport_pdf_.pdf)

Is there any chance to have the Layer property for each element?
