### ISSUE TITLE
Fail to extract image from pdf

### ISSUE THREAD

**Issue by oleksant** [UglyToad/PdfPig#271]
Hi. 

During extraction of images from the pdf files we keep running into failures. 
Up to 30 percent of images fail to extract. 

We have tried TryGetPng, TryGetBytes, and RawBytes for sureб but some of the images could not be extracted anyway. 

To create the PDF file from Word we are using LibreOffice. 

Here is a piece of code that is using RawBytes. It saves the image but the result could not be opened.
 
    using (var document = PdfDocument.Open(FilePath))
            {
                foreach (var page in document.GetPages())
                {
                    foreach (var image in page.GetImages())
                    {
                        var byteArray = image.RawBytes.ToArray();
                        using (var fs = new FileStream(imageFilePath, FileMode.Create, FileAccess.Write))
                        {
                            fs.Write(byteArray, 0, byteArray.Length);
                        }
                    }
                }
            }

Usually, I can check whether the image fails to extract with the following code: 

```
public static bool IsValidImage(byte[] bytes)
{
      try {
            using(MemoryStream ms = new MemoryStream(bytes))
                    Image.FromStream(ms);
            }
            catch (ArgumentException) {
                return false;
            }
            return true; 
}
```

[StuckSamplePdf.pdf](https://github.com/UglyToad/PdfPig/files/5855093/StuckSamplePdf.pdf)
[TextImages.pdf](https://github.com/UglyToad/PdfPig/files/5855596/TextImages.pdf)
[2imagesdoc.pdf](https://github.com/UglyToad/PdfPig/files/5855597/2imagesdoc.pdf)

**Comment by alex19497** [comment]
After some investigation, I can assume that for most images (except for the one in StuckSamplePdf) we are facing the same issue. 
If the ColorSpace is an array - we have an issue. In our case - the name of the first element is "Indexed" and from the PdfBox code, I can see that it requires additional logic, saving other data from the ColorSpace array to be able to decode the image with it.

Here is the data from our ColorSpace: 
![image](https://user-images.githubusercontent.com/44353204/105523327-ed653b00-5ce6-11eb-802c-c8ecca734116.png)

The 3 element is never being used and it is needed to reconstruct the original image.

**Comment by alex19497** [comment]
Hi again. There is no mechanism to process raster images in PdfPig as I can see, so in our case, the workaround that we were able to put in place is the following:

```
 public static class PdbPigImageExtentions
    {
        public static bool TryGetIndexedPng(this XObjectImage image, out byte[] resultImage )
        {
            resultImage = null;
            try
            {
                if (image.TryGetBytes(out var tryBytes))
                {
                    if (image.ColorSpace == UglyToad.PdfPig.Graphics.Colors.ColorSpace.Indexed)
                    {
                        if (image.ImageDictionary.Data.TryGetValue(NameToken.ColorSpace, out var colorSpace))
                        {
                            var colorSpaceArray = (ArrayToken) colorSpace;
                            PDIndexed pdIndexed = new PDIndexed(tryBytes.ToArray(), (ArrayToken) colorSpaceArray);
                            var bitmap = pdIndexed.GetRGBImageBytes(image.HeightInSamples, image.WidthInSamples);
                            resultImage = ImageToByte(bitmap);
                            return true;
                        }
                    }
                }

                return false;
            }
            catch
            {
                return false;
            }
        }
        
        public static byte[] ImageToByte(Image img)
        {
            using (var stream = new MemoryStream())
            {
                img.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
    }
    
    public class PDIndexed
    {
        private byte[] lookupData;
        private byte[] imageData;
        private byte[,] colorTable;


        private ArrayToken colorSpaceArray;

        /// <summary>
        /// s
        /// </summary>
        /// <param name="colorSpaceArray"></param>
        public PDIndexed(byte[] imageData, ArrayToken colorSpaceArray)
        {
            this.colorSpaceArray = colorSpaceArray;
            this.imageData = imageData;
            ReadColorTable();
        }

        private void ReadLookupData()
        {
            if (lookupData == null)
            {
                HexToken lookupTable = (HexToken) colorSpaceArray.Data[3];
                lookupData = lookupTable.Bytes.ToArray();
            }
        }

        private int GetHival()
        {
            return ((NumericToken) (colorSpaceArray.Data[2])).Int;
        }

        private void ReadColorTable()
        {
            ReadLookupData();

            int maxIndex = Math.Min(GetHival(), 255);
            int numComponents = 3;

            if (lookupData.Length / numComponents < maxIndex + 1)
            {
                maxIndex = lookupData.Length / numComponents - 1;
            }

            colorTable = new byte[maxIndex + 1, numComponents];
            for (int i = 0, offset = 0; i <= maxIndex; i++)
            {
                for (int c = 0; c < numComponents; c++)
                {
                    colorTable[i, c] = lookupData[offset];
                    offset++;
                }
            }
        }

        public Bitmap GetRGBImageBytes(int height, int widht)
        {
            Bitmap bitmap = new Bitmap(widht, height);

            var i = 0;
            for (var y = 0; y < height; y++)
            {
                for (var x = 0; x < widht; x++)
                {

                    var pixel = imageData[i++];
                    bitmap.SetPixel(x, y,
                        Color.FromArgb(colorTable[pixel, 0], colorTable[pixel, 1], colorTable[pixel, 2]));
                }
            }
            return bitmap;
        }
    }
```

In your code, you already have some mechanisms to make this much easier. From my point of view, the ColorSpace enum needs to be promoted to class. What do you think?

**Comment by EliotJones** [comment]
Hi there @oleksant I agree that the full details need to be made available to consumers. In order to maintain backwards compatibility the existing color space property for images should be preserved so I added a new `ColorSpaceDetails` property to the `IPdfImage` class as follows.

However when I run the code I'm generating the wrong indexes into the lookup table, maybe you can review it and spot the obvious error https://github.com/UglyToad/PdfPig/compare/support-indexed-color-space?expand=1

**Comment by oleksant** [comment]
Hi @EliotJones! The job you've done looks amazing and will be really useful. Looking into your issue, I can see that the lookup table is correct, however, the UnwrapIndexedColorSpaceBytes has a small bug. The table contains all 255*3 elements and when unwrapping we assume that it is just 255. 

The simple fix will be to multiply the input of the transformer method. 
So it can be done with the following for DeviceRGB (and the same for others)
```
               transformer = x =>
                    {
                        var r = new byte[3];
                        for (var i = 0; i < 3; i++)
                        {
                            r[i] = indexed.ColorTable[x*3+ I]; 
                        }

                        return r;
                    };
                    multiplier = 3;
                    break;
```

Or you can try to simplify the method like this: 
   ```
private static byte[] UnwrapIndexedColorSpaceBytes(IndexedColorSpaceDetails indexed, IReadOnlyList<byte> input)
        {
            int multiplier;
            switch (indexed.BaseColorSpaceDetails.Type)
            {
                case ColorSpace.DeviceRGB:
                    multiplier = 3;
                    break;
                case ColorSpace.DeviceCMYK:
                    multiplier = 4;
                    break;
                case ColorSpace.DeviceGray:
                    multiplier = 1;
                    break;
                default:
                    return input.ToArray();
            }

            var result = new byte[input.Count * multiplier];
            var i = 0;
            foreach (var b in input)
            {
                foreach (var newByte in Transform(indexed, b, multiplier))
                {
                    result[i++] = newByte;
                }
            }

            return result;
        }

        private static byte[] Transform(IndexedColorSpaceDetails indexed, byte colorTableAddress, int multiplier)
        {
            var r = new byte[multiplier];

            for (var i = 0; i < multiplier; i++)
            {
                r[i] = indexed.ColorTable[colorTableAddress * multiplier + i];
            }

            return r;
        }

```

This worked for my cases, but if you have more files to check with, it would be awesome. 
Once again, thanks much, for such a quick response and a great job!!

**Comment by EliotJones** [comment]
Thanks @oleksant the missing multiplier was the issue. I left it as the slightly more complicated `transformer` Func for now because for CIE and Separation/DeviceN based Color Spaces the conversion is more complex so the Func won't be a straight multiplication.

**Comment by oleksant** [comment]
Hello @EliotJones, I did a quick check on my side and it looks like the issue is resolved. Should we close it or do you think there is more testing required to verify? 
 
I really appreciate your work and am thankful for the fix provided. You are doing amazing work!!
