### ISSUE TITLE
Add embedded file to existing PDF

### ISSUE THREAD

**Issue by jerry2007** [UglyToad/PdfPig#273]
Is possible to add file to existing PDF?

My use case is transform existing PDF files to PDF/A-3 and add file

Is it possible?

**Comment by jerry2007** [comment]
@EliotJones 
Hello,
I would like to ask you, what has to be done to support editing PDF and adding in PDFPig?
I would like to contribute to done this features for PDFPig, because I really need some free library for inserting file to PDF and create PDF/A-3...

Can you help me where to start? How can I help you to implement this feature

**Comment by Poltuu** [comment]
I don't want to responde for @EliotJones , but pdf/A is an ISO standard, and I seem to remember that this library does not intend to handle the standard, but only pdf 1.7, mostly since the specification cannot be found for free online.

**Comment by jerry2007** [comment]
@Poltuu  
Really?
I found this file...
https://github.com/UglyToad/PdfPig/blob/d959a30bf0a8a4e9b85d7b2e4f1c97133401657c/src/UglyToad.PdfPig/Writer/PdfAStandard.cs

PDF/A-3 is missing by 2 and 1 is there...

**Comment by EliotJones** [comment]
Hi @jerry2007 unfortunately this is not possible at the moment with this library. 

Currently those PDF/A utilities are for creating new documents where it's easier to enforce PDF/A compliance since the set of objects being written is know.

The discussion for editing features is currently underway in issue #264

**Comment by EliotJones** [comment]
Document loading into PdfDocumentBuilder is now possible
