### ISSUE TITLE
Maintain text lines when reading text?

### ISSUE THREAD

**Issue by MLyons10** [UglyToad/PdfPig#274]
I am new to this sdk and really commend all of the work on this, it's a great utility.

The only issue I'm running into that I can't seem to find a solution to is that I'm trying to pull a value from the pdf file and I'm having some difficulty doing that.

For instance, iText maintains the lines of the pdf report so I can find the line that I want and then pull the data from it.  Is there a way to populate the string by text line with pdfPig?  It looks like it just does this by word or am I missing something?

I appreciate the help!

**Comment by MLyons10** [comment]
I jumped the gun on my post but wanted to post the solution in case anyone else runs into the same thing:

using (var pdf = PdfDocument.Open("PDFFILEPATH))
                {
                    foreach (var page in pdf.GetPages())
                    {
                        var text = ContentOrderTextExtractor.GetText(page);

                        // Or based on grouping letters into words.
                        var otherText = string.Join(" ", page.GetWords());

                        // Or the raw text of the page's content stream.
                        var rawText = page.Text;

                        pdfString += text;
                    }

                }

                PDFRTB.Text = pdfString;
                
               
foreach (string str in PDFRTB.Lines)
                {
                    if (str.Contains("TEXT YOUR LOOKING FOR"))
                    {
                        Line = str;
                    }
                }

**Comment by BobLd** [comment]
Maybe also have a look the [Wiki Document Layout Analysis - Page segmenters](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#page-segmenters)

Page segmenters allow you to extract text lines and text blocks
