### ISSUE TITLE
How can I  render pdf to image?

### ISSUE THREAD

**Issue by xtuzy** [UglyToad/PdfPig#280]
Hello, I want render pdf to image and extract text in Xamain. I search pdfbox，then find this library. I use skiasharp in xamarin，and i find [PdfBox-Android](https://github.com/TomRoush/PdfBox-Android) render pdf use android's canvas, it is  similar to SkCanvas in Skiasharp. I want imitation PdfBox-Android to implement render , but I see PdfPig  is different from PdfBox. How can I implement this feature? Can you give me a guide?

**Comment by BobLd** [comment]
Hi @xtuzy, thanks for your question, this is a feature that would be really useful.

I've started working on it in this PR https://github.com/UglyToad/PdfPig/pull/228 but this is far from being finished. This uses System.Drawing but it should be relatively easy to replace it by Skiasharp.

As this is a feature this requested a lot, happy to help you if you want to work on it

**Comment by perplexityjeff** [comment]
This would make for a very nice feature and make the library that much more useful! Thank you for all the work so far.

**Comment by davebrokit** [comment]
For those that are looking for a solution while this is ongoing:

From the documentation:
> If you need this functionality see if [docnet ](https://github.com/GowenGit/docnet)meets your requirements.

**Comment by BobLd** [comment]
I've created a repo/NuGet package to render pdf documents using PdfPig and SkiaSharp here https://github.com/BobLd/PdfPig.Rendering.Skia
