### ISSUE TITLE
Bullet points separated

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#296]
When running the following code:

```
var words = page.GetWords(NearestNeighbourWordExtractor.Instance).ToList();
var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(words);
var orderedBlocks = new UnsupervisedReadingOrderDetector(spatialReasoningRule: UnsupervisedReadingOrderDetector.SpatialReasoningRules.RowWise, useRenderingOrder: false).Get(blocks).ToList();
var finalBlocks = new List<UglyToad.PdfPig.DocumentLayoutAnalysis.TextBlock>(orderedBlocks);
```
on the file https://drive.google.com/file/d/1fWXuDZpO_iUgwNhqCds60WhaQYFXJkOK/view?usp=sharing

I get the following text:

> This service is free and comes with the following additional benefits:
> 
> ●
> ●
> 
> Payments are received faster than waiting for a cheque to arrive in the mail.
> No more lost/misplaced/fraudulent cheques.
> 

I happens many times that the bullet points are the numbered points are separated from text.

**Comment by EliotJones** [comment]
Layout analysis is an inexact art. You will need to post-process the results to suit your use-cases. There is no 100% for this stuff
