### ISSUE TITLE
Issue with word order

### ISSUE THREAD

**Issue by christopher5106** [UglyToad/PdfPig#297]
https://drive.google.com/file/d/13kw4PxlY3ExM-rWhCqHP2PMwXft7CBXP/view?usp=sharing

I get with the following code:

```
var words = page.GetWords(NearestNeighbourWordExtractor.Instance).ToList();
var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(words);
var orderedBlocks = new UnsupervisedReadingOrderDetector(spatialReasoningRule: UnsupervisedReadingOrderDetector.SpatialReasoningRules.RowWise, useRenderingOrder: false).Get(blocks).ToList();
var finalBlocks = new List<UglyToad.PdfPig.DocumentLayoutAnalysis.TextBlock>(orderedBlocks);
```

the following text in one of the blocks it outputs:

> The terms “including” and “include” shall mean “including and “include without limitation”, respectively. limitation” without Notwithstanding any other provision of this Agreement and, unless otherwise expressly stated herein, all rights and remedies of its Affiliates under this Agreement are in addition 

while the original text is 

> The terms “including” and “include” shall mean “including without limitation” and “include without limitation”, respectively. Notwithstanding any other provision of this Agreement and, unless otherwise expressly stated herein, all rights and remedies of its Affiliates under this Agreement are in addition

**Comment by BobLd** [comment]
Running the [DlaViewer app](https://github.com/BobLd/DocumentLayoutAnalysis/tree/master/DocumentLayoutAnalysis/DlaViewer), this is th result you'd get (TextLines are displayed):
![image](https://user-images.githubusercontent.com/38405645/108776696-a2934900-755a-11eb-8a98-cf282c35fd7d.png)

As you can see, there is a problem with how the lines are build for the part with which you have an issue. This is a known issue for justified text... 

This is kind of an ad-hoc solution, but try having a look at the [wiki](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#docstrum-for-bounding-boxes-method) and play with the docstrum parameters - if I recall correctly, you need to change the `WithinLineMultiplier` property in the docstrum's options and pass them when you run the algo
```csharp
var options = new DocstrumBoundingBoxes.DocstrumBoundingBoxesOptions()
{
      WithinLineMultiplier = 5 // 5 for example, default is 3
};
```

**Comment by BobLd** [comment]
Also, you can use the `RecursiveXYCut` algo, instead of the Docstrum one.
Feel free to reopen the issue if need be
