### ISSUE TITLE
Draw a line on an existing pdf

### ISSUE THREAD

**Issue by ChristianRazvan** [UglyToad/PdfPig#303]
Hello!
 I saw something about the ability to import a pdf page to a document builder so...that means until that part it's implemented you cannot  draw a line on an existing pdf page? 

The mention: Consolidate document / page modification approach #264

Thanks!

**Comment by plaisted** [comment]
The trunk code should have this ability but don't believe it has been released as a nuget. You can import a page to the `PdfDocumentBuilder` (creating a PdfPageBuilder based on the imported page) or `PdfPageBuilder` (adding page to existing). Keep in mind the changes are pretty new and don't have a lot of usage yet.
