### ISSUE TITLE
not able to get words from scanned PDF

### ISSUE THREAD

**Issue by markat1** [UglyToad/PdfPig#309]
Hi,
I'm having an issue reading from scanned pdfs. This library works fine with non scanned pdfs. 

Test code is the following from a .net core console application:

```
using UglyToad.PdfPig;

namespace PdfExtractor
{
    class Program
    {
        static void Main(string[] args)
        {

            // test pdf - https://jeroen.github.io/images/ocrscan.pdf
            using (PdfDocument document = PdfDocument.Open(@"C:\Users\james\Desktop\code\dev\PdfExtractor\PdfExtractor\PdfExtractor\src\ocrscan.pdf"))
            {
                foreach (var page in document.GetPages())
                {
                    foreach (var word in page.GetWords())
                    {
                        Console.WriteLine(word);
                    }
                }
            }
        }
    }
}
```

I got the following error 

```
C:\Users\james\Desktop\code\dev\PdfExtractor\PdfExtractor\PdfExtractor\bin\Debug\netcoreapp3.1\PdfExtractor.exe (process 35324) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by InusualZ** [comment]
The library doesn't contain an OCR (Optical Character Recognition) API, so reading a scanned document is not possible.

**Comment by markat1** [comment]
Any other libraries capable of doing OCR?

**Comment by EliotJones** [comment]
Hi @markat1 I think your best bet is to use Tesseract to generate a searchable PDF output, theres some more details here https://tesseract-ocr.github.io/tessdoc/Command-Line-Usage.html. 

The produced searchable PDF from tesseract should be read by PdfPig normally.

Generally I use docker and some simple wrapper for tesseract to ensure any issues don't break the rest of my processes, for example this image wraps tesseract behind a simple web server: https://github.com/ricktorzynski/ocr-tesseract-docker

**Comment by markat1** [comment]
Thank you so much @EliotJones ! I will look further into it!

**Comment by BobLd** [comment]
Closed - Answered by @EliotJones
