### ISSUE TITLE
incorrect text encoding for string tokens

### ISSUE THREAD

**Issue by schmitch** [UglyToad/PdfPig#313]
currently string tokens sometimes have an incorrect encoding. sadly I can't share documents, but if I call:

```csharp
Console.WriteLine(document.Information.Author);
```

the string that will be printed sometimes start with `0xFE`, `0xFF`. btw. apache-pdfbox does this correctly.
Also I can print the following:

```csharp
if (document.Information.DocumentInformationDictionary.TryGet(NameToken.Author, out var token))
{
    var sToken = (StringToken)token;
    var bytes = sToken.GetBytes();
    Console.WriteLine($"AuthorToken: |{bytes[0] & 0xFF}, {bytes[1] & 0xFF}|");
}
```

which will result in: `AuthorToken: |254, 255|` in case of apache-pdfbox the `getString()` method of these tokens will be like that:

```java
    public String getString()
    {
        // text string - BOM indicates Unicode
        if (bytes.length >= 2)
        {
            if ((bytes[0] & 0xff) == 0xFE && (bytes[1] & 0xff) == 0xFF)
            {
                // UTF-16BE
                return new String(bytes, 2, bytes.length - 2, Charsets.UTF_16BE);
            }
            else if ((bytes[0] & 0xff) == 0xFF && (bytes[1] & 0xff) == 0xFE)
            {
                // UTF-16LE - not in the PDF spec!
                return new String(bytes, 2, bytes.length - 2, Charsets.UTF_16LE);
            }
        }
        // otherwise use PDFDocEncoding
        return PDFDocEncoding.toString(bytes);
    }
```
this method will also be called when calling `document.getDocumentInformation().getAuthor()` since the `getAuthor()` method calls `info.getString( COSName.AUTHOR );` which calls:

```java
    public String getString(COSName key)
    {
        String retval = null;
        COSBase value = getDictionaryObject(key);
        if (value instanceof COSString)
        {
            retval = ((COSString) value).getString();
        }
        return retval;
    }
```

so the `StringToken.Data` of PdfPig will always incorrectly also spit out the BOM.

I have no idea why this is happening, since `StringTokenizer` looks correct?!

**Edit:**
it looks like the pdf is encrypted (`/Encrypt 7 0 R`) and I'm not sure, but it looks like that the `StringTokenizer` works on the unencrypted string. Because if I put a breakpoint onto `token = new StringToken(tokenStr, encodedWith);` `tokenStr` is basically not readable, however that would be incorrect, since it should be decrypted before performing the decoding.

**Edit 2:** 
not all pdf's that are created and have the `/Encrypt` are wrong, only the ones with a BOM, I could not create a broken document with Adobe Pdf Pro, but I found out that `wkhtmltopdf 0.12.5` with Password Encrypted PDFs might create a broken one. nvm wkhtmltopdf does not do that...

**Comment by InusualZ** [comment]
I'm trying to debug your problem. This problem only occur when the PDF is encrypted?

Since the problem at hand is with the document metadata. Couldn't you strip the pages that way you share the document?

**Comment by schmitch** [comment]
> Does the problem only occur when the PDF is encrypted?

well the `/Encrypt` flag is set inside the pdf, but that's more or less just a write protection or digital document signing. (I have no idea how that works)

> Since the problem at hand is with the document metadata. Couldn't you strip the pages that way you could share the document?

unfortunatly not, because once I use adobe pro to remove it (which is funny that I can remove stuff, because of write protection or digital signed) it will save the pdf differently.

and I tried so many tools to create them:
- wkhtmltopdf+qpdf
- adobe pro
- itext
- pdfbox

nothing worked.
Reading the broken ones basically worked with:
- itext 7
- pdfbox

but did not with older versions of itext (couldn't get it to work with itext 4 LGPL) and of course pdfpig.

not **all** pdf's with an `/encrypt` flag have that problem?!

I know a german electronics retailer that has the problem: https://reichelt.de but you need to be described to their email workflow: https://www.reichelt.de/?;ACTION=70;LA=70;PAGE=52

**Comment by InusualZ** [comment]
If a PDF contain the `/Encrypted` entry in the document trailer dictionary it's because the PDF is password protected. From that I can see that [this code](https://github.com/UglyToad/PdfPig/blob/c74ca5fda8a51f3af9cf19c675272f57d3beee60/src/UglyToad.PdfPig/Encryption/EncryptionHandler.cs#L392-L407) is at fault for the _mismanagement_ of the encoding. I have an idea for a patch that could work. But, you would have to test it since I don't have the document.

**Comment by schmitch** [comment]
it would not be a problem to test it, as said I'm still trying to ask the retailer if he can give us an idea how he generates the pdf, but I did not get an answer yet.

**Comment by EliotJones** [comment]
Hi @InusualZ thanks for finding the cause, if I'm understanding correctly the following code should address this? https://github.com/UglyToad/PdfPig/pull/321

**Comment by schmitch** [comment]
@EliotJones @InusualZ thanks!

this is fixed in master!


```
using (PdfDocument document = PdfDocument.Open(@"/Users/schmitch/593640.pdf"))
{
                Console.WriteLine($"Info: {document.Information.Title}");
}
```

Version 0.1.4:
`Info: þÿEingangsbestätigung für (Inet-Nr. I- 593640 )`

master:
`Info: Eingangsbestätigung für (Inet-Nr. I- 593640 )`
