### ISSUE TITLE
PDFpig parser not parsing some pdfs correctly 

### ISSUE THREAD

**Issue by ArkadeepDey71** [UglyToad/PdfPig#319]
Hi,
I am using the below method to read the text from a pdf. The parsing works fine for most of the pdfs. However, for some of the pdf, parser is unable  to identify the space between words. As a result, we are getting a redundant output of large sequence of alphanumeric character without any space.

```
// strfileDir : This is the file Path.
private static string GetTextfromPDF(string strfileDir) {
            try
            {
                using (var document = PdfDocument.Open(strfileDir))
                {
                    string result = "";
                    for (var i = 0; i < document.NumberOfPages; i++)
                    {
                        var page = document.GetPage(i + 1);
                        var words_2 = page.GetWords();
                        var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(words_2);
                        foreach (var block in blocks)
                        {
                             result = result + "  " + block.Text.ToString() ;
                        }
                   }
                  
                    return result;
                }
            }
            catch(Exception) {
                return "";
            }
        }
```

I have also attached one such pdf for which I am getting the similar issue along with the parsed result. Please look into the issue Thanks in advance.

[Sample PDF document.pdf](https://github.com/UglyToad/PdfPig/files/6398585/Sample.PDF.document.pdf)
[Parsed result.docx](https://github.com/UglyToad/PdfPig/files/6398592/Parsed.result.docx)

**Comment by EliotJones** [comment]
Hi, document layout analysis isn't an exact process, it's based on best-guesses. It sounds like the word extraction is the problem so maybe try using the Nearest Neighbour word extractor https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#nearest-neighbour-method before feeding the data into the Docstrum method. Alternatively it may be necessary to write custom logic to construct words using `page.Letters`. The default approach is very naive and doesn't seek to be correct except in the simplest cases.

**Comment by ArkadeepDey71** [comment]
Hi ,We have already tried to implement the Nearest Neighbors word extractor to extract words from the pdf but got the similar type of output (sequence of letters without whitespace).

While investigating we found out that the whitespace between letters are also not appearing in the `Page.Letters` . So could you please suggest how can we customize the `Page.Letters` to generate words. 

The Font name of most of the letters were `HGKNAF+AdvOTb49d9406` and it was one of the embedded font in the PDF . Do embedded fonts cause any issues while scanning the letters in a page?

**Comment by EliotJones** [comment]
It looks like these documents contain unusually narrow word gaps. I've added a slightly more 'intelligent' approach to word gap calculation in 0.1.5-alpha002 https://www.nuget.org/packages/PdfPig/0.1.5-alpha002 please give it a try and let me know,.

**Comment by ArkadeepDey71** [comment]
Hi @EliotJones I have tested the new changes for lots of documents and its working as expected. When do we expect this new changes in release branch ?

**Comment by ArkadeepDey71** [comment]
Hi @EliotJones 
Any updates on this. When do we expect this new changes in main release branch ?

**Comment by BobLd** [comment]
Closed as answered - feel free to reopen if need be
