### ISSUE TITLE
Issues reading unicode document properties?

### ISSUE THREAD

**Issue by Numpsy** [UglyToad/PdfPig#32]
Hi,

I had a try with loading some simple test documents into PdfPig 0.0.6, and noticed that unicode document properties don't seem to be handled correctly.

e.g., if I open the attached [minimal.pdf](https://github.com/UglyToad/PdfPig/files/3253137/minimal.pdf) in Acrobat reader it displays:

![image](https://user-images.githubusercontent.com/1178570/58890904-6adbd200-86e3-11e9-88a2-03bca07501f2.png)

but in PdfDocument.Information, I get:

![image](https://user-images.githubusercontent.com/1178570/58891209-053c1580-86e4-11e9-835a-4339b7a32503.png)

Would this be expected to work?

Thanks.

**Comment by EliotJones** [comment]
Thanks for raising this and providing a replication. 

I've had a look and it seems PDFs can support UTF-16 Big and Little Endian strings in its content, I've added what I believe should fix the behaviour here though it seems like the resulting string is 'weird' when it comes to comparing string equality with normal C# strings.

**Comment by Numpsy** [comment]
Thanks, that looks better now.

I have just accidentally discovered a variation of the issue when trying to create a new test pdf with LibreOffice though - the document properties come out as HexTokens with a BOM attached:

![HexToken](https://user-images.githubusercontent.com/1178570/59858912-b8a73a00-9373-11e9-837b-9cc81b0746da.png)

Sample file: 
[PropsAddedWithLibreOffice.pdf](https://github.com/UglyToad/PdfPig/files/3310951/PropsAddedWithLibreOffice.pdf)

**Comment by Numpsy** [comment]
> 
> though it seems like the resulting string is 'weird' when it comes to comparing string equality with normal C# strings.

The [MS Docs](https://docs.microsoft.com/en-us/dotnet/api/system.text.unicodeencoding.getstring?view=netframework-4.8) suggests that the strings that come back from GetString have a BOM left at the start, and suggests Trimming the string to remove them?

**Comment by EliotJones** [comment]
Ok, I've made it remove the BOM by default now, hopefully this won't break something else! 😆

**Comment by EliotJones** [comment]
Does this seem to be working for the documents you're dealing with after the fix and if so are you happy to close it? Just finding old issues to close where I can.

**Comment by Numpsy** [comment]
Looks good now
