### ISSUE TITLE
Could not read the first token in the document at position 0

### ISSUE THREAD

**Issue by wildview** [UglyToad/PdfPig#334]
Thanks for your work on this, it's amazing. I get the following error when opening some our PDF files - 'UglyToad.PdfPig.Core.PdfDocumentFormatException: 'Could not read the first token in the document at position 0.' I'm not sure why it's throwing this error which iText doesn't throw. Is there a way to resolve this using PdfPig? Or what in the PDF would cause this error to occur since they look normal in the browser?

Maybe there is something else in the PDFs that fail to open that differ from the ones that work, but not sure. Hopefully, there's a workaround since we'd like to use PdfPig for parsing our PDF files since it seems to be quite accurate vs. some of the other parsers we've tried =)

I can email the pdf to you, but can't post it here since it's has Judicial information.  

```
using (var pdf = PdfDocument.Open(file))
{
	foreach (var page in pdf.GetPages())
	{
		var text = ContentOrderTextExtractor.GetText(page);
		var blocks = DocstrumBoundingBoxes.Instance.GetBlocks(page.GetWords());

		string result = "";
		foreach (var block in blocks)
		{
		  result = result + "  " + block.Text.ToString();
		}
		Console.WriteLine(result);
	}
}
```

Thanks for your help, Rob

**Comment by EliotJones** [comment]
Hi there @wildview sorry to hear you're encountering this issue. Before looking at the file would you be able to share the full stack-trace of the error please, it might be evident from the error alone, but probably not. Also which version of the library are you using, do you still get the error with the latest pre-release version whihc I think is 0.1.5-alpha002?

**Comment by wildview** [comment]
Hey Eliot. Thanks for getting back to me. I'm using the latest alpha release 0.1.5-alpha002. The stable release v0.1.4 reports the same error. I can't really see anything wrong in the PDF to why it would fail the PdfDocument.Open method. Some of our PDFs work fine and others don't, but look the same. I hope we can figure out the issue since this is a great package we'd like to use =)  Below is the stack trace of the error. If you want, I can PM the PDF directly if needed to help in finding the problem.  Thanks so much!

UglyToad.PdfPig.Core.PdfDocumentFormatException: Could not read the first token in the document at position 0.
   at UglyToad.PdfPig.Parser.FileStructure.FileHeaderParser.Parse(ISeekableTokenScanner scanner, Boolean isLenientParsing, ILog log) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Parser\FileStructure\FileHeaderParser.cs:line 53
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, ILog log, Boolean isLenientParsing, IReadOnlyList`1 passwords, Boolean clipPaths) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 100
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 78
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(String filename, ParsingOptions options) in C:\git\csharp\PdfPig\src\UglyToad.PdfPig\Parser\PdfDocumentFactory.cs:line 40
   at Pdf2Text.Program.Main(String[] args) in C:\Users\Robert Short\Downloads\Pdf2Text.Full.20150420\Pdf2Text\Program.cs:line 28

**Comment by EliotJones** [comment]
@wildview Thanks for the reply, it's definitely a bug in PdfPig but I'm not 100% sure of the cause.

Since I don't want to cause you to have to share sensitive data if at all possible it looks like it should be sufficient to diagnose the issue if you open the document in something like Notepad++/Notepad/nano etc and share the first 5 or so lines of the text content, for example from a random file in my archive it will look something like:

```
%PDF-1.7
%ÈÈÈÈÈÈÈ
18 0 obj
<</Filter/FlateDecode/Length 5546>>stream
H‰¬WÛŽÇÕ«ùó@
ÀÙ¾÷@0Xr—È@ ~‚
```

If you can copy down to at least the first instance of some text like `%PDF-1.5` or `%PDF-1.7` or similar that should give some idea what's going on, it seems like the file header might not appear at the beginning instead it occurs after some content that confuses the token scanner.

**Comment by wildview** [comment]
Hi Eliot, here are the first 37 lines of the PDF file that fails. Hopefully this helps to locate the problem. Fingers crossed =)

`%PDF-1.7
%âãÏÓ
1 0 obj
<</Lang(en-US)/MarkInfo<</Marked true>>/Metadata 630 0 R/Pages 2 0 R/StructTreeRoot 50 0 R/Type/Catalog/ViewerPreferences 631 0 R>>
endobj
630 0 obj
<</Length 3512/Subtype/XML/Type/Metadata>>stream
<?xpacket begin="ï»¿" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 5.2-c001 63.143651, 2012/04/05-09:01:49        ">
   <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <rdf:Description rdf:about=""
            xmlns:pdf="http://ns.adobe.com/pdf/1.3/">
         <pdf:Producer>MicrosoftÂ® Word for Office 365</pdf:Producer>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:dc="http://purl.org/dc/elements/1.1/">
         <dc:format>application/pdf</dc:format>
         <dc:creator>
            <rdf:Seq>
               <rdf:li></rdf:li>
            </rdf:Seq>
         </dc:creator>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:xmp="http://ns.adobe.com/xap/1.0/">
         <xmp:CreatorTool>MicrosoftÂ® Word for Office 365</xmp:CreatorTool>
         <xmp:CreateDate>2021-05-27T15:24:31-04:00</xmp:CreateDate>
         <xmp:ModifyDate>2021-05-28T11:09:59-04:00</xmp:ModifyDate>
         <xmp:MetadataDate>2021-05-28T11:09:59-04:00</xmp:MetadataDate>
      </rdf:Description>
      <rdf:Description rdf:about=""
            xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/">
         <xmpMM:DocumentID>uuid:554C9CE1-4EC9-4008-BA18-96DACA0BAB19</xmpMM:DocumentID>
         <xmpMM:InstanceID>uuid:45e275de-666c-4768-8df6-c47652ec6ff8</xmpMM:InstanceID>
      </rdf:Description>
   </rdf:RDF>
</x:xmpmeta>`

**Comment by EliotJones** [comment]
Thanks for that, it all looks normal and the test case works as expected. In your code you're opening the file by passing a file-path to `PdfDocument.Open()` correct?

It look like unfortunately I will need the full file to diagnose the issue. My email is elioty at hotmail &period; co dot uk

With &period; being a dot obviously, just trying to trick the spambots 😆.

**Comment by wildview** [comment]
Hey Eliot, it appears it was our PDFs there were causing the problem. Sometimes when requesting these across or SOAP exchange they've gotten corrupted. I thought this was fixed, but guess not. Anyway, we can close this ticket since PdfPig is working fine. Thanks for assisting though and look forward to using pdfPig. Cheers.
