### ISSUE TITLE
Support AES-256bit encryption

### ISSUE THREAD

**Issue by jonmiller1** [UglyToad/PdfPig#34]
I really like this library.  The letters feature that shows me the glyph rectangle is very helpful.  The problem I'm having is that a lot of my PDF documents come in encrypted AES-256 bit.  Please support it!  Thank you!

**Comment by EliotJones** [comment]
Thanks for the feedback, I'll look into adding AES support as the next feature.

I think I've got a couple of documents in my test set which are AES encrypted, do you have any documents you're able to share so I can check it works once I've implemented it?

**Comment by EliotJones** [comment]
Can you please give the attached nuget package a go and let me know if it works for your files please? I've added support for revision 5 encryption defined in this supplement: https://www.adobe.com/content/dam/acom/en/devnet/flashplayer/pdfs/adobe_supplement_iso32000.pdf

Currently the PDF version 2 specification defines an additional encryption level (revision 6) but the specification is being held hostage by ISO who want a vast amount of money for it, I could port the line by line version of the PDFBox algorithm for that level but I'd rather avoid it if this works.

[PdfPig.0.0.6.1.zip](https://github.com/UglyToad/PdfPig/files/3287716/PdfPig.0.0.6.1.zip)

**Comment by jonmiller1** [comment]
I'm testing it now.  I do not have any documents that I can share at this time.

**Comment by jonmiller1** [comment]
I'm getting the error "Support for revision 6 encryption not supported"

**Comment by EliotJones** [comment]
OK, looks like revision 6 also needs to be implemented, I'll try to get round to it soon.

**Comment by jonmiller1** [comment]
Thanks!  I also noticed that I've got a lot of files that encrypted with 40-bit RC4 that don't open either.  Is that cipher supported?

**Comment by EliotJones** [comment]
Hmm, I'm surprised the RC4 doesn't work, do you get a specific error, the details might be in the inner exception?

**Comment by Numpsy** [comment]
I don't have any RC4 encrypted files to hand to test with, but in case it's of any interest I tried encrypting a trivial PDF with the online tool @ http://www.pdfill.com/pdftool_encrypt.html and the resulting file is opened and identified as RC4 40bit by Acrobat Reader, but reading it with PdfPig throws

```
UglyToad.PdfPig.Exceptions.PdfDocumentFormatException : The dictionary did not contain a number with the key /Size. Dictionary way: .
```

```
Result StackTrace:	
at UglyToad.PdfPig.Util.DictionaryTokenExtensions.GetInt(DictionaryToken token, NameToken name)
   at UglyToad.PdfPig.CrossReference.TrailerDictionary..ctor(DictionaryToken dictionary)
   at UglyToad.PdfPig.CrossReference.CrossReferenceTableBuilder.Build(Int64 firstCrossReferenceOffset, ILog log)
   at UglyToad.PdfPig.Parser.FileStructure.CrossReferenceParser.Parse(IInputBytes bytes, Boolean isLenientParsing, Int64 crossReferenceLocation, IPdfTokenScanner pdfScanner, ISeekableTokenScanner tokenScanner)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.OpenDocument(IInputBytes inputBytes, ISeekableTokenScanner scanner, IContainer container, Boolean isLenientParsing, String password)
   at UglyToad.PdfPig.Parser.PdfDocumentFactory.Open(IInputBytes inputBytes, ParsingOptions options)
   at UglyToad.PdfPig.PdfDocument.Open(Stream stream, ParsingOptions options)
```

Sample file: 
[rc4.pdf](https://github.com/UglyToad/PdfPig/files/3314064/rc4.pdf)

**Comment by EliotJones** [comment]
@Numpsy thanks, I didn't think to try using an online tool. I've tried a couple of documents from that site and they seem to have some problems with cross-reference table positions which I've fixed in the last commit, do you remember the password for the file you attached? I just want to check if it had a different problem to the one I think I resolved.

**Comment by Numpsy** [comment]
ah, sorry, forgot to say - the password should just be 'password'

**Comment by EliotJones** [comment]
I've found this tool which is capable of producing Revision 6 encrypted documents so can start an implementation soon. I've attached an example file for which the password is `maltby`.

[encrypt-revision-6-maltby.pdf](https://github.com/UglyToad/PdfPig/files/3317862/encrypt-revision-6-maltby.pdf)

**Comment by EliotJones** [comment]
Sorry for the delay in implementing this. I think it should now be working. Please try the attached package.

If you do encounter errors please try and post as many details as possible, particularly inner exceptions and stack traces.

[PdfPig.0.0.6.34.1.zip](https://github.com/UglyToad/PdfPig/files/3326861/PdfPig.0.0.6.34.1.zip)

**Comment by EliotJones** [comment]
Are you happy to close this issue now? Hopefully the latest 0.0.7 version includes full encryption support but I've not had many documents to test against so just wanted to check if it's ok to close this issue.
