### ISSUE TITLE
Bug: PdfPageBuilder.CopyFrom did not preserve the page orientation

### ISSUE THREAD

**Issue by Banyc** [UglyToad/PdfPig#348]
The source page (`page.Rotation == 90`) is in horizontal orientation. The new document generated from `PdfPageBuilder.CopyFrom` has a correct orientation in page size, but with a vertical-oriented content.

The example code is in the following:

```csharp
PdfDocumentBuilder builder = new();
var page = this.document.GetPage(pageIndex + 1);
PdfPageBuilder pageBuilder = builder.AddPage(page.Width, page.Height);
pageBuilder.CopyFrom(page);

var bytes = builder.Build();
File.WriteAllBytes(outputFilePath, bytes);
```

**Comment by EliotJones** [comment]
I think this should be covered by AddPage
