### ISSUE TITLE
PdfPageBuilder.CopyFrom() creates invalid PDF

### ISSUE THREAD

**Issue by cremor** [UglyToad/PdfPig#350]
1. Download this PDF: https://cartographicperspectives.org/index.php/journal/article/download/cp43-complete-issue/pdf/
2. Use PdfPig to create a new PDF from that PDF by calling `PdfDocumentBuilder.AddPage(sourcePage.Width, sourcePage.Height).CopyFrom(sourcePage)` for all pages.
3. Notice that the created PDF is only 64 MB big, while the original PDF has 100 MB.
4. Open the created PDF in Acrobat Reader and scroll to page 2.
5. Notice that Acrobat shows an error message about errors on the page.
6. Notice that some text is missing on the right side of the page. And that some wrong text is shown on the lower right side.
7. Redo step 2 but call `PdfDocumentBuilder.AddPage(sourceDocument, pageNumber)` this time.
8. Notice that the created PDF now has 100 MB and is shown correctly in Acrobat Reader.

Tested with PdfPig version 0.1.5-alpha002

Screenshots:

Expected:
![grafik](https://user-images.githubusercontent.com/116314/127871313-1deaf948-2e5c-4ee2-a57f-84fd52a3c375.png)

Problem:
![grafik](https://user-images.githubusercontent.com/116314/127871381-2e57fa30-36a0-4ac1-b734-9c2c03cf3148.png)

**Comment by EliotJones** [comment]
Any chance this was fixed in a different ticket? Anyone has time to check?

**Comment by fnatzke** [comment]
@EliotJones,

Remains in current version as described.

`
        static void Issue350()
        { 
            using (var sourceDocument = PdfDocument.Open(@"C:\src\PdfPig\Issues\350\pkpadmin,+529-2711-1-CE.pdf"))
            {
                PdfDocumentBuilder pdfBuilder = new PdfDocumentBuilder();
                var numberOfPages = sourceDocument.NumberOfPages;
                foreach (var sourcePage in sourceDocument.GetPages())
                {
                    pdfBuilder.AddPage(sourcePage.Width, sourcePage.Height).CopyFrom(sourcePage);
                }
                var pdfBytes = pdfBuilder.Build();
                WritePdfFile("Approach1-Builder-AddPages", pdfBytes);
            }

            using (var sourceDocument = PdfDocument.Open(@"C:\src\PdfPig\Issues\350\pkpadmin,+529-2711-1-CE.pdf"))
            {
                PdfDocumentBuilder pdfBuilder = new PdfDocumentBuilder();
                var numberOfPages = sourceDocument.NumberOfPages;
                for (int pageNumber = 1; pageNumber <= numberOfPages; pageNumber++)
                {
                    pdfBuilder.AddPage(sourceDocument, pageNumber);
                }
                var pdfBytes = pdfBuilder.Build();
                WritePdfFile("Approach2-Doc-AddPages", pdfBytes);
            }
        }
        private static void WritePdfFile(string name, byte[] bytes, string extension = "pdf")
        {
            const string subFolder = "Issue350";
            var folderPath = subFolder;

            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }

            var filePath = Path.Combine(folderPath, $"{name}.{extension}");
            File.WriteAllBytes(filePath, bytes);
            Debug.WriteLine($@"{Path.Combine(Directory.GetCurrentDirectory(), filePath)}");
        }
`
![Page2-AdobeAcrobatReader-Error-PopUp-Screenshot](https://user-images.githubusercontent.com/15922731/209417509-1249d770-de85-49c8-aa59-a628386fae20.png)

![FileSizes](https://user-images.githubusercontent.com/15922731/209417507-046bf7c5-8bc1-4011-a77e-4edb4c1411f6.png)
![AdobeAcrobatReaderVersionScreenshot](https://user-images.githubusercontent.com/15922731/209417519-a6a5c3d6-255a-4d95-9cd1-f7948dcf50dd.png)
![ScreenshotMissingText](https://user-images.githubusercontent.com/15922731/209417523-feacd99f-b368-4840-94de-86d8bb80d2a5.png)

**Comment by fnatzke** [comment]
@cremor , @EliotJones,

Bug fix checked in.

The first approach incorrectly copies ShowText operations on page 2. On page 2 there are 3 ShowText operations with unbalanced round brackets in the text of the operation. Unbalanced meaning there is an open bracket without a close bracket or close without open.
1. line 387   (\() Tj
2. line 397   (\)) Tj
3. line 384   ( \(I\222ll try to stay on ) Tj
note in text 3 the 0222 (octal) or (0x92 hex) is similar to an apostople ' so text is similar to " (I'll try to stay on" (with an open bracket).

The output created in the copied PDF did not include the '\' which is why Adobe generated an error and text after these operations were missing.
