### ISSUE TITLE
transparency

### ISSUE THREAD

**Issue by simonedd** [UglyToad/PdfPig#353]
Hello,

Is color transparency supported or do you have any plan to add it?

**Comment by EliotJones** [comment]
@simonedd is this color transparency for letters and paths? Currently it is not supported. It might be added later but since transparency is a whole chapter of the PDF specification covering over 60 pages of specification it's not likely to be soon.

**Comment by simonedd** [comment]
Especially for filled paths, as in the attached file.
[PDF_Transparency.pdf](https://github.com/UglyToad/PdfPig/files/6998365/PDF_Transparency.pdf)

**Comment by EliotJones** [comment]
Life gets in the way and absent a new contributor I'm never going to get to this, closing as wontfix
