### ISSUE TITLE
Tolerance in drawing is incorrectly got

### ISSUE THREAD

**Issue by powerfulant** [UglyToad/PdfPig#356]
Dears,

For some .pdf drawings, we found that the tolerance which PdfPig gets from them is incorrect and different from what they are in the .pdf drawings. hereby is an example:

the information in the .pdf drawing:
![image](https://user-images.githubusercontent.com/14267006/128439889-8c662fb8-2807-4d24-a8de-2384d402e793.png)

the information get by PdfPig is as following:
![image](https://user-images.githubusercontent.com/14267006/128440761-535cb2bb-4fc4-4f4c-9827-29eb092eeb58.png)

Since the .pdf drawing is sensitive, I can not upload the original file,
Do you even encounter such problem and is there a solution for that?

Many thanks.
Lorry

**Comment by powerfulant** [comment]
Did anyone encountered such problem?

**Comment by EliotJones** [comment]
Hi there's really not enough information in your ticket to help with this problem. How are you getting the text in the bottom image, what text extraction process are you using, are these the positions of the raw letters? If so without at least a document to replicate it it's extremely unlikely anyone can fix it.
