### ISSUE TITLE
Find Annotation that is referenced by 'In Reply To' (IRT) key in another Annotation

### ISSUE THREAD

**Issue by PhantoManresa** [UglyToad/PdfPig#362]
Hi,
I am trying to read the comments in a pdf file. Since the comments are annotations, I am able to get them through the `Page.Experimental.GetAnnotations()` functionality. There are some comments that are a reply to other comments. I found out that the ObjectId of the Annotation that is being replied to could be found in the key `IRT` of the annotation dictionary that the reply Annotation was created from.
So far so good. My problem is that I do not really know which Annotation is being referenced to in the IRT key since the Annotation class do not have the ObjectId of the annotation in the page. The `AnnotationProvider` class seems to do what I need to associate an ObjectId to an Annotation but it is internal and I cannot use it. The other option I found could be using the `DirectObjectFinder` class but it is internal as well.

Is there a way for me to find which Annotation is being replied to?

Thanks in advance

**Comment by EliotJones** [comment]
![image](https://user-images.githubusercontent.com/7862346/206929654-fbc69b79-b782-4917-a296-076294124fb7.png)
For anyone who wants to try implementing this

**Comment by EliotJones** [comment]
This is available now on the `InReplyTo` property on the `Annotation` class in tonight's build
