### ISSUE TITLE
Unable to Get Inline Image

### ISSUE THREAD

**Issue by mayurjansari** [UglyToad/PdfPig#363]
![image](https://user-images.githubusercontent.com/18002706/131088015-3ce6e953-2894-4674-846f-cbdf24acaa3f.png)

details where image locate

**Comment by BobLd** [comment]
Can you describe exactly your problem, there is now way anybody can understand the issue you are facing. Also, attached a pdf sample.

**Comment by mayurjansari** [comment]
File contains some private details so i can mail you
