### ISSUE TITLE
Incorrect number format when using not "en-US" number style

### ISSUE THREAD

**Issue by OneHalf3544c** [UglyToad/PdfPig#37]
Hi. Thank you for this library, this good, but I have problem.
When I use PC with not  "en-US" style numbers, by default I have throw when try open any pdf file.
I was try to fix this but still not found all parse function.

for example:

        private static decimal ReadDecimal(IInputBytes input)
        {
            decimal result;

            var str = ReadString(input);

            Decimal.TryParse(str, NumberStyles.Any, new CultureInfo("en-US"), out result); // <-

            return result;
        }

Sorry for my english. Thank you for your work.

**Comment by EliotJones** [comment]
Thanks for your issue report, this isn't something I would have thought to test. I'll try to get this in for the next release but it may be a week or so until I get time.

Thanks again for the useful bug report.

**Comment by EliotJones** [comment]
Hi, I've made an updated which I think correctly handles all culture sensitive parsing, would you be able to try the attached nuget package and let me know if you encounter any errors please?

[PdfPig.0.0.6.37.zip](https://github.com/UglyToad/PdfPig/files/3302884/PdfPig.0.0.6.37.zip)

**Comment by OneHalf3544c** [comment]
Thank you! Thank you! Now seems working well!
