### ISSUE TITLE
change request: DocstrumBoundingBoxes, allow extra processing between GetLines and GetStructuralBlocks

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#376]
hello,

thank you for your great work on this library, DocstrumBoundingBoxes in general works very well but it has some issues with parsing superscripted characters. Tweaking the parameters doesn't seem to solve it, but I can correct it with some custom code I need to execute after GetLines but before GetStructuralBlocks executes.
Unfortunately there is no way for me to do this besides re-implementing the entire IPageSegmenter, which would be 99% the same as the current DocstrumBoundingBoxes implementation. Some sort of dependency injection or another solution would be much appreciated here.

**Comment by Hert79** [comment]
hello,

thx for these changes.
The parsing of the superscript is really simple. I am only interested in superscripted numbers, assume the 2 is superscripted here:
in the pdf: some text2 to parse
is parsed to:
textline: some text
textline: 2
textline: parse

I then take all TextLines with only a single number in it, see if it overlaps on the Y axis with any of the other lines, and if so stick them back together in a single TextLine object.

**Comment by BobLd** [comment]
Thanks for the insights!
