### ISSUE TITLE
Unable to build release on UWP 

### ISSUE THREAD

**Issue by Shen666666** [UglyToad/PdfPig#379]
Hello,

I have got a compilation problem on UWP. after adding PdfPig 1.5 from Nuget, I am not able to build the release with these errors

![image](https://user-images.githubusercontent.com/14927326/137862763-3f5a1cf9-a63e-4d6e-8a36-1718c038af96.png)

The UWP release compile with .Net native tool chain, if we uncheck the .Net native tool chain, I will not get the build errors but this is necessary for release a uwp application in Microsoft Store.

![image](https://user-images.githubusercontent.com/14927326/137862992-32dd93ab-d82f-4e9a-8568-7528ae06bb61.png)

Thanks in advance.

Best regards,
Shen

**Comment by linhnt3012** [comment]
I'm facing that too, did you found any solution @Shen666666 

Thanks & Best regards,
Linh

**Comment by mryderie** [comment]
@linhnt3012 I had the same issue, and was able to resolve it by adding the following line to the Application element in my project's Runtime Directive (.rd.xml) file:

<Assembly Name="UglyToad.PdfPig.DocumentLayoutAnalysis" Dynamic="Auto" />

**Comment by Shen666666** [comment]
> I'm facing that too, did you found any solution @Shen666666 ?
> 
> Thanks & Best regards, Linh

Hello @linhnt3012, the solution of @mryderie was working for me

**Comment by Shen666666** [comment]
> @linhnt3012 I had the same issue, and was able to resolve it by adding the following line to the Application element in my project's Runtime Directive (.rd.xml) file:
> 
> ```
> <Assembly Name="UglyToad.PdfPig.DocumentLayoutAnalysis" Dynamic="Auto" />
> ```

Thanks, it worked perfectly ! 👍 

- [ ]
