### ISSUE TITLE
Support for custom document properties in PDFs?

### ISSUE THREAD

**Issue by Numpsy** [UglyToad/PdfPig#38]
Hi,

Can I ask if there are any plans and/or possibility of supporting custom document properties in PDF files as well as the 'known' ones (Author and Keywords and such)?

I haven't used PDFBox, but the documentation for PDDocumentInformation does seem to have functions to access custom properties.

**Comment by EliotJones** [comment]
That sounds like a good addition to the API, it would be fairly easy to add by providing access to the underlying `DictionaryToken` in the `DocumentInformation` object. I'll look into adding it when I get time.

**Comment by EliotJones** [comment]
This is in the latest master code now, it might be worth testing it out for your documents if you're able, I don't have any documents with custom info at the moment to test against. It should make it into the 0.0.7 release for which the timeline is "hopefully soonish".

**Comment by Numpsy** [comment]
Thanks, i'll give it a test tommorow.

**Comment by Numpsy** [comment]
Ok, I started adding a unit test @ https://github.com/Numpsy/PdfPig/commit/db0f1c7fb0d0bc27d5aeccd91aefde8cef71eb2b, and i'm not sure if I've got another issue there.

The 'custom-properties.pdf' file attached to that commit contains multiple sets of document information, which have a few differences in the property values.
If I open the file in Firefox, it shows the Keywords property as being 'MoreKeywords' (which is what I was expecting), but when loading in PdfPig the value in Document.Information is 'TestKeywords', which is an old/previous value.

Possibly something else going wrong somewhere?

**Comment by EliotJones** [comment]
Thanks for the further bug report, I've pushed some changes which seem to work for this document (and not break the tests!). Let me know if you run into any more issues please, I think the code in that area needs a bit of a rewrite/tidy-up.

**Comment by Numpsy** [comment]
Ok, that seems to work now, thanks.

Would you be interested in a PR for https://github.com/Numpsy/PdfPig/commit/10dcbd0cc4d836dd93bb18634af918ae7411992b to add a unit test?

**Comment by EliotJones** [comment]
Yes, thank you, that would be good to cover with a test.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by EliotJones** [comment]
Just doing some tidying up, are you happy to close this issue now?

**Comment by Numpsy** [comment]
Yes, it looks good now, i'll close the issue.
