### ISSUE TITLE
GlyphRectangle has a height of 0

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#380]
You can simulate this by changing the GetBlocks unit test to read the attached pdf [PdfPigGlyprectangleHeightZero.pdf](https://github.com/UglyToad/PdfPig/files/7371626/PdfPigGlyprectangleHeightZero.pdf).
It fails to decode the font of the copyright statement (© 2020, Brepols Publishers n.v., Turnhout, Belgium), this exception is thrown:
Found invalid token Token[type=StartArray, text=[] when type StartProc with text  was expected.

with this call stack:
   at UglyToad.PdfPig.Fonts.Type1.Parser.Type1EncryptedPortionParser.ReadExpected(Type1Tokenizer tokenizer, TokenType type, String text) in PdfPig\src\UglyToad.PdfPig.Fonts\Type1\Parser\Type1EncryptedPortionParser.cs:line 411

You could think this is an error in the font of the pdf, but PdfBox does manage to extract the character's heights which leads me to believe it is a PdfPig specific bug.

**Comment by EliotJones** [comment]
Closing this since I think it was fixed in a previous nightly build, let me know if you encounter any issues.
