### ISSUE TITLE
How to extract images?

### ISSUE THREAD

**Issue by dehyang** [UglyToad/PdfPig#398]
I don't know how to operate

page.GetImages()  ... After？

Help me, thank you

**Comment by EliotJones** [comment]
Note to self: `// TODO: add a sample to the examples folder`

**Comment by TomSwiedler** [comment]
The simplest way is to let PdfPig process the filters for the image.

The two methods TryGetPng and TryGetBytes will attempt to do this:

```cs
foreach (var Image in page.GetImages())
{
  string ImageType = String.Empty;

  if (Image.TryGetPng(out var ByteArray))
  {
    ImageType = "png";
  }
  else if (Image.TryGetBytes(out var ByteList))
  {
    ByteArray = ByteList.ToArray();
    ImageType = "Most likely JPG";
  }
  else
  {
    ByteArray = Image.RawBytes.ToArray();  //None of the filters are applied to the result. This can be an issue.
    ImageType = "Unknown";
  }

// Process the ByteArray as an image. i.e. save it to a file, send it on to a downstream process.
}
```

There is an issue with files having an unknown type of filter. TryGetPng and TryGetBytes will both fail.
There is another issue with images that have the DCTDecode (or just DCT) filter. It seems that the expected default image format is Jpeg. The DCTDecode filter (which I think is specifying the image format is Jpeg) is considered an error. It could be argued that the DCTDecode filter should invoke an identity filter and be done.

If you have an image that contains the DCTDecode filter you can get around the issue by executing the other filters in the chain.

```cs
private byte[] ApplyFilters(IPdfImage Image)
{
  byte[] Result = Image.RawBytes.ToArray();
  IReadOnlyList<IFilter> Filters = DefaultFilterProvider.Instance.GetFilters(Image.ImageDictionary);

  foreach (var Filter in Filters)
  {
    if (Filter.IsSupported)
    {
      Result = Filter.Decode(Result, Image.ImageDictionary, 0);
    }
  }
  return Result;
}
```
Replace the call to GetBytes:
```cs
  ByteArray = Image.RawBytes.ToArray()
```
with:
```cs
  ByteArray = ApplyFilters(Image);
```
You run the risk of skipping a filter that is unknown and required to obtain the proper output. If that happens, the resulting image will be trash.

I am skipping over the third and fourth parameters to the call to decode. They involve options parameters to the filter but I have not seen them used in the images I have processed. Perhaps Eliot could provide some insight on this.

Speaking of which, Thanks to Eliot for providing this library. I am very tired of PDF packages suddenly going from free to licensed.

**Comment by EliotJones** [comment]
Thanks @TomSwiedler that's a thorough explanation.

One thing I would add though is that if `image.TryGetBytes(out b)` fails it's usually a JPG in the file directly, accessed with `image.RawBytes`. In my test archive I don't think I have a single instance of it not being a JPG or having more than just the DCT decode filter applied, which is afaik the same as a JPG discrete cosine transform and therefore the raw JPG. I'd guess if you wanted assurance the raw bytes were a JPG you could pass it to an image library to check. I think the presence of non-JPGs in the files is more common in certain document domains such as architectural plans.

There's an open PR for handling the other image type it could be but unfortunately I don't have time to complete it.

**Comment by TomSwiedler** [comment]
The problem arises when you have multiple filters. i.e. a FlateDecode followed by a DCTDecode. For me this showed up in a PDF generated by a scanner. TryGetPng and TryGetBytes both fail due to the DCTDecode. If the DCTDecode was treated as an identity filter both methods would have worked. This would make sense since the presence of the DCTDecode basically confirms it is a JPG format.

**Comment by paillave** [comment]
At my side, I am trying to save pictures on the current folder. But no file is recognized by any reader. How to do?

```csharp
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Paillave.Etl.Core;
using UglyToad.PdfPig;
using UglyToad.PdfPig.Content;
using UglyToad.PdfPig.Filters;

namespace Paillave.Etl.Samples
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var stream = File.OpenRead("MyScanned.pdf"))
            using (var pdfDocument = PdfDocument.Open(stream))
            {
                var imgs = pdfDocument.GetPages().SelectMany(page => page.GetImages()).ToList();
                foreach (var (img, idx) in imgs.Select((i, idx) => (i, idx)))
                {
                    if (img.TryGetBytes(out var jpgBytes))
                    {
                        jpgBytes = ApplyFilters(img);
                        File.WriteAllBytes($"img{idx}.jpg", jpgBytes.ToArray());
                        // File.WriteAllBytes($"img{idx}.jpg", jpgBytes.ToArray());
                    }
                    else if (img.TryGetPng(out var pngBytes))
                    {
                        pngBytes = ApplyFilters(img);
                        File.WriteAllBytes($"img{idx}.png", pngBytes.ToArray());
                        // File.WriteAllBytes($"img{idx}.png", pngBytes.ToArray());
                    }
                }
            }
        }
        private static byte[] ApplyFilters(IPdfImage image)
        {
            byte[] result = image.RawBytes.ToArray();
            IReadOnlyList<IFilter> filters = DefaultFilterProvider.Instance.GetFilters(image.ImageDictionary);

            foreach (var filter in filters)
            {
                if (filter.IsSupported)
                {
                    result = filter.Decode(result, image.ImageDictionary, 0);
                }
            }
            return result;
        }
    }
}
```

**Comment by TomSwiedler** [comment]
The problem may be the scanner is specifying a filter chain that includes the DCT or DCTDecode.
The DCT/DCTDecode is the default JPG decoder however, PDFPig treats it as an error.

I use the ApplyFilters code above to get around the issue.

**Comment by EliotJones** [comment]
Absent a file for reference I'm cloasing this. Images API is still suboptimal for consumers but I'm also 100% burnt out and need to make a decision for these old issues

**Comment by EliotJones** [comment]
@paillave a little of both. I've not seen a file with this problem but also since I haven't really had time for this project going on 3 years now I'm unlikely to be able to address it
