### ISSUE TITLE
PAGE Xml Export in LayoutEval tool throws error: "The region of the ground-truth lies not completely within the document boundaries"

### ISSUE THREAD

**Issue by davebrokit** [UglyToad/PdfPig#399]
Followed the steps to generate a PAGE Xml Export as written [here](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#description-9):

When the xml was imported into the LayoutEval tool this error was thrown: "The region of the ground-truth lies not completely within the document boundaries".

I think it is caused by the region having points on the page boundaries:

```xml
<Coords points="0,0 0,0 426,426 426,426" />
```

This can be fixed in file 

https://github.com/UglyToad/PdfPig/blob/5524473e0ee617c0bfbc00c86c45acb52e761258/src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/PageXmlTextExporter.cs#L107

by changing method to
```cs
        private string PointToString(PdfPoint point, double pageWidth, double pageHeight)
        {
            double x = Math.Round(point.X * _scale);
            double y = Math.Round((pageHeight - point.Y) * _scale);

            // move away from borders
            x = x > 1 ? x : 1;
            y = y > 1 ? y : 1;

            x = x < (pageWidth - 1) ? x : pageWidth - 1;
            y = y < (pageHeight - 1) ? y : pageHeight - 1;

            return x.ToString("0") + "," + y.ToString("0");
        }
```

**Comment by BobLd** [comment]
Hi @davebrokit, thanks for the issue and for editing the wiki. Happy to create a PR with your fix if you don't know how to do that. Also, I'd like to add tests - would you mind sharing the document that created the issue so that I can add tests with it.

**Comment by davebrokit** [comment]
@BobLd  Will raise PR. The document is located here: https://www.sharrockinsurance.co.uk/wp-content/uploads/2015/01/professional_indemnity_form.pdf.

Also I wrote a version of the PageXmlTextExporter.cs that takes an arbitrary list of objects with `PdfRectangle`. This was helpful for me when I needed to view bounding boxes I had generated. Let me know if you want me to share that too.
