### ISSUE TITLE
OCR extension & Image scanning

### ISSUE THREAD

**Issue by fasteddys** [UglyToad/PdfPig#411]
Hello, I saw glyps (was not clear), I was wonderign if you can please add an extension to support OCR such as tesseract and

**Comment by BobLd** [comment]
You'll find a C# wrapper for tesseract-ocr here: https://github.com/charlesw/tesseract

**Comment by fasteddys** [comment]
thanks, but his is not compatible with .net core ASP 6, yours runs on them. Would be nice to have an extension in the same/your lib.
