### ISSUE TITLE
How to get page orientation?

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#42]
First of all, thank you! This library is great! But it seems there are some minor issues :-)

It seems page width/height is not correctly reported when page is rotated.
E.g. in the attached document it's showing width=612 and height = 792, but it's in landscape. So should it be reversed? Or have some orientation flag similar to PdfBox "page.findRotation()" method?

[letter_size_problem.pdf](https://github.com/UglyToad/PdfPig/files/3327376/letter_size_problem.pdf)

```
            
using (PdfDocument document = PdfDocument.Open(@"letter_size_problem.pdf"))
{
    var page = document.GetPage(1);
    decimal width = page.Width;
    decimal height = page.Height;
}

```

**Comment by EliotJones** [comment]
Thanks for your issue reports. I've had a look and it appears I've missed the `/Rotation` flag from my calculation of pages. I'll try and get round to fixing this as soon as I can.

As a workaround you can get the rotation from the page dictionary https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Content/Page.cs#L21 by doing `page.Dictionary.TryGet(NameToken.Rotation, out NumericToken numericRotation)`.

But I think not accounting for the `Rotation` is also causing letters to get the wrong size as you reported in #41 so it needs fixing.

**Comment by vadik299** [comment]
Page.Rotation property works well. Thank you!

**Comment by topcat30** [comment]
hi guys, on the subject of rotation, how can a change the rotation of a PDF?
