### ISSUE TITLE
Support for PageSegmenterOptions with PageXmlTextExporter

### ISSUE THREAD

**Issue by JeffJankowski** [UglyToad/PdfPig#424]
Maybe I'm missing something, but I'd like to visualize how tweaking the `PageSegmenterOptions` parameters changes the bounding regions of the extracted blocks. In particular I'm using `RecursiveXYCut`, but the `PageXmlTextExporter` constructor only seems to accept an instance of `RecursiveXYCut`. However, `RecursiveXYCutOptions` is only accepted when calling the `GetBlocks` method.

Reviewing the source, it looks like `GetBlocks` is called with the default options: https://github.com/UglyToad/PdfPig/blob/99c284c719c61ac1f0a25688fa0929a3678a60ea/src/UglyToad.PdfPig.DocumentLayoutAnalysis/Export/PageXmlTextExporter.cs#L178

**Comment by BobLd** [comment]
Hi @JeffJankowski,

This is unfortunately correct, the `PageXmlTextExporter` does not accept options for the moment as the `PageSegmenterOptions` classes were added to the library after the exporters... 

Feel free to update the code and create a PR to be able to include them, or I'll try to do it shortly, but not really sure when I'll have time.

Checking the code, the `exporters`, `segmenters` and `PageSegmenterOptions` meed need a light rewrite.... For example, I don't remember why I created the base class `DlaOptions` as an abstract class and not an interface; Also, it might be a good idea to add the `DlaOptions` inside the segmenter constructor, and not in the `GetBlocks(words);` function.

Any comment welcome!
