### ISSUE TITLE
boundingbox of word much too big

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#425]
While parsing pdf's I came across a word with a boundingbox that is a lot larger then the page crop box. the strange thing is the individual letters look ok, but throw them together in a Word object and the boundingbox size goes bonkers.
See attached pdf
[bigword.pdf](https://github.com/UglyToad/PdfPig/files/8184397/bigword.pdf)

**Comment by BobLd** [comment]
Note for later, it's the first letter's bounding box that is problematic. It seems to be a special character ![image](https://user-images.githubusercontent.com/38405645/156732201-776eb4e8-ec2f-419e-a0f9-cc5aa8a9d07d.png)
![image](https://user-images.githubusercontent.com/38405645/156732394-6c80cb14-214a-44fa-bb09-d7cbeb77b7d2.png)

**Comment by Hert79** [comment]
Out of interest, which tool are you using to draw the bounding boxes?

**Comment by BobLd** [comment]
Have a look here https://github.com/BobLd/DocumentLayoutAnalysis/tree/master/DocumentLayoutAnalysis/DlaViewer

**Comment by EliotJones** [comment]
Thanks for reporting this. A fix should be available in the latest nightly NuGet package.

**Comment by EliotJones** [comment]
Closing this as the fix is now available, let me know if there are any issues.
