### ISSUE TITLE
NullReference exception when reading pdf

### ISSUE THREAD

**Issue by Hert79** [UglyToad/PdfPig#434]
when attempting to read this document:
https://doi.org/10.3306/STUDIALULLIANA.116.127

the call to GetPages() throws a nullreference exception.
Very easy to simulate:
`_Document = PdfDocument.Open(pdfFile); `
`foreach (Page page in _Document.GetPages())`

PdfBox library doesn't seem to have this issue.

**Comment by EliotJones** [comment]
Thanks for reporting the issue. A fix for this should be available in the latest nightly NuGet package.

**Comment by EliotJones** [comment]
Closing this since the fix is available, let me know if you encounter any issues.
