### ISSUE TITLE
Letters extracted with no Value

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#44]
[a.pdf](https://github.com/UglyToad/PdfPig/files/3365275/a.pdf)

In this file all letters on pages 1-54 have Value=null. I guess this is due to font "TTdcr10"? 
Starting from page 55 letters are extracted correctly (when font is changing to ArialMT).

Is this a known issue? It seems to be working in PdfBox.

**Comment by EliotJones** [comment]
It looks like PDFBox was defaulting to returning the straightforward mapping to the character code when this happened in version 1.8 (but not version 2.0 which was the one I was working off). I've changed PdfPig to do the same now so it should return the correct values.

There are some issues with this in the document you attached, for example page 3 starts with (copied from Chrome PDF viewer):

```
1 Introduction
Many di§erent factors contributed to the global Önancial crisis of 2007-09. One such factor
seems to have been the [...]
```

So ligatures (ff and fi) return nonsense values, but this behaviour seems common to all PDF consumers for this document.

Please give the latest version a try and let me know how you get on.

**Comment by vadik299** [comment]
It's working great! Thank you Eliot!
Yes, I was testing with PdfBox 1.8, since it's the last one that works with c# (via IKVM) :-)
Seems like I can ditch it now and use PdfPig. It's so much better. Thank you for your hard work!!!
