### ISSUE TITLE
Spaces extracted as tabs

### ISSUE THREAD

**Issue by asbjornu** [UglyToad/PdfPig#441]
As mentioned in https://github.com/UglyToad/PdfPig/issues/439#issuecomment-1100861460, for some PDFs, `ContentOrderTextExtractor.GetText(page)` extracts spaces as tabs. A PDF file that illustrates this issue has been sent to @EliotJones. 

When using PdfPig to extract text for [Verification testing](https://github.com/VerifyTests/Verify) (as explained in https://github.com/VerifyTests/Verify/issues/507#issuecomment-1091523647), this causes the extracted text to be considered unequal across operating systems.

If the current behavior of extracting tabs is not a bug, I would love to see a feature added to `ContentOrderTextExtractor` where `GetText()` takes an option that allows for space normalization or something similar, ensuring the coalescing and conversion of all space and control characters into `0x20` and  `0x0A`.

**Comment by EliotJones** [comment]
Hi @asbjornu I've pushed a change to `ContentOrderTextExtractor` so that it now takes an `Options` argument which supports replace `\t`, `\v` and `\f` whitespaces with spaces.

The tab characters formed part of the actual content stream on the Mac version so this seemed like the right level to handle it.

**Comment by asbjornu** [comment]
Magnificent, @EliotJones! The only problem I have left is that sentences are broken differently on Mac and Windows. But I don't expect PdfPig to be able to do anything about that. Or do you think that would fit into `ContentOrderTextExtractor.Options` as well?

```cs
new ContentOrderTextExtractor.Options
{
    ReplaceWhitespaceWithSpace = true,
    BreakLinesAt = 120
}
```

**Comment by asbjornu** [comment]
I created #449 for the line break issue. Also, I thought that it may be more extensible and flexible if `bool ReplaceWhitespaceWithSpace` instead was `string ReplaceWhitespaceWith`, so the replacement character could be customizable?
