### ISSUE TITLE
Exception: Could not find the version header comment at the start of the document

### ISSUE THREAD

**Issue by khanshahan** [UglyToad/PdfPig#443]
I am trying to read the file `https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/e9/95/23056.PMC2132516.pdf` but I am getting an exception "Could not find the version header comment at the start of the document". 

I am using Nuget package 0.1.5.

I am using the following code:
NOTE: pdfStream is a memory stream. Position=0 has already been set. 
The same code works for the file `"https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/db/77/ymj-47-432.PMC2688166.pdf"`

```
public string GetPDFText(Stream pdfStream)
        {
            StringBuilder stringBuilder = new StringBuilder();
            var pageCount = 0;
            using (PdfDocument document = PdfDocument.Open(pdfStream))
            {
                var pages = document.GetPages();
                foreach (Page page in pages)
                {
                    string pageText = page.Text;
                    stringBuilder.Append(" " + pageText);
                    pageCount++;
                }
            }
            return stringBuilder.ToString(); 
        }
```

Any ideas what am I doing wrong ?

**Comment by EliotJones** [comment]
Hi @khanshahan, thanks for including the file, it looks like there was a bug with how PdfPig was handling file versions here. I've pushed a fix which will be included in the next release/nightly build.

**Comment by khanshahan** [comment]
Thank you very much @EliotJones
