### ISSUE TITLE
Exception: Could not find the object number 14 0 with type StreamToken instead, it was found with type ObjectToken.

### ISSUE THREAD

**Issue by khanshahan** [UglyToad/PdfPig#444]
Hi, 

I am trying to read the file `https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/15/93/OpenMed-03-e10.PMC2765762.pdf` but I am getting an exception "Could not find the object number 14 0 with type StreamToken instead, it was found with type ObjectToken".

The error is encountered when going through Pages.

I am using Nuget package **0.1.6**.
.NET 6.0

I am using the following code:
NOTE: pdfStream is a memory stream. Position=0 has already been set.
The same code works for the file "https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/db/77/ymj-47-432.PMC2688166.pdf"

```
public string GetPDFText(Stream pdfStream)
        {
            StringBuilder stringBuilder = new StringBuilder();
            var pageCount = 0;
            using (PdfDocument document = PdfDocument.Open(pdfStream))
            {
                var pages = document.GetPages();
                foreach (Page page in pages)
                {
                    string pageText = page.Text;
                    stringBuilder.Append(" " + pageText);
                    pageCount++;
                }
            }
            return stringBuilder.ToString(); 
        }
```

**Comment by EliotJones** [comment]
@khanshahan I've pushed a potential fix for this that should be available in the nightly build

**Comment by khanshahan** [comment]
Thank you Elliot.

**Comment by khanshahan** [comment]
I can confirm, this ticket is fixed in the alpha builds
