### ISSUE TITLE
MediaBox clipped to IntRectangle

### ISSUE THREAD

**Issue by SitAnko** [UglyToad/PdfPig#450]
In Parser\PageFactory.cs the media-box gets clipped to int values: **mediaBox = new MediaBox(mediaboxArray.ToIntRectangle(pdfScanner))**.
In real-life files, MediaBox values are not always integers.
An easy fix would be to use ToRectangle() instead of ToIntRectangle():
**mediaBox = new MediaBox(mediaboxArray.ToRectangle(pdfScanner))**.

**Comment by EliotJones** [comment]
Not planned though you're welcome to make a PR
