### ISSUE TITLE
overload for NearestNeighbourWordExtractor shown in advanced example is private

### ISSUE THREAD

**Issue by jeanfrancoislarente** [UglyToad/PdfPig#461]
I'm trying to follow the example provided [here](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#nearest-neighbour-method) and I get a compilation that no overload method takes two arguments. The method is marked as private.

Please let me know if I'm doing something wrong, thanks!

**Comment by BobLd** [comment]
which example are you trying for Nearest Neighbour method? The simplace case or the advances one? Which method throws an error?

**Comment by jeanfrancoislarente** [comment]
Advanced case. I copied the example in and the overload is private

![image](https://user-images.githubusercontent.com/5884676/171905246-d7b94fa5-eebd-496d-8d50-cb8b46ea5757.png)

**Comment by BobLd** [comment]
Please do as follow (there were breaking changes introduced in the last version, you now need to pass the options in the contructor, same will apply to other Document Layout Analysis extractors):
```csharp
using UglyToad.PdfPig;
using UglyToad.PdfPig.DocumentLayoutAnalysis.WordExtractor;

using (var document = PdfDocument.Open(@"document.pdf"))
{
	string[] punctuation = new[] { ".", "," };
	string[] cannotStartWord = new[] { ")", "]", "!", "?", ";", ":" };
	string[] cannotEndWord = new[] { "(", "[" };

	for (var i = 0; i < document.NumberOfPages; i++)
	{
		var page = document.GetPage(i + 1);

		var nnOptions = new NearestNeighbourWordExtractor.NearestNeighbourWordExtractorOptions()
		{
			// Ignore the letters that are space or belong to 'punctuation' array
			// These letters will be put in a single word
			FilterPivot = letter => !string.IsNullOrWhiteSpace(letter.Value) &&
				!punctuation.Contains(letter.Value),

			Filter = (pivot, candidate) =>
			{
				if (string.IsNullOrWhiteSpace(candidate.Value) ||
					cannotEndWord.Contains(candidate.Value))
				{
					// start new word if the candidate neighbour is 
					// a space or belongs to 'cannotEndWord' array
					return false;
				}
				else if (cannotStartWord.Contains(pivot.Value))
				{
					// end word if pivot belongs to 'cannotStartWord' array
					return false;
				}
				return true;
			}
		};

		var nnWordExtracor = new NearestNeighbourWordExtractor(nnOptions);

		var words = nnWordExtracor.GetWords(page.Letters);

		foreach (var word in words)
		{
			// Do something
		}
	}
}
```

I've updated the wiki for this case, will need to update the other when I have time

**Comment by jeanfrancoislarente** [comment]
Awesome thanks!! I did close to that (just put the options initalization inside the new NearestNeighbourWordExtractor).

I'm new to this library, and without asking for handholding, wondering if you would know of any resources that could help me parse the following (headings following by words directly below them) - shot in the dark, if you don't know of any - no worries - thanks for the incredibly quick turnaround - aside from this latest question - case closed!

![image](https://user-images.githubusercontent.com/5884676/171906619-c8a7b269-7a7a-4b2b-a849-3709d06ecbbb.png)

**Comment by BobLd** [comment]
@jeanfrancoislarente no problem! I think you will have to create an ad-hoc logic for your case, since it a very particular layout.

You can take a look at [tabula-sharp](https://github.com/BobLd/tabula-sharp) which is a table extraction library using pdfpig. It might no really work as your case is not really a table...

**Comment by jeanfrancoislarente** [comment]
Will try - thanks!
