### ISSUE TITLE
The cm operator must pass 6 numbers. Instead got: System.Decimal[]

### ISSUE THREAD

**Issue by tuohaibei** [UglyToad/PdfPig#467]
When i read the pdf,it have the error message,could you please have a check?

**The cm operator must pass 6 numbers. Instead got: System.Decimal[]**

i use nuget package:
https://www.nuget.org/packages/PdfPig/0.1.7-alpha-20220622-fc71a

[973.pdf](https://github.com/UglyToad/PdfPig/files/9015672/973.pdf)

**Comment by EliotJones** [comment]
I've pushed a fix for this which should be included in tonight's pre-release. The file is corrupted/broken for certain pages due to invalid content, I have implemented a workaround for this.
