### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name

### ISSUE THREAD

**Issue by tuohaibei** [UglyToad/PdfPig#468]
When I read the following pdf,it have the error message,could you help to check,
**System.ArgumentOutOfRangeException:“Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name”**

I use nuget package:
https://www.nuget.org/packages/PdfPig/0.1.7-alpha-20220622-fc71a

the pdf is over 25M,i coule not upload it.If you want to the pdf,could you tell me how i send you the file?

**Comment by EliotJones** [comment]
Hi @tuohaibei does compressing the file enable it to be uploaded as a ZIP/tarball?

**Comment by EliotJones** [comment]
If you still want us to look you can also mail the file to pdfpig@outlook.com. Closing based on lack of response
