### ISSUE TITLE
read pdf landscape

### ISSUE THREAD

**Issue by joanfercho** [UglyToad/PdfPig#470]
hello good morning, I like your bookstore but I don't know how to read a pdf horizontally, since currently it reads vertically and I have a document that I need to read horizontally, if you could help me I would be grateful, since they are not always in order.
[documento para mostrar.pdf](https://github.com/UglyToad/PdfPig/files/9111646/documento.para.mostrar.pdf)
.

**Comment by EliotJones** [comment]
Sorry this is out of scope of the support we're able to offer. Try looking into layout analysis tools for documents with non-standard layouts https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis
