### ISSUE TITLE
Duplicating words

### ISSUE THREAD

**Issue by Smurfj3** [UglyToad/PdfPig#471]
Hello,

I noticed in the extracted words there is a few words that are duplicated for some odd reason. At first I thought it had to do with the process of turning the letters into words but that is not the issue. I can tell they are already duplicated from the moment I check the Page.Letters, so before I use NearestNeighbourWordExtractor.GetWords(,, ,,). It's odd because not all words do it but some duplicate like 4 times.

I am aware I can solve the duplications by just deleting all doubles but for my use case I cannot do that, because if a word does in fact appear multiple times on the PDF, then I want to keep those. The ones that are duplicating right now, only appear on the PDF 1 time, but PdfPig seems to think it's there multiple times.

Anyone know what could be causing this?

**Comment by InusualZ** [comment]
Hello,

The most likely case is that, the producer of the pdf document write the same text twice to emboss (**bold**) the text. But it could also be a bug. Can you provide the pdf?

**Comment by Smurfj3** [comment]
Hello Wesley,

You must be right, it is because of the bold font. I didn't think of that,
I think I might be able to fix that by coding something that checks
distance between letters etc.

Thank you for your e-mail.

Jeffrey

**Comment by BobLd** [comment]
before writting code, can you check if the following does the job for you?
https://github.com/UglyToad/PdfPig/blob/c74ca5fda8a51f3af9cf19c675272f57d3beee60/src/UglyToad.PdfPig.DocumentLayoutAnalysis/DuplicateOverlappingTextProcessor.cs

It's supposed to handle this kind of case

**Comment by Smurfj3** [comment]
Oh that works perfectly, thank you. I have only tested it on 1 case though,
I will be doing a couple of 100 over the next few days but so far so good!

**Comment by BobLd** [comment]
@Smurfj3 I'm going to mark this issue as closed - feel free to reopen it if you see case where [`DuplicateOverlappingTextProcessor.cs`](https://github.com/UglyToad/PdfPig/blob/c74ca5fda8a51f3af9cf19c675272f57d3beee60/src/UglyToad.PdfPig.DocumentLayoutAnalysis/DuplicateOverlappingTextProcessor.cs) does not work
