### ISSUE TITLE
Last version reads as first page the last page of document

### ISSUE THREAD

**Issue by grinay** [UglyToad/PdfPig#472]
I have one exactly document , which when I start reading  
using var pigPdf = PdfDocument.Open(file);
foreach (var pigPage in pigPdf.GetPages())

as a first page it read the last page of document. 
I downgrade version to 0.1.5 and it reads everything correct. 
I can't provide you that document unfortunately it's under NDA.
Would it be possible to check what is the possible reason for that?

**Comment by grinay** [comment]
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/13212299/181680715-098f7a2a-61b5-436d-b79c-367e9452d97c.png">
This commit is doing, that after rollback branch before that commit, pages are read correctly,

**Comment by grinay** [comment]
@EliotJones please review PR. https://github.com/UglyToad/PdfPig/pull/473

**Comment by Hert79** [comment]
I have seen almost the same issue in about a dozen documents so far, (incidentally all under copyright protection). Not just the last page being read first, but the general page order being scrambled. Downgrading also fixes the issue.

**Comment by EliotJones** [comment]
@Hert79 and @grinay does the version containing the fix in PR #473 fix the issue? That should be in this release https://www.nuget.org/packages/PdfPig/0.1.7-alpha-20220814-2f9a9

**Comment by Hert79** [comment]
> @Hert79 and @grinay does the version containing the fix in PR #473 fix the issue? That should be in this release https://www.nuget.org/packages/PdfPig/0.1.7-alpha-20220814-2f9a9

For me, the issue is solved. Tested on multiple docs, all fine now.
