### ISSUE TITLE
Letter width calculation incorrect, possibly due to Tz operator

### ISSUE THREAD

**Issue by massonib** [UglyToad/PdfPig#475]
![image](https://user-images.githubusercontent.com/12925670/182646683-c2b1a94c-800c-4c2c-9d72-a08e5e3b161f.png)
![image](https://user-images.githubusercontent.com/12925670/182646744-53a0b5a8-95c5-436c-ab27-505603b363e6.png)

In these examples, I am drawing a box around the Letter's glyph rectangle, but it does not line up with the actual text of the PDF. Horizontal Scaling (Tz) is being using a lot within this document, but PDFPig seems to rebuild the document fine as shown in the image. The letter's font says it is "QYVNFR+CourierNewPSMT", but I am pretty sure it is supposed to be Arial MT - so this is likely the issue. 

From the pdf stream:
11 0 obj
<</Ascent 1021 /CapHeight 571 /Descent -680 /Flags 34 /FontBBox [ -122 -680 623 1021 ] /FontFamily (Courier New) /FontFile2 10 0 R /FontName /QYVNFR+CourierNewPSMT /FontStretch /Normal /FontWeight 400 /ItalicAngle 0 /StemV 40 /Type /FontDescriptor /XHeight 423 >>
endobj
12 0 obj
<</BaseFont /QYVNFR+CourierNewPSMT /Encoding /WinAnsiEncoding /FirstChar 0 /FontDescriptor 11 0 R /LastChar 255 /Subtype /TrueType /Type /Font /Widths [ _...numbers..._ ] >>
endobj
13 0 obj
<</Ascent 905 /CapHeight 716 /Descent -212 /Flags 32 /FontBBox [ -665 -325 2000 1040 ] /FontFamily (Arial) /FontName /Arial /FontWeight 400 /ItalicAngle 0 /StemV 0 /Type /FontDescriptor >>
endobj
14 0 obj
<</BaseFont /Arial /Encoding /WinAnsiEncoding /FirstChar 32 /FontDescriptor 13 0 R /LastChar 121 /Subtype /TrueType /Type /Font /Widths [ _...numbers..._  ] >>
endobj

I cannot share this document unfortunately, but the commands leading up to the first placement of text with the error are:

0.454545 0 0 0.454545 75.272728 36 cm
BT
111.1111 Tz
Neither Tr
/F0 1 Tf
17.688 0 0 17.688 2248.8 6.586 Tm
122.2222 Tz
9.36 0 0 9.36 29.6 110.8 Tm
TEXT WITH ISSUE EXTRA WIDE Tj
88.8889 Tz
-0.14 -1.8 Td (move to next line)
TEXT NOT QUITE AS WIDE, BUT STILL WITH ISSUE Tj
ET

There are no Tc or Tw operations in use.

                var page = document.GetPages().First();
                PdfDocumentBuilder builder = new PdfDocumentBuilder();
                PdfPageBuilder newPage = builder.AddPage(document, 1);
                newPage.SelectContentStream(0);
                newPage.NewContentStreamBefore();
                newPage.SetStrokeColor(255, 0, 0);
                foreach (var letter in page.Letters)
                {
                    newPage.DrawRectangle(letter.GlyphRectangle.BottomLeft, (decimal)letter.GlyphRectangle.Width, 
                                  (decimal)letter.GlyphRectangle.Height, 1, false);
                }
                File.WriteAllBytes(@"D:\Desktop\Drawings\PdfPigTest.pdf", builder.Build());

**Comment by EliotJones** [comment]
Unfortunately without access to the source document I don't think it's going to be possible to resolve this. Sorry for the issue
