### ISSUE TITLE
Load pdf from memorystream

### ISSUE THREAD

**Issue by Gerardo-Sista** [UglyToad/PdfPig#476]
Hello,
I need PdfPig to open a pdf file from memorystream.
I tried with 

`using var stream = file.OpenReadStream();
            using var ms = new MemoryStream();
            await stream.CopyToAsync(ms);
using (PdfDocument document = PdfDocument.Open(ms))
                {
                    foreach (UglyToad.PdfPig.Content.Page page in document.GetPages())
                    {
                        string pageText = page.Text;

                        foreach (Word word in page.GetWords())
                        {
                            Console.WriteLine(word.Text);
                        }
                    }
                }`

but it always gives this error:
UglyToad.PdfPig.Core.PdfDocumentFormatException: 'Could not find the version header comment at the start of the document.'

If I load the same file from path it works good.

Any help?

Thank you

**Comment by EliotJones** [comment]
I think the `MemoryStream` you're passing might be at the end of stream, I'm not sure but can you try calling `ms.Seek(0, Begin)` or whatever the call is before passing to `Open` and see if that has any effect?

**Comment by Gerardo-Sista** [comment]
@EliotJones it works like a charm!. Thank you :)
