### ISSUE TITLE
get  chinese string error

### ISSUE THREAD

**Issue by namemyself** [UglyToad/PdfPig#477]
Hi,I have one problem,look for your help:
my code and result as:
![image](https://user-images.githubusercontent.com/11289772/183043917-c914e615-c51f-4f15-9c1c-8983189bd1e2.png)
this is the test pdf: [aaa.pdf](https://github.com/UglyToad/PdfPig/files/9267212/aaa.pdf)

**Comment by namemyself** [comment]
anyone here????

**Comment by namemyself** [comment]
i really need to solve this problem

**Comment by smliebear** [comment]
If you just need to get the text content, you don't need the second loop. I suggest you try it

**Comment by namemyself** [comment]
> If you just need to get the text content, you don't need the second loop. I suggest you try it

but I want to get the coordinates of each character

**Comment by namemyself** [comment]
![image](https://user-images.githubusercontent.com/11289772/186592545-a5e515a3-5ec2-4b4f-85ec-75c6c63078eb.png)

**Comment by namemyself** [comment]
It happens too often

**Comment by smliebear** [comment]
Maybe you can write it this way. Pdfpig has an example
![image](https://user-images.githubusercontent.com/59463841/186592928-9e2c2496-a851-4d84-8ae0-01e606a4ebca.png)

**Comment by namemyself** [comment]
> Maybe you can write it this way. Pdfpig has an example ![image](https://user-images.githubusercontent.com/59463841/186592928-9e2c2496-a851-4d84-8ae0-01e606a4ebca.png)

thankyou ,i try it

**Comment by namemyself** [comment]
> > Maybe you can write it this way. Pdfpig has an example ![image](https://user-images.githubusercontent.com/59463841/186592928-9e2c2496-a851-4d84-8ae0-01e606a4ebca.png)
> 
> thankyou ,i try it

the test pdf donot work,why?
![image](https://user-images.githubusercontent.com/11289772/186603004-a776f703-d4a5-4c99-8aa2-80ff186c2365.png)

**Comment by smliebear** [comment]
I think it's a coding problem, because it's like our usual random code

**Comment by namemyself** [comment]
> I think it's a coding problem, because it's like our usual random code

yes,i use mupdf to get all string ,work normal。i think this is a bug,if some one can solve this problem,please tell me......thank

**Comment by EliotJones** [comment]
Not really sure what's going on here and won't have time to fix, sorry
