### ISSUE TITLE
How to extend library with new languages like Arabic?

### ISSUE THREAD

**Issue by saadahmedkhan** [UglyToad/PdfPig#479]
Hi, the library works perfectly fine for English PDFs. However, we are trying to convert Arabic PDFs as well. We noticed that the characters order is reversed for each word so we used Bidi methodology to fix that. But now we notice some characters still not being converted properly.

Is there any way we can extend or add Arabic language?

**Comment by EliotJones** [comment]
Do you have an example file demonstrating the issue?
