### ISSUE TITLE
about paddocument.open(string,password)

### ISSUE THREAD

**Issue by smliebear** [UglyToad/PdfPig#480]
`When I use the PdfDocument.Open(string,password)，In this using, the foreach loop cannot run.It tell me "This is the next statement to be executed when the thread returns from the current function."but i use PdfDocument.Open(string).It can run.
![image](https://user-images.githubusercontent.com/59463841/186378933-72001832-bc15-47c1-9e19-4f9a965dfe28.png)

**Comment by EliotJones** [comment]
Do you have an example document where this fails? It's not going to be possible to resolve without one
