### ISSUE TITLE
Exception: Expected the XObject dictionary value for key /thumbnail_background_Page_0 to be an indirect reference, instead got: null.

### ISSUE THREAD

**Issue by khanshahan** [UglyToad/PdfPig#481]
Hi,

I am trying to read the file `https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/08/09/jc11561639.PMC2289205.pdf` but I am getting an exception "Expected the XObject dictionary value for key /thumbnail_background_Page_0 to be an indirect reference, instead got: null.".

The error is encountered when going through Pages.

I am using Nuget package 0.1.7-alpha-20220814-2f9a9
.NET 6.0

I am using the following code (The problem seems to be associated with the images page):
NOTE: pdfStream is a memory stream. Position=0 has already been set.
The same code works for the file "https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/db/77/ymj-47-432.PMC2688166.pdf"

```
        public string GetPDFText(Stream pdfStream)
        {
            StringBuilder stringBuilder = new StringBuilder();
            var pageCount = 0;
            
            using (PdfDocument document = PdfDocument.Open(pdfStream))
            {
                var pages = document.GetPages();
                foreach (Page page in pages)
                {
                    string pageText = page.Text;
                    stringBuilder.Append(" " + pageText);
                    pageCount++;
                }
            }
            return stringBuilder.ToString(); 
        }

```

**Comment by EliotJones** [comment]
From the linked commit this should be fixed in the latest nightly/pre-release builds
