### ISSUE TITLE
Exception: Could not find the font with name /T1_4 in the resource store. It has not been loaded yet.

### ISSUE THREAD

**Issue by khanshahan** [UglyToad/PdfPig#482]
Hi,
I apologise for creating so many tickets, I just felt it will be good idea to report as I am processing different pdfs.

I am trying to read the file `https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/71/d3/mt2009176a.PMC2835024.pdf `but I am getting an exception "Could not find the font with name /T1_4 in the resource store. It has not been loaded yet.".

I am using Nuget package 0.1.7-alpha-20220814-2f9a9
.NET 6.0

I am using the following code:
NOTE: pdfStream is a memory stream. Position=0 has already been set.
The same code works for the file "https://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_pdf/db/77/ymj-47-432.PMC2688166.pdf"

```
        public string GetPDFText(Stream pdfStream)
        {
            StringBuilder stringBuilder = new StringBuilder();
            var pageCount = 0;
            
            using (PdfDocument document = PdfDocument.Open(pdfStream))
            {
                var pages = document.GetPages();
                foreach (Page page in pages)
                {
                    string pageText = page.Text;
                    stringBuilder.Append(" " + pageText);
                    pageCount++;
                }
            }
            return stringBuilder.ToString(); 
        }

```

**Comment by EliotJones** [comment]
From the linked commit there should be a change which allows ignoring the corrupted file in this case by passing `SkipMissingFonts` in the parsing options when opening a file
