### ISSUE TITLE
We need source code of pdfpig liabraries like - header, footer custom tables, formatted text etc.

### ISSUE THREAD

**Issue by mukeshanand123** [UglyToad/PdfPig#488]
"https://github.com/UglyToad/PdfPig"
I am using above pdfpig library to generate pdf document, but we can not find any types of example which is related to generated bill , invoice , custom tables, header, footers etc.

Please provide some link url which is helpful for me.

Thanks in Advance
Mukesh

**Comment by EliotJones** [comment]
This is very much outside the scope of this library. It's something more commercial solutions are likely to provide for example https://products.aspose.com/pdf/net/
