### ISSUE TITLE
Type3 font has no height

### ISSUE THREAD

**Issue by grinay** [UglyToad/PdfPig#500]
Hi Guys. I have bunch of documents to process, which were originally converted to PDF format by customer. However what I see is that bounding boxes of letters are not correct and has 0 height. I debug it and  noticed, that document defines type3 font and  class Type3Font defines 0 height rectangle for this font type. I may understand why that it is in theory. My question is that would it be possible to use fallback to bounding box , something like that ?
```
private PdfRectangle GetBoundingBoxInGlyphSpace(int characterCode)
        {
            if (characterCode < firstChar || characterCode > lastChar)
            {
                throw new InvalidFontFormatException(
                    $"The character code was not contained in the widths array: {characterCode}.");
            }

            var scale = widths[characterCode - firstChar] / this.boundingBox.Width;
            return new PdfRectangle(0, 0, widths[characterCode - firstChar], boundingBox.Height * scale);
        }
```

Would it be correct usage? In my case text bounding boxes look pretty good after such fix. Please advice.

**Comment by Hert79** [comment]
I think I am seeing the same issue. Letters on attached page also have height 0.
PdfBox does give the correct height for these letters.
[ZeroHeightLetters.pdf](https://github.com/UglyToad/PdfPig/files/10111106/ZeroHeightLetters.pdf)

**Comment by EliotJones** [comment]
May be linked to #501 . Full fix is to parse the postscript path and calculate bounding box. Short term fix could use default bounding box. Needs research.

**Comment by Hert79** [comment]
> I think I am seeing the same issue. Letters on attached page also have height 0. PdfBox does give the correct height for these letters. [ZeroHeightLetters.pdf](https://github.com/UglyToad/PdfPig/files/10111106/ZeroHeightLetters.pdf)

Actually it looks like my problem is related to non-embedded fonts. If the font is not embedded letters using it will have height 0.

**Comment by grinay** [comment]
also found that PDFs exported from Figma font type 3 has no height. as well as bounding box has no height.For this case I'm suing pointsize as fallback. Works.

**Comment by BobLd** [comment]
@grinay can you sahre a pdf example? Will work on that soon
