### ISSUE TITLE
Save FileAttachment

### ISSUE THREAD

**Issue by EmaSciacca** [UglyToad/PdfPig#502]
Hi,

I have a pdf file with a large number of file attachments. I need to extract and save them as stand-alone files in a given directory. `TryGetEmbeddedFiles` cannot find any file, however I can visualize them with an Pdf reader software.
Is it possible to do that? I can get file attachment annotations but I cannot figure out how to save their data.

Thank you

**Comment by fnatzke** [comment]
Are you able to share the pdf?

**Comment by EliotJones** [comment]
Closing this absent a file to reproduce the problem. If you're able to provide one we can re-open

**Comment by rajanmhr47** [comment]
I am facing the same issue. I was not able to save the files from Annotation>FileAttachment. I have attached few samples here.

[pdf with comment.zip](https://github.com/UglyToad/PdfPig/files/12833294/pdf.with.comment.zip)
