### ISSUE TITLE
AES-128 Decryption Problem on some files

### ISSUE THREAD

**Issue by sfurqan2** [UglyToad/PdfPig#505]
I am splitting an existing pdf into a new pdf. I have noticed that when a file is decrypted and passed onto some pdf to text converter, it throws an error (encoding not found/ endstream not found error). The file works fine when it is not protected by password, but after encrypting it with AES-128, it starts throwing this error. (PDFPig throws no exception, but the generated pdf has these issues which did not exist in the existing pdf).

**Comment by EliotJones** [comment]
Do you have any example files to reproduce the problem?

**Comment by EliotJones** [comment]
Going to close this but will re-open if any repro is provided
