### ISSUE TITLE
Extracting the bullet points (list elements)

### ISSUE THREAD

**Issue by lelik-01** [UglyToad/PdfPig#506]
Hello everyone.

Guys, please help to extract somehow the bullet points of the list as per screen above:
![image](https://user-images.githubusercontent.com/92250857/200034881-bd379dcb-6bc6-4b4f-aff2-8a8fda19fc8f.png)
As you can see, the points are not selected as text and not extracted as text. Also they are not in the list of images.
Where can they be and how to get them and their positions?

Thanks!

**Comment by EliotJones** [comment]
If these are not embedded as characters it is possible they are path elements in the Page content. Try `page.Experimental.Paths` https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Content/Page.cs#L181
