### ISSUE TITLE
PDF/A-3

### ISSUE THREAD

**Issue by greg-cann** [UglyToad/PdfPig#513]
Hello! Are there any plans to add A3 support? I wish I could contribute to such an endeavour but would have no idea where to start, so thought I'd ask. (Feel free to close if this is not the right place to ask this)

**Comment by EliotJones** [comment]
Not realistically going to be able to address this, partly because ISO are a bunch of rent-seekers (https://www.iso.org/standard/57229.html) but also due to lack of time/contributors
