### ISSUE TITLE
PdfPig not recognizing pages

### ISSUE THREAD

**Issue by cysieks** [UglyToad/PdfPig#516]
I have a document with 18 pages, but when opening it, the PdfPig shows NumberOfPages = 0.
They exist and I can see them in the Structure.Catalog.PageTree

![pages_bug](https://user-images.githubusercontent.com/20565775/203987282-d5c186ab-7ddf-455b-aa13-b7d777073558.png)

How can I read these pages?

**Comment by fnatzke** [comment]
Are you able to provide the document?

**Comment by cysieks** [comment]
Sure, but privately.

**Comment by fnatzke** [comment]
One option send me a direct message (DM) on Twitter. 
Same handle: fnatzke.
Another option is you pick a private channel or if you want to live dangerously drop the two parts of your email in two lines here in comments (or as a screenshot).

**Comment by cysieks** [comment]
Thanks @fnatzke!

**Comment by fnatzke** [comment]
This words for your PDF but failed for other PDFs in the integration tests folder.
A slightly better solutions that passes all tests has been checked in. 
[commit](https://github.com/UglyToad/PdfPig/commit/29adece98394bd7c39705dd954607b53d206e4c0)
If url fails update is to Catalog.cs
 

`
         // <summary>
        /// Number of discovered pages.
        /// </summary>
        public int? NumberOfDiscoveredPages => pagesByNumber?.Count;
`

\src\UglyToad.PdfPig\Content\Pages.cs

after

Count = catalog.PagesDictionary.GetIntOrDefault(NameToken.Count);

change from original to 

`
           var CountOfPagesByPagesTree = catalog.PageTree.Children.Count;
            var numberOfDiscoveredPages = catalog.NumberOfDiscoveredPages;
            if (numberOfDiscoveredPages is null == false && Count != numberOfDiscoveredPages)
            {
                  Count = numberOfDiscoveredPages.Value;
            }
`

**Comment by EliotJones** [comment]
I believe @fnatzke has fixed this in the latest nightly build
