### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by Poltuu** [UglyToad/PdfPig#518]
Is it possible to get an alpha release 🙏 ?
We are heavily suffering from this bug https://github.com/UglyToad/PdfPig/pull/473

**Comment by EliotJones** [comment]
@Poltuu is this release not including this fix? https://www.nuget.org/packages/PdfPig/0.1.7-alpha-20220814-2f9a9

**Comment by Poltuu** [comment]
ah damn, I didn't see it 🤦 . thanks :)
