### ISSUE TITLE
PdfDocument.Open cannot finish execution, and the memory continues to increase.

### ISSUE THREAD

**Issue by zhangbaodan** [UglyToad/PdfPig#519]
When I open the "bug_544880.pdf" file using PdfDocument.Open, the function keeps being called, cannot finish, and the memory keeps increasing. Can anyone help me solve this problem?    The UglyToad.PdfPig version is 0.1.6
The file in question is：[bug_544880.pdf](https://github.com/UglyToad/PdfPig/files/10150216/bug_544880.pdf)

**Comment by fnatzke** [comment]
G'day @zhangbaodan 

Infinite loop parsing tokens. 

In <src>\UglyToad.PdfPig\Parser\**CatalogFactory.cs**

after 

`var current = toProcess.Dequeue();`

add

`if (current.reference.GetHashCode() == current.parentReference.GetHashCode()) { continue; }`

**Comment by zhangbaodan** [comment]
@fnatzke  Thank you very much. It seems to be working. I hope the community will put this change together and publish it soon.

**Comment by fnatzke** [comment]
Thnkas @zhangbaodan. I've checked in a revisited fix that handles your pdf as well as some others.

**Comment by EliotJones** [comment]
I believe @fnatzke has fixed this in the latest nightly build
