### ISSUE TITLE
How to extract text, hyperlinks and images in-order?

### ISSUE THREAD

**Issue by strich** [UglyToad/PdfPig#537]
I'm trying to write a tool to extract PDF content to another format (for example html), and so I need to be able to know where images fit in amongst the text as well as what parts of the text are hyperlinks.

In addition to this, I plan to be able to also extract the font size, weight, paragraphs etc.

**Comment by fnatzke** [comment]
@strich,

Can do with existing library without change.

Attached is a working solution (C# - Console App -  .net 7 - NuGet PdfPig 0.1.7)

For each page get 1) Words 2) Hyperlinks 3) Images then for each use Bounds (or BoundedBox) and use "TopLeft" to get location of item (X,Y) [ can get width and height also but not included in example solution].
 
Example solution builds dictionary of items on each page then sorts the keys and display all items sorted by Y then X.

By default solution looks for all PDFs in c:\PDFs.

[537-Locations.zip](https://github.com/UglyToad/PdfPig/files/10407999/537-Locations.zip)

**Comment by strich** [comment]
Thanks, that's a great start! A key issue I'm running into though is that ideally I'm getting whole "paragraphs". IE I can get all the contiguously same text and reconstruct it into paragraphs. I can see GetWords() is basically doing that from the letters. Sounds like I pretty monumental task to write a reconstructor. Is there no other way?

**Comment by fnatzke** [comment]
@strich,

Lots of good work has been done on Word extraction explained in this [Wiki](https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis).

These Word extraction strategies require:
    using UglyToad.PdfPig.DocumentLayoutAnalysis;

Please let me know if this helps or you need something else.
