### ISSUE TITLE
Can't use with UWP + .NET native tool chain

### ISSUE THREAD

**Issue by 0xLuca** [UglyToad/PdfPig#544]
I can build a UWP project that uses this library with Debug configuration without problems, but when i try to build it using Release the following error occurs:

`error CS0200: Property or indexer 'AltoDocument.AltoParagraphStyle.LeftSpecified' cannot be assigned to -- it is read only`

The only way to build the application in release mode is by unchecking `Compile with .NET Native tool chain` in the release configuration (which is checked by default).

**Comment by fnatzke** [comment]
@0xLuca, 

Also found could not build release version of UWP (target Windows 10 version 2004) (x86) with NuGet PdfPig 0.1.7 

I get a slightly different error in Build log:

Build started...
1>------ Build started: Project: PdfPigIssue544-DemoApp-UWP, Configuration: Release x86 ------
1>  PdfPigIssue544-DemoApp-UWP -> C:\src\PdfPig\Issues\544\PdfPigIssue544-DemoApp-UWP\bin\x86\Release\PdfPigIssue544-DemoApp-UWP.exe
1>  Processing application code
1>  Computing application closure and generating interop code
1>    Loading 100 modules...
1>    Generating code...
1>    Interop code generated.
1>  Generating serialization code
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : System.InvalidOperationException: Unable to generate a temporary class (result=1).
1>C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.12-rel-31116-00\tools\Microsoft.NetNative.targets(809,5): error : ILT0032: Failed to compile serialization code. See the build log for error details.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Elapsed 00:58.010 ==========

![Issue544-BuildError-Screenshot](https://user-images.githubusercontent.com/15922731/215997386-c42aab0f-3d56-4630-bff3-fe1e8619134b.png)

Will work on tomorrow.

**Comment by fnatzke** [comment]
@0xLuca 
see earlier closed issue #379 which had this solution ( haven’t had a chance to test):

 I had the same issue, and was able to resolve it by adding the following line to the Application element in my project's Runtime Directive (.rd.xml) file:

<Assembly Name="UglyToad.PdfPig.DocumentLayoutAnalysis" Dynamic="Auto" />


[Source](https://github.com/UglyToad/PdfPig/issues/379#issuecomment-1086274380)

**Comment by fnatzke** [comment]
@0xLuca,

Confirming with that change:

Modify
<App>/Properties/Default.rd.xml

![Issue544-Fix-DefaultRdXml-File-Navigation](https://user-images.githubusercontent.com/15922731/216285491-0b7aeb80-9545-4bed-85b6-568ec9be0689.png)

Add single line:

`<Assembly Name="UglyToad.PdfPig.DocumentLayoutAnalysis" Dynamic="Auto" /> `

![Issue544-Fix](https://user-images.githubusercontent.com/15922731/216285530-9e023e8b-6e0a-4934-b97b-151e756a8f71.png)

Now have a successful UWP build.

**Comment by EliotJones** [comment]
Thanks for the answer here. I'll close the issue for now since it appears fixed by the change suggested. I'm not sure if there's something we can include in the NuGet package to make this change automatic but I'm not familiar with the UWP toolchain to know.
