### ISSUE TITLE
Error while parsing font in corrupted pdf

### ISSUE THREAD

**Issue by KleifaHH** [UglyToad/PdfPig#548]
Hello,

we have an pdf which we can open in Acrobat Reader, but when we try open with PdfPig we got the error:

```
Cannot convert a block padded by 4 'u' characters. Arg_ParamName_Name
   bei UglyToad.PdfPig.Filters.Ascii85Filter.WriteData(Byte[] ascii, Int32 index, BinaryWriter writer)
   bei UglyToad.PdfPig.Filters.Ascii85Filter.Decode(IReadOnlyList`1 input, DictionaryToken streamDictionary, Int32 filterIndex)
   bei UglyToad.PdfPig.PdfExtensions.Decode(StreamToken stream, ILookupFilterProvider filterProvider, IPdfTokenScanner scanner)
   bei UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, InternalParsingOptions parsingOptions)
   bei UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber, InternalParsingOptions parsingOptions)
   bei UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber)
   bei UglyToad.PdfPig.PdfDocument.<GetPages>d__30.MoveNext()
```

We analyzed the document with Acrobat and found this corruption:

<img width="457" alt="Adobe" src="https://user-images.githubusercontent.com/125445967/218979059-533805fd-c681-4788-bb25-ea3764a5cb47.png">

Would it be possible for PdfPig to ingore/ fix this problem?

Thank you very much

**Comment by fnatzke** [comment]
@KleifaHH it is possible.  The exception seems to occur when decoding a page (content stream) (using Ascii85Filter). Depending on where in the decode it happends it may be possible to recover and obtain the majority of the page however at the least could present a "blank page" for this page.

Interestingly from your tree layout screeshot of the PDF it seems to indicate it is within a TruType font.

Are you able to share an example PDF that that generates this exception?

**Comment by KleifaHH** [comment]
We can only provide the original PDF if you sign an NDA...

Of course,  we can provide any other information you need.

**Comment by fnatzke** [comment]
That’s fine.
My email is the same handle (fnatzke) at hotmail.com.

**Comment by fnatzke** [comment]
If this is still an issue happy to sign NDA.

Alternatively I can send a code for a tool which you can compile and run that will copy out one page (perhaps with non sensitive details) that has the error.

a other alternative is a tool to extract all the fonts on the page in question (so no page content) for reproducing the issue in a (blank) PDF based on the font export from my end.

**Comment by KleifaHH** [comment]
Hi, 
it is still an issue. All the PDF pages contains senstive informations. 
At the moment the NDA is no option, we do not get the permission (in time).

So the tool to extract the fonts would be great!

**Comment by EliotJones** [comment]
Hi @KleifaHH unfortunately we're not going to be able to make much progress here without an original document. I hope you were able to find a library that could handle this corrupted file in a more resilient manner for your needs.
