### ISSUE TITLE
Adding a specific PNG to a PDF causes the PDF to be invalid

### ISSUE THREAD

**Issue by cremor** [UglyToad/PdfPig#550]
If you add [this](https://user-images.githubusercontent.com/116314/219009895-937bd4a8-9969-4be0-b354-a41919917d9f.png) PNG with `PdfPageBuilder.AddPng()` to a PDF then the resulting PDF can't be shown in Adobe Acrobat Reader. Adobe then shows an error message box about a graphics error and the page is empty.

**Comment by fnatzke** [comment]
@cremor, Can reproduce your issue.  The Adoube Acrobat Reader pop-up message I get is: "A drawing error occurred.". Opens and renders fine in Chrome (without error). Looking further tomorrow.

**Comment by cremor** [comment]
Thanks for your analysis. I think it's not just a bug in Adobe Acrobat Reader because the application Wondershare PDFelement also behaves weird with it. While it can show the image in the PDF initially, it will have various rendering errors in the PDF after you edit the file with Wondershare PDFelement.

That could also be a bug in Wondershare PDFelement, but I think the chance that the PDF is malformed is higher since two completely separate applications have problems with it.

**Comment by fnatzke** [comment]
I'll keep looking. For Adobe I couldn’t find a log file , kb article or hint to the reason. There isn’t anything obvious that stands out in the PdfPig code. I’ll give Wondershare a go. I’m also get a collection of (different) PNGs to try to see if can reproduce to see if there is a common properties that cause.

**Comment by cremor** [comment]
Another hint: If you open the PNG in Paint and just resave it as PNG then the bug doesn't happen. I don't know enough about PNGs to check for differences, but it seems like the way the original file was saved differes from the way that Paint saves PNGs.

**Comment by fnatzke** [comment]
That is interesting. Paint usually saves withOUT the alpha channel. I had that on my todo (mod lib code to drop alpha (smash) as a test) but I’ll put as the next thing to try. Thank you.

**Comment by fnatzke** [comment]
Have what looks to be a fix (still pending full test suite).

In src/src/UglyToad.PdfPig/Writer/PdfPageBuilder.c Line 686:

https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig/Writer/PdfPageBuilder.cs#L686


Change  "png.Header.BitDepth" 
       {NameToken.BitsPerComponent, new NumericToken(png.Header.BitDepth)}, 
to "8"
       {NameToken.BitsPerComponent, new NumericToken(8)},  


![image](https://user-images.githubusercontent.com/15922731/219829855-03c71ccd-0844-42af-aa4e-62c78e06d0ed.png)

to
![FixedLineScreenshot](https://user-images.githubusercontent.com/15922731/219829908-effde0fa-5ddc-4f9e-8d91-36fe2afb256b.png)


What starts giving it away is that the colour of the image in the PDF is different ("brown" (PDF) vs "purple" (PNG)) and the image is "duplicated" (left and right).

Screenshot of image from PDF:
![1-Pdf-ColourMismatch-16bit](https://user-images.githubusercontent.com/15922731/219830175-c2579c73-643e-47aa-9c73-0813861baf01.png)

Original:
![219009895-937bd4a8-9969-4be0-b354-a41919917d9f](https://user-images.githubusercontent.com/15922731/219830187-8917fecf-686e-4921-ab28-406d37b622ac.png)

The 16bit (2 byte) values for the pixels (R,G,B) from the PNG are reduced to 8 bit (1 byte) to generate a replacement PNG for adding to the PDF.

The one line fix is the hardcode 8 as the "BitsPerCompoent" in (metadata) (XObjectImage StreamDictionary) for the (replacement) PNG that ends up in PDF.

A (far) more complex fix would be to retain the 16 bit precision but this involved having "Pixel" class (in the PdfPig library) accept R,G,B components with values > 8 bits.

Separately Wondershare didn't seem to produce any errors for me and behaved like Chrome.
![2-Wondershare-Screenshot-BeforeFix](https://user-images.githubusercontent.com/15922731/219830600-4b85b80a-d432-46ae-bdf4-7b98a2699a9e.png)

Screenshots after fix:
![3-AdobeScreenshotAfterFix](https://user-images.githubusercontent.com/15922731/219830608-c8b4e455-2d4e-4a42-a4e5-6039a37d6a5c.png)
![4-ChromeAfterFix](https://user-images.githubusercontent.com/15922731/219830611-d555caf0-7604-4ff0-8a54-c5ac054a466c.png)
![5-WondershareAfterFix](https://user-images.githubusercontent.com/15922731/219830620-2ea5e96c-feb2-425f-9944-07c3f2a1b141.png)


Use with caution. Preliminary fix. Lots of test yet to do. May break other PNGs. Should know by tomorrow.

**Comment by cremor** [comment]
I can confirm that this is fixed in 0.1.8-alpha-20230320-c024e, thanks.
