### ISSUE TITLE
PDFDocument.Open issue in request process in web environment

### ISSUE THREAD

**Issue by AhmetAtasagun** [UglyToad/PdfPig#564]
Hi

When I try to open the pdf file that I captured with the IFormFile object as PDFDocument.Open(path), I get the following error;

![NofileExistError](https://user-images.githubusercontent.com/47632025/224936383-5d2a3ca8-6dcd-4ad1-a59b-d567200ae3f3.jpeg)

Differently, when I try to open the pdf file that I captured with the IFormFile object as PDFDocument.Open(stream), I get the following error;

![notfindversionheader1](https://user-images.githubusercontent.com/47632025/224936457-90f478c2-3b84-4fe3-ad44-4c560aa8721a.jpeg)
![notfindversionheader2](https://user-images.githubusercontent.com/47632025/224936485-80477b34-35d3-4b6e-9780-a47335f83145.jpeg)

I was able to solve it like this;
It worked when I saved the PDF file from a location and read it from the location. With another method, it also worked when I converted the stream to an array as seen in the picture below.

![solved](https://user-images.githubusercontent.com/47632025/224937559-9fd61690-adfc-4491-b274-c99e56cf8f7c.jpeg)

I think there is a problem with PDFDocument.Open(...) stream and file path overloads.
For your information...

**Comment by mvantzet** [comment]
Hi Ahmet,
In case #1 you are trying to open the file from disk using the Filename property, but there is no actual file found on disk; which I would also expect until you explicitly save it from the request.
In case #2 you are turning the filename into a byte[], not the actual file contents, so it is trying to parse the filename as a PDF.
In case #3 you are correctly using the stream.

**Comment by EliotJones** [comment]
Thanks for the answers here @mvantzet and @BobLd. I think I'll leave streams as-is for now. While we could internally transform them to `MemoryStream`s internally to make it more user friendly `Stream` is intended to be the more 'advanced' API for people to work with inputs that may not necessarily fit in memory, I don't particularly want us to have to do the work of correcting the API usage but probably could be improved with documentation.
