### ISSUE TITLE
Drop shadow text is extracted in duplicate giving garbled text

### ISSUE THREAD

**Issue by mvantzet** [UglyToad/PdfPig#568]
Some packages export drop shadow text as regular text, with the same text offset a bit with added transparency and/or in a lighter color. 
In essence text is present twice and with PdfPig we get both the regular text and the shadow text back. It mixes the shadow letters with the regular letters, giving garbled text. I have a PDF that was exported from Visio that exhibits this issue but I am not able to share it here unfortunately.

**Comment by BobLd** [comment]
Hi @mvantzet, can you have a look at #542? I think it's a similar issue and show how to fix that here. Let me know if it's a different issue
