### ISSUE TITLE
Recent 0.1.8-alpha update broke adding PNGs with transparency to a PDF

### ISSUE THREAD

**Issue by cremor** [UglyToad/PdfPig#576]
It seems like package version 0.1.8-alpha-20230318-a5c91 broke adding PNGs with transparency to a PDF. The images are not shown correctly in the created PDF.

The last working package version was 0.1.8-alpha-20230219-999f9, so it was one of those changes: https://github.com/UglyToad/PdfPig/compare/999f9ee..a5c91f0

The most likely candidate is #556 by @fnatzke 

Sample images:
https://user-images.githubusercontent.com/116314/227136578-db67736d-0fba-41fa-92a9-34c7be04a9bf.png
https://user-images.githubusercontent.com/116314/227136593-fa04975e-686c-4a69-ba55-a3ec57bcbe62.png

This is how the first sample image looks in the PDF:
![grafik](https://user-images.githubusercontent.com/116314/227137170-cf203229-660f-4ca7-a9c1-f5a9e4aeb7c4.png)

**Comment by fnatzke** [comment]
Very happy to look at this if it is unsolved in the morning (+9 for me).
