### ISSUE TITLE
Getting text containing multiple words from a page

### ISSUE THREAD

**Issue by Kakolukia91** [UglyToad/PdfPig#581]
Hello.

This is more a question than an issue.

I can see that I can get the list of words within a page. Is there a way to get text made up of multiple words? For example say the PDF page contains the following:
`NEXT LOCATION`

I'm able to get the list of words, `NEXT` and `LOCATION`, but is there a way to get the text block itself (rather than the whole page text)?

Hope I'm making sense :)

Thanks.

**Comment by BobLd** [comment]
Have a look here: https://github.com/UglyToad/PdfPig/wiki/Document-Layout-Analysis#docstrum-for-bounding-boxes-method

you should get Paragraphs and lines

**Comment by Kakolukia91** [comment]
Thanks, that sorts it out :)

Got another question about paths, but I'll open another issue for it.

Thanks.
