### ISSUE TITLE
Extracting path details with commands and colors

### ISSUE THREAD

**Issue by Kakolukia91** [UglyToad/PdfPig#586]
Hi,

I've trying to extract path information from a PDF document, including the path fill color.

I've got a CSV file that contains path info of the PDF, so I'm trying to cross reference that with the output from PdfPig. Here's some of the data form the CSV. First column are the path details and commands, second is the path fill colour.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/ali_m/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/ali_m/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Index | Raw Text | Color
-- | -- | --
0 | 15.55 820.35 m 579.8 820.35 l 579.8 34.2 l 15.55 34.2 l h W n | 0
1 | 16.05 802.55 m 576.45 802.55 l 576.45 49.35 l 16.05 49.35 l s | 0
2 | 293.05 820.35 m 523.4 820.35 l 523.4 813.95 l 293.05 813.95 l h W n | 0
3 | 32.05 809.45 m 106.55 809.45 l 106.55 803.05 l 32.05 803.05 l h W n | 0
4 | 111.55 809.95 m 184.05 809.95 l 184.05 803.55 l 111.55 803.55 l h W   n | 0
5 | 187.3 809.45 m 417.65 809.45 l 417.65 803.05 l 187.3 803.05 l h W n | 0
6 | 401.55 809.45 m 471.55 809.45 l 471.55 803.05 l 401.55 803.05 l h W   n | 0
7 | 473.3 809.45 m 523.05 809.45 l 523.05 803.05 l 473.3 803.05 l h W n | 0
8 | 267.55 810.95 m 299.05 810.95 l 299.05 804.55 l 267.55 804.55 l h W   n | 0
9 | 17.65 800.95 m 575.55 800.95 l 575.55 771.05 l 17.65 771.05 l h W n | 0
10 | 223.45 781.95 m 277.45 781.95 l 277.45 771.05 l 223.45 771.05 l h W   n | 0
11 | 18.25 769.05 m 573.9 769.05 l 573.9 743.2 l 18.25 743.2 l s | 0
12 | 19.75 767.55 m 572.4 767.55 l 572.4 744.7 l 19.75 744.7 l h W n | 0
13 | 19.75 767.55 m 572.4 767.55 l 572.4 756.55 l 19.75 756.55 l h f | 15132390
14 | 19.75 756.55 m 572.35 756.55 l S | 15132390
15 | 194.05 767.55 m 194.05 744.7 l S | 15132390
16 | 252.75 767.55 m 252.75 744.7 l S | 15132390
17 | 386.35 767.55 m 386.35 744.75 l S | 15132390
18 | 336 767.55 m 336 744.7 l S | 15132390
19 | 293.2 767.55 m 293.2 744.75 l S | 15132390
20 | 272.8 767.55 m 272.8 744.7 l S | 15132390
21 | 235.8 767.55 m 235.8 744.7 l S | 15132390
22 | 161.85 767.55 m 161.85 744.7 l S | 15132390
23 | 70.3 767.55 m 70.3 744.7 l S | 15132390
24 | 71.65 766.15 m 159.75 766.15 l 159.75 757.65 l 71.65 757.65 l h W n | 0
25 | 167.45 766.85 m 190.2 766.85 l 190.2 758.35 l 167.45 758.35 l h W n | 0
26 | 195.45 766.85 m 234.95 766.85 l 234.95 758.35 l 195.45 758.35 l h W   n | 0
27 | 237.45 766.85 m 251.95 766.85 l 251.95 758.35 l 237.45 758.35 l h W   n | 0
28 | 254.95 766.85 m 271.45 766.85 l 271.45 758.35 l 254.95 758.35 l h W   n | 0
29 | 273.85 766.85 m 291.95 766.85 l 291.95 758.8 l 273.85 758.8 l h W n | 0
30 | 294.85 766.85 m 334.35 766.85 l 334.35 758.35 l 294.85 758.35 l h W   n | 0
31 | 337.55 766.85 m 385.45 766.85 l 385.45 758.35 l 337.55 758.35 l h W   n | 0
32 | 573.9 742.7 m 573.9 717.7 l S | 0
33 | 573.9 717.7 m 18.25 717.7 l S | 0
34 | 18.25 717.7 m 18.25 742.7 l S | 0
35 | 19.75 742.7 m 572.4 742.7 l 572.4 719.2 l 19.75 719.2 l h W n | 0
36 | 19.75 742.7 m 572.4 742.7 l 572.4 730.95 l 19.75 730.95 l h f | 15724527
37 | 101.25 742.7 m 101.25 719.2 l S | 15724527
38 | 161.85 742.7 m 161.85 719.2 l S | 15724527
39 | 19.75 730.95 m 572.35 730.95 l S | 15724527
40 | 167.45 741.45 m 236.55 741.45 l 236.55 730.95 l 167.45 730.95 l h W   n | 0

</body>

</html>

When I look at the path list from PdfPig, I can see that a path with fill color appears at index 13. But then after index 13, the fill color of remaining paths is 0, until the current path segment ends ('n' or 's' commands) and another path with `IsFilled = true` appears (index 36), and so on. My question is does that mean when I see a path that is `IsFilled = true`, the color from that path applies to the next paths until I reach the end of the path segment? This is what I see from PdfPig:
![fillColors](https://user-images.githubusercontent.com/2738626/227748750-50c1e64a-bee3-4d1e-b0e9-60b57ba16a30.png)

My next questions are regarding the commands. I think I understand them but want to verify my understanding.

When I see `W`, does that mean that the path has `IsClipping` set to true? This seems to match when I see a 'W' in the CSV file, the corresponding PdfPig path object has `IsClipping` set tot rue.

Does `s` (lowercase) mean that the path is closed with a path where `IsStroked` is set to true? Similarly, `S` (capital) does that mean we have a non-closing path with `IsStroked` set to true?

Hope my questions make sense :)

Thanks in advance.

**Comment by BobLd** [comment]
Hi @Kakolukia91, thanks for your question. For next time, as this is not an issue but more a question, can you create a discussion instead of an issue?

Regarding your question about the commands, you need to have a look a the pdf specifications here https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf, you will have all the details about clipping, stroking, filling, etc.

![image](https://user-images.githubusercontent.com/38405645/227749310-3a482c39-e771-49bf-a1be-9e0956380169.png)
![image](https://user-images.githubusercontent.com/38405645/227749316-e324f095-1163-44b7-8eeb-eaa660db3aa1.png)

> My question is does that mean when I see a path that is IsFilled = true, the color from that path applies to the next paths until I reach the end of the path segment?

This is not how it works. You are only selecting the `FillColor` in your `Select()` statement. I am pretty sure this is the reason why you are missing colors. Try selecting the Stroke color too, theese should be you missing colors

**Comment by Kakolukia91** [comment]
Thanks @BobLd . Apologies hadn't spotted the discussion tab.

Yeah I did have another collection for stroke colours, however they're all zero, which doesn't match what's on the CSV.

The pattern I'm seeing is that when a line has IsFilled set to true, it contains a fill colour, but the subsequent lines that should also have the fill colour (according to the CSV) have fill colour set to zero in PdfPig.

**Comment by BobLd** [comment]
@Kakolukia91 how was generated the csv? can you share the pdf file?

**Comment by Kakolukia91** [comment]
Hi @BobLd. Sorry for the late reply.

I'll see if I can share the relevant parts of the PDF as it contains sensitive info. The CSV has been generated by reading the PDF using another tool, however looking at the CSV generation logic I think it might be grabbing the fill color of the path and applying it to the segments.

In the meantime, a question about the commands please. Looking at the spec document I can notice several commands that I'm not sure how to deduce using the properties from PdfPig path object.

For example I can probably find out if the path has 'S', 's', 'F', 'W', 'n' operator. However, for example the 'b*' operator, would that apply if both `IsFilled` and `IsStroked` are set, `FillingRule` is set to `NonZeroWinding`, and there is a close operator for the path?

I think PdfPig Path object probably has all the info I need in order to generate the path information string I need (similar to the CSV), but just trying to see if my thinking is on the right lines.

Thanks :)

**Comment by BobLd** [comment]
@Kakolukia91 from the specs I see for **b*** operator:

> Close, fill, and then stroke the path, using the even-odd rule to determine the region to fill. This operator shall have the same effect as the sequence h B*. See also 11.7.4.4, "Special Path-Painting Considerations".

Which means that your path should have `IsFilled` and `IsStroked`, should be closed and the `FillingRule` should be set to `Even odd`

The **b** operator will do the same but with `FillingRule` set to `nonzero winding number rule`.

If you see discrepancies between what is expected and what you have in PdfPig, then there might be a bug somewhere

**Comment by Kakolukia91** [comment]
Thanks for your reply @BobLd .

I don't think there are any discrepancies, just been trying to understand how I can deduce the various path commands using the properties I get from PdfPig. I think I have a good understanding of that now.

Will post something if I find an issue.

Many thanks.
