### ISSUE TITLE
Expected name as dictionary key, instead got: Ghostscript

### ISSUE THREAD

**Issue by tincann** [UglyToad/PdfPig#59]
Hi there,

I'm trying to extract the text of a PDF generated by Ghostscript. The pdf itself seems fine, I tried to display it with a PDF viewer, which works. Also text extraction with iTextSharp seems to work. However, if I try to read the PDF with PdfPig, then I get the following exception:

> PdfDocumentFormatException: Expected name as dictionary key, instead got: Ghostscript

I've looked at the pdf source to look for references to 'Ghostscript' and found the following snippet:
```
<?xpacket end='w'?>
endstream
endobj
2 0 obj
<</Producer(GPL Ghostscript 9.25)
/CreationDate(D:20190813110636Z00'00')
/ModDate(D:20190813110636Z00'00')
/Creator(OpenText Capture Recognition Engine \(RecoStar\) 7.8.0)>>endobj
xref
```
If I set a breakpoint and inspect the tokens, this indeed seems the place where the exception occurs. It seems that the parser cannot handle this kind of syntax. I must say, I don't have enough knowledge around the PDF format to know if this syntax is allowed, but in any case it exists in the wild with documents generated by RecoStar / Ghostscript.

Do you have any advice?

**Comment by tincann** [comment]
Extra note: using the `UseLenientParsing` option does not solve the problem.

**Comment by Numpsy** [comment]
I was getting errors of that sort that turned out to be because of the bug described in #52 (those files either failed or worked depending on which APi was used to open the document)

**Comment by tincann** [comment]
Thanks for the reply @Numpsy . I can confirm that my problem is fixed when opening the pdf with a file path, instead of stream. I see that your fix has been merged, so I'll guess I'll wait for the next release.

**Comment by EliotJones** [comment]
Thanks for the bug report, I'll push out 0.0.9 this evening since 0.0.7 is already breaking consumers in the wild (0.0.8 is skipped).

**Comment by EliotJones** [comment]
When you get time would you be able to try 0.0.9 which is now on NuGet and check it fixes the issue when opening from a stream please? I've also added a bunch of test cases for opening from a stream to hopefully avoid this in future.

**Comment by tincann** [comment]
I just tested 0.0.9 and it solved my issue using the stream. @Numpsy @EliotJones Thanks a lot for the quick solution!
