### ISSUE TITLE
RTL Lang Not Supported 

### ISSUE THREAD

**Issue by alijkdkar** [UglyToad/PdfPig#594]
Hi I trying to extraction text from pdf with RTL Language (Persian) but the word chars are Left to right.

**Comment by EliotJones** [comment]
Hi @alijkdkar do you have any example files we could look at please?

**Comment by vnikopol** [comment]
Hey, there are any news? The library changes RTL text
from:

`شسيبشسيبشسيبسشيبسشيبسشيبشسيبشسيبسشيب`
to:
`بيشسبيسشبيسشبيشسبيشسبيشسبيسشبيسشبيسش`
each character in wrong order

**Comment by alijkdkar** [comment]
thats great it's awesome.
