### ISSUE TITLE
Access the text fields in the IRS W4 form

### ISSUE THREAD

**Issue by muscatd75** [UglyToad/PdfPig#598]
Hi, I am using pdfpig in order to read the text inside a pdf document. I am new to pdf parsing.

One of these documents is the IRS W4 pdf which can be downloaded from https://www.irs.gov/pub/irs-pdf/fw4.pdf

The following is the part of my code where I try to get the field text:

```
using (PdfDocument document = PdfDocument.Open(filename))
{
	StringBuilder allText = new StringBuilder();
	UglyToad.PdfPig.AcroForms.AcroForm aform;
	
	if(document.TryGetForm(out aform))
	{
		foreach(UglyToad.PdfPig.AcroForms.Fields.AcroFieldBase f in aform.Fields)
		{
			if(f.FieldType == UglyToad.PdfPig.AcroForms.Fields.AcroFieldType.Text)
			{
				UglyToad.PdfPig.AcroForms.Fields.AcroTextField tf = (UglyToad.PdfPig.AcroForms.Fields.AcroTextField)f;
				allText.AppendLine(tf.Value);
				allText.AppendLine(tf.Information.AlternateName);
				allText.AppendLine(tf.Information.PartialName);
			}
		}
	}
}
```

In the fw4.pdf file there is only one AcroFieldBase and it is of type Unknown.

I would appreciate if you can point me in the right direction. Thank you for your help.

**Comment by EliotJones** [comment]
The unknown field in your document probably contains child fields with the actual form content, see the `GetFields` method here for an example of working witth nested fields https://github.com/UglyToad/PdfPig/pull/599/files

**Comment by muscatd75** [comment]
That was my problem. Thank you for you very quick response. 
Should I close the issue? Or will you do that?
