### ISSUE TITLE
Broken text encoding on some pages

### ISSUE THREAD

**Issue by vmato** [UglyToad/PdfPig#600]
We are extracting text from PDF ( PdfDocument.GetPages() / Page.GetWords() ) but getting only 1 correct page and all others with invalid encoding. 

Could we get encoding of a certain page?
[
Sample file](https://docs.eaeunion.org/docs/ru-ru/01139384/err_06042023_150_doc.pdf)

**Comment by EliotJones** [comment]
Hi @vmato unfortunately the font in this file does not contain valid data, if you open the file in a PDF viewer like Chrome or Adobe and copy the text you will see that pages starting from page 5 do not contain valid text. A snippet of the copied text is shown below:

```
2. ÎÁÙÈÅ
ÔÀÐÌÀÊÎÏÅÉÍÛÅ ÑÒÀÒÜÈ

2.1. ÌÅÒÎÄÛ ÀÍÀËÈÇÀ

2.1.2. ÔÈÇÈ×ÅÑÊÈÅ È ÔÈÇÈÊÎ-ÕÈÌÈ×ÅÑÊÈÅ
ÌÅÒÎÄÛ ÀÍÀËÈÇÀ
201020044-2022
2.1.2.44. Òåìïåðàòóðà
êàïëåïàäåíèÿ
Òåìïåðàòóðà êàïëåïàäåíèÿ ïðåäñòàâëÿåò ñî-
áîé òåìïåðàòóðó, ïðè êîòîðîé â óñëîâèÿõ, ïðè-
âåäåííûõ íèæå, ïåðâàÿ êàïëÿ ðàñïëàâëåííîãî
èñïûòóåìîãî îáðàçöà ïàäàåò èç ÷àøêè
```

Your best bet to retrieve the text is use an OCR solution such as Tesseract or similar, unfortunately if there's no data preserved in the file this library can't access it.
