### ISSUE TITLE
I noticed that PDFBox seems to lack some features or find it difficult to obtain information

### ISSUE THREAD

**Issue by xiaoguaishoubaobao** [UglyToad/PdfPig#611]
I noticed that PDFBox seems to lack some features or find it difficult to obtain information, especially information such as text blocks, which is very important for us
Can u produce a Java version of PDFPig for a fee
Pdfpig is really great to use.

**Comment by EliotJones** [comment]
Hi unfortunately to port back to Java would be a huge effort I don't have anywhere near enough time to undertake. Hopefully you're able to achieve what you need with PDFBox or add a C# service to consume this library for your needs.
