### ISSUE TITLE
"Invalid type of toUnicode CMap encountered" calling GetPages()

### ISSUE THREAD

**Issue by RaduPoenaru** [UglyToad/PdfPig#619]
I'm using PdfPig to (magically) parse an auto-generated PDF. It worked until a few weeks ago, when new PDFs have started throwing this error.

It is an exact duplicate of issue #354. As far as my limited understanding of PDFs goes: 
 - The ToUnicode token of the font points to a reference (26?) that is indeed missing from the cross reference stream.  
 - Objects 26 and 32 are missing from the table, a result confirmed by any PDF reader/analyzer.
 - Using some PDF analyzer the table does seem to be messed (see attached image?) but every other app opens the PDF just fine,  so what can I do now?

 
I cannot upload the PDFs publicly, but I could email a de-personalized version of it 

![cross ref](https://user-images.githubusercontent.com/1391718/236304261-b7f58079-1216-45ba-b82e-b601c293885c.png)

**Comment by EliotJones** [comment]
Closing but feel free to reopen if the issue persists
