### ISSUE TITLE
OCR of Scanned PDF

### ISSUE THREAD

**Issue by im-ashar** [UglyToad/PdfPig#623]
I just want to know does it support OCR of scanned PDF?

**Comment by EliotJones** [comment]
Hi @im-ashar no, there's no support for OCR currently. Your best bet is a library like [DocNet](https://github.com/GowenGit/docnet/blob/master/examples/nuget-usage/NugetUsageAnyCpu/PdfToImageExamples.cs) or PdfSharp to generate images then pass those to Tesseract, or use a commercial OCR program.
