### ISSUE TITLE
Pdf version paramter not used in XmpWriter

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#633]
The `version` parameter is not actually used in the `XmpWriter.GenerateXmpStream()` function.
Value is hardcoded to 1.7
https://github.com/UglyToad/PdfPig/blob/fba1cbc13c251d1446e93591ed522ddaced05a44/src/UglyToad.PdfPig/Writer/Xmp/XmpWriter.cs#L70

**Comment by EliotJones** [comment]
I have pushed a fix for this that I think will write the version correctly, should be in tonight's build
