### ISSUE TITLE
Incorrect characters in bookmarks

### ISSUE THREAD

**Issue by mvantzet** [UglyToad/PdfPig#636]
It seems that parsing strings in bookmark titles is not correct, I saw a couple of incorrect characters. I found a similar issue in QPDF https://github.com/qpdf/qpdf/issues/179. This mentions PdfDocEncoding for text outside content streams, which is similar to, but not 100% equal to, ISO-8859-1 notably for the characters in the range 0x80 - 0xA0.

**Comment by EliotJones** [comment]
Latest nightly builds have moved here https://www.nuget.org/packages/PdfPig.Nightly/0.1.9-alpha-20230608-ae83f the latest contains a fix for this. The move to a seperate nightly package reduces the noise for non-nightly consumers

**Comment by mvantzet** [comment]
Great, thanks for fixing this!

**Comment by BobLd** [comment]
Closing as fixes
