### ISSUE TITLE
path.StrokeColor is always black

### ISSUE THREAD

**Issue by aoweis** [UglyToad/PdfPig#641]
Hi,

I need to extract the paths in a PDF Document along with their fill and stroke colors. I'm comparing the output of PDFPig with that of PDF-Tools Extract object and I found that that the StrokeColor in PDFPig is always black RGB(0,0,0) while I'm sure some paths have a stroke color that is not black. Any idea?

Code sample:
```
string fileName = @"Page 1.pdf";

using (PdfDocument document2 = PdfDocument.Open(fileName))
            {
                foreach (Page page in document2.GetPages())
                {
                    foreach(PdfPath path in page.ExperimentalAccess.Paths)
                    {
                            if(path.IsStroked)
                            {
                                Console.WriteLine($"{path[0].GetBoundingRectangle().Value.Left}\t{path[0].GetBoundingRectangle().Value.Right}\t{path[0].GetBoundingRectangle().Value.Top}\t{path[0].GetBoundingRectangle().Value.Bottom}\t{path.StrokeColor}");
                            }
                    }
                }
            }
```

Output (notice how all stroke colors are black RGB(0,0,0)):

16.55	590.55	753.35	753.35	RGB: (0, 0, 0)
16.55	590.55	691.2	691.2	RGB: (0, 0, 0)
217	413.2	739.7	705.65	RGB: (0, 0, 0)
266	266	739.95	728.75	RGB: (0, 0, 0)
317.1	317.1	739.95	728.75	RGB: (0, 0, 0)
364.7	364.7	739.95	728.75	RGB: (0, 0, 0)
216.75	413.45	728.5	728.5	RGB: (0, 0, 0)
216.75	413.45	717.3	717.3	RGB: (0, 0, 0)
266	266	728.75	717.55	RGB: (0, 0, 0)
364.7	364.7	728.75	717.55	RGB: (0, 0, 0)
317.1	317.1	728.75	717.55	RGB: (0, 0, 0)
317.15	317.15	717.55	705.4	RGB: (0, 0, 0)
592.05	592.05	690.7	634.15	RGB: (0, 0, 0)
15.05	15.05	690.7	634.15	RGB: (0, 0, 0)
16.55	592.5	679.7	679.7	RGB: (0, 0, 0)
201.1	201.1	684.7	634.15	RGB: (0, 0, 0)
113.75	113.75	679.7	634.15	RGB: (0, 0, 0)
365.25	365.25	679.7	634.15	RGB: (0, 0, 0)
515.8	515.8	679.7	634.15	RGB: (0, 0, 0)
443.2	443.2	679.7	634.15	RGB: (0, 0, 0)
16.55	590.5	656.85	656.85	RGB: (0, 0, 0)
277.55	277.55	656.85	634.15	RGB: (0, 0, 0)
16.55	590.5	634.15	634.15	RGB: (0, 0, 0)
592.05	592.05	634.15	597.6	RGB: (0, 0, 0)
15.05	15.05	634.15	597.6	RGB: (0, 0, 0)
16.55	592.5	620.15	620.15	RGB: (0, 0, 0)
365.55	365.55	621.4	597.6	RGB: (0, 0, 0)
81.7	81.7	620.15	597.6	RGB: (0, 0, 0)
176.75	176.75	620.15	597.6	RGB: (0, 0, 0)
272.05	272.05	620.15	597.6	RGB: (0, 0, 0)
458	458	620.15	597.6	RGB: (0, 0, 0)
528.45	528.45	620.15	597.6	RGB: (0, 0, 0)
559.55	559.55	620.15	597.6	RGB: (0, 0, 0)
16.55	590.5	597.6	597.6	RGB: (0, 0, 0)
592.05	592.05	597.6	573.65	RGB: (0, 0, 0)
15.05	15.05	597.6	573.65	RGB: (0, 0, 0)
16.55	592.5	586.4	586.4	RGB: (0, 0, 0)
189.6	189.6	586.4	573.65	RGB: (0, 0, 0)
357.9	357.9	586.4	573.65	RGB: (0, 0, 0)
483.2	483.2	586.4	573.65	RGB: (0, 0, 0)
16.55	588.55	573.65	573.65	RGB: (0, 0, 0)
592.05	592.05	573.65	369.3	RGB: (0, 0, 0)
15.05	15.05	573.65	369.3	RGB: (0, 0, 0)
16.55	592.5	562.45	562.45	RGB: (0, 0, 0)

**Comment by BobLd** [comment]
@aoweis could you share the document so that we can have look? It will be difficult to understand what is going on without it

**Comment by aoweis** [comment]
Hi @BobLd,
Is there a way to privately share the document with you? I can share it with individuals who would like to try it, but I cannot post it here.

**Comment by BobLd** [comment]
@aoweis can you send a screenshot of the text that supposed to not be black? What is the color they are supposed to have by the way? Also maybe can you share the output of PDF-Tools Extract object? Last question, can you make sure these paths your seeing are not in fact filled? Maybe by checking both the stroke and the fill color?

**Comment by EliotJones** [comment]
I think you're right there @BobLd most text is filled but not stroked as far as I know so the stroke color probably defaults to 0 (black):
![image](https://github.com/UglyToad/PdfPig/assets/7862346/cd0b11c2-f32d-4b9a-850f-f73f2139843a)

**Comment by aoweis** [comment]
Hi @EliotJones, these are not text items, these are vertical and horizontal lines.

Hi @BobLd,

The paths are stroked not filled, the code checks for this condition in the if statement:

`if(path.IsStroked)`

Also, the PDF-Tools component shows the entire path command as stroked (it ends with S command). By the way, the FillColor property worked for me; however it also has another issue in that sometimes the color doesn't match the PDF-Tools output (RGB 0.090, 0.212, 0.365) in PdfPig versus RGB(0.086,0.212, 0.365) in PDF tools. I can address this in a separate thread to avoid confusion.

Back to stroking: below is what I get from PDF-Tools for the same file, check the highlighted line  `16.55 679.7 m 592.5 679.7 l S` that has a gray color RGB(0.808, 0.808, 0.808). This is line number 15 in the PdfPig output I shared above:

16.55 592.5 679.7 679.7 RGB: (0, 0, 0)

![image](https://github.com/UglyToad/PdfPig/assets/24617048/b44e0671-ae4e-4b84-a736-5ff46c950710)

Also, the last line in my PdfPig output above should be dark blue RGB(0.365, 0.212, 0.086) as per PDF-Tools output.

![image](https://github.com/UglyToad/PdfPig/assets/24617048/4eb4d5e8-3dc7-4193-aa10-e0d36abeddaf)

Other points to consider:

1- I tried to locate those gray and blue paths visually in the PDF file, but I couldn't. I know they exist because the PDF-Tools extracted them. Could they be located in a back layer? Would PdfPig not detect their color in this case?

2- I tried to create a PDF from word file with some colored lines and the PdfPig component returned a StrokeColor. So, it looks like there's something special in the PDF file I'm trying to extract.

Thanks for your help!

**Comment by BobLd** [comment]
@aoweis thanks for the details. Your issue seems to be related to color spaces. A lot of changes were made in the latest version 0.1.8 of PdfPig, can you tell us which version you're using? If it's not 0.1.8, can you give us the results with the latest?

Please find my feedback to your point below:

> By the way, the FillColor property worked for me; however it also has another issue in that sometimes the color doesn't match the PDF-Tools output (RGB 0.090, 0.212, 0.365) in PdfPig versus RGB(0.086,0.212, 0.365) in PDF tools. I can address this in a separate thread to avoid confusion.

That's an interesting point, and might be related to your issue with stroked path. The difference in colour you see in your filled paths is most certainly related to PdfPig not supporting ICC profile colour space properly yet. Because of that, an alternate colour space (that is provided by the pdf document) will be used. It usually works quite well visually (the colours are very similar, like in your case).

But there are cases where this approximation does not work as well, which I guess can be the reason why some paths colour is approximated to black.

> 1- I tried to locate those gray and blue paths visually in the PDF file, but I couldn't. I know they exist because the PDF-Tools extracted them. Could they be located in a back layer? Would PdfPig not detect their color in this case?

It's possible they are clipped, or under other paths. But that should not impact how PdfPig gets the paths and there colours.

> 2- I tried to create a PDF from word file with some colored lines and the PdfPig component returned a StrokeColor. So, it looks like there's something special in the PDF file I'm trying to extract.

That makes sense, Word might not be using ICC profile or provide a better alternate colour space that give better results.

**Comment by aoweis** [comment]
Hi @BobLd,

I was using 0.1.7, but I upgraded to 0.1.8 and the problem is still there. I agree with  you, it seems it's a color space issue.

**Comment by aoweis** [comment]
Just to clarify, I think the difference in FillColor is due to the color space issue since the color retrieved by PdfPig is very close to the one PDF-Tools reports. However, after testing with several files, the stroking color is always black regardless of the actual color, for the files that I tested. If anyone wants to try, you can send me an email to: a_oweis at yahoo dot com and I will reply back with a test file.

**Comment by BobLd** [comment]
Closing as no pdf document publicly sharable available - feel free to reopen if that changes
