### ISSUE TITLE
Render pdf as images

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#647]
Hi @EliotJones, below are my initial thoughts about what's missing to enable rendering pdf pages as images:

- Allow users to create their own `ContentStreamProcessor`, either starting from scratch implementing `IOperationContext`, or implementing an abstract class (to be added, let's call it `BaseStreamProcessor<T>` for now) that contains the current main logic of `ContentStreamProcessor`
- This new abstract `BaseStreamProcessor<T>.GetContent(...)` should return any T, be it `PageContent`, `byte[]`, etc
- The image renderer will derive from`BaseStreamProcessor<byte[]>` for example, with `byte[]` being the rendered page image
- `PageFactory` needs to accept any `IOperationContext` implementation, and the `GetContent()` should return `T`
- We might want to use a similar pattern as in PdfBox, creating a `PdfRenderer` helper class that will take the `PdfDocument` in the constructor, and call the page factory.

I think it would be good to make it possible to not reload the `PdfDocument` but to make it possible to not have to get the `Page` object before rendering.

FYI, some notes on how PdfBox does it:
- `PDFRenderer.java`
	- Helper class
	- ctor: `PDFRenderer(PDDocument document)`
	- `renderImage(int pageIndex, float scale)`
	- uses `PageDrawer.java`
	
- `PageDrawer.java`
	- extends PDFGraphicsStreamEngine (equivalent to PdfPig IOperationContext)

Any feedback welcome!

**Comment by BobLd** [comment]
As a side note, it seems the `GetPage()` function is still not thread safe (as experienced in #168), and would be the perfect opportunity to change that to be able to render pages in parallel. 

I haven't investigated that thoroughly but it seems the `ResourceStore` is one cause of the issue

**Comment by EliotJones** [comment]
Hi @BobLd that's fine, you should just be able to use the plain Apache 2 license for that library since this one inherited a bunch of stuff from PDFBox to do with Adobe files etc.

**Comment by BobLd** [comment]
@EliotJones I've created the repos and published the NuGet package, any feedback welcome

https://github.com/BobLd/PdfPig.Rendering.Skia

I'm closing the issue
