### ISSUE TITLE
Some paths are missing in page

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#66]
Hi,

I am trying to retrieve all the paths from [__this__](https://github.com/UglyToad/PdfPig/files/3566357/104-7-3.pdf) pdf document , but it seems some of them are missing.

When drawing all the bounding boxes found, this is what I get (the `PdfPath.BezierCurve` are in red, and the `PdfPath.Line` are in blue):
![104-7-3](https://user-images.githubusercontent.com/38405645/64121121-d0e4fd80-cd95-11e9-9d85-cb8198dd1749.jpg)

As you can see, for each of the charts, only one line contains bounding boxes, the others seem to be ignored. Same issue for grid lines: some are drawn and some are not.

Am I doing something wrong, or are they really missing?
Thanks,

The code I used is the following:

            using (PdfDocument document = PdfDocument.Open(path))
            {
                for (var i = 0; i < document.NumberOfPages; i++)
                {
                    var page = document.GetPage(i + 1);
                    var paths = page.ExperimentalAccess.Paths;

                    using (var bitmap = converter.GetPage(i + 1, zoom))
                    using (var graphics = Graphics.FromImage(bitmap))
                    {
                        var imageHeight = bitmap.Height;

                        foreach (var p in paths)
                        {
                            if (p == null) continue;
                            var commands = p.Commands;

                            foreach (var command in commands)
                            {
                                if (command is PdfPath.Line line)
                                {
                                    var bbox = line.GetBoundingRectangle();
                                    if (bbox.HasValue)
                                    {
                                        var rect = new Rectangle(
                                            (int)(bbox.Value.Left * (decimal)zoom),
                                            imageHeight - (int)(bbox.Value.Top * (decimal)zoom),
                                            (int)(bbox.Value.Width == 0 ? 1 : bbox.Value.Width * (decimal)zoom),
                                            (int)(bbox.Value.Height == 0 ? 1 : bbox.Value.Height * (decimal)zoom));
                                        graphics.DrawRectangle(bluePen, rect);
                                    }
                                }
                                else if (command is PdfPath.BezierCurve curve)
                                {
                                    var bbox = curve.GetBoundingRectangle();
                                    if (bbox.HasValue)
                                    {
                                        var rect = new Rectangle(
                                            (int)(bbox.Value.Left * (decimal)zoom),
                                            imageHeight - (int)(bbox.Value.Top * (decimal)zoom),
                                            (int)(bbox.Value.Width == 0 ? 1 : bbox.Value.Width * (decimal)zoom),
                                            (int)(bbox.Value.Height == 0 ? 1 : bbox.Value.Height * (decimal)zoom));
                                        graphics.DrawRectangle(redPen, rect);
                                    }
                                }
                            }
                        }
                    }
                }
            }

**Comment by BobLd** [comment]
I ran a test with 2 plots generated with the OxyPlot library ([__here__](https://github.com/UglyToad/PdfPig/files/3566933/oxyplot.pdf) and [__here__](https://github.com/UglyToad/PdfPig/files/3566934/oxyplot_2.pdf)). It seems that all paths are retrieved:
![oxyplot 1_pathsTest](https://user-images.githubusercontent.com/38405645/64130859-e6b9e900-cdbc-11e9-8dbd-290acb35d370.jpg)
![oxyplot_2 1_pathsTest](https://user-images.githubusercontent.com/38405645/64130860-e9b4d980-cdbc-11e9-94e2-0450b5b231a8.jpg)

**Comment by BobLd** [comment]
Also, if it helps, you'll find [__here__](https://github.com/UglyToad/PdfPig/files/3601121/samples.zip) the corresponding `hocr` file.

**Comment by EliotJones** [comment]
Oops, it looks like GitHub has now decided that linking an issue to a commit should close it, which is not very helpful 🤦‍♂ 

I've pushed some changes which I think fix this issue for this file, could you try them out and let me know if it works for you? Thanks.

**Comment by BobLd** [comment]
Hi Eliot, thanks a lot for the update! Looking at the update below, it seems GitHub was right in the end :D. It looks very promising. I'll run the test on other files and get back to you
![104-7-3 1](https://user-images.githubusercontent.com/38405645/64708801-18ae0800-d4ad-11e9-9ddb-60aa30d24fc4.png)

**Comment by BobLd** [comment]
After doing a better visual check, I was able to spot some missing paths (they are circled in purple in the picture below, I don't pretend this is exhaustive)
![104-7-3 1_errors](https://user-images.githubusercontent.com/38405645/64994876-b6506f80-d8d1-11e9-9e03-8c202dc4adc4.png)
There are:
- 1 vertical line (left chart)
- 6 x-axis' tick marks (2 on the left, 4 on the right)

**Comment by BobLd** [comment]
After further checks, it seems the shapes above the are 'missing' are in fact there, but their bounding boxes are not drawn.
I still don't understand why, if it is a problem with the drawing, or a problem with the bounding box.

If okay with you, I guess this issue can be closed.

**Comment by EliotJones** [comment]
Hmm, looking at the output of the paths it seems like there are at least 660 with a width of zero (all vertical lines). It seems like it's probably something with how they're being drawn so I'll close this for now but it you notice the same problem elsewhere feel free to re-open or raise a new issue.
