### ISSUE TITLE
Image will not decode

### ISSUE THREAD

**Issue by gktval** [UglyToad/PdfPig#673]
I am trying to read a GeoSpatial PDF (https://en.wikipedia.org/wiki/Geospatial_PDF) but running into some problems decoding the buffer.  In ReadImages in the XobjectFactory class, the decodedBytes return as null. The filter for the image says it is ASCII85Decode.

Here is a link to the pdf: https://www.fs.usda.gov/Internet/FSE_DOCUMENTS/fseprd1102849.pdf

Related, but a geospatial PDF should have some reference to the coordinates in the metadata. Any idea where in the document information this is stored?

**Comment by BobLd** [comment]
@gktval I'm not able to find any picture that is `ASCII85Decode`. I only see `FlateDecode` (supported in PdfPig) and `DCTDecode` (not supported). Can you point me to which page and which image you are refering to?

Regarding your question about coordinate/metadata, have a look into `page.GetMarkedContents()`, seems like there's a lot of information in there.

**Comment by gktval** [comment]
Thanks for the response. I think I was a little confused by the code. I where it is referencing the DCTDecode.
