### ISSUE TITLE
Missing character

### ISSUE THREAD

**Issue by JansXue** [UglyToad/PdfPig#688]
https://github.com/UglyToad/PdfPig/blob/4a480ffd7f30b35e42fc9d664c0891a5344bfae4/src/UglyToad.PdfPig/Graphics/ContentStreamProcessor.cs#L443
Because StringTokenizer determines Encoding, in special cases there are only two codes, 0xFE and 0xFF, StringToken's Data will be Empty, and if the font is Type1C, it will cause the character to be lost here. So Mebe should using StringToken.GetBytes() directly instead of OtherEncodings.StringAsLatin1Bytes(((StringToken)token).Data)

**Comment by BobLd** [comment]
Hi @JansXue do you have a document example for that?

**Comment by JansXue** [comment]
[Indexed-DeviceRGB-JPXDecode-0-[0.0,255.0]-Font-F1_1_missing_char_255.pdf](https://github.com/UglyToad/PdfPig/files/12447007/Indexed-DeviceRGB-JPXDecode-0-.0.0.255.0.-Font-F1_1_missing_char_255.pdf)
![missing_char](https://github.com/UglyToad/PdfPig/assets/29146781/751f91c9-2804-4c7c-aae6-fe46a93ae615)
The characters in the red box in the picture are the missing characters

**Comment by JansXue** [comment]
@BobLd FontName T1_1
![missing_char2](https://github.com/UglyToad/PdfPig/assets/29146781/599f0e71-c185-4593-a9b5-8ce874374762)

**Comment by BobLd** [comment]
@JansXue thanks a lot for the document and details, will look into that shortly

**Comment by JansXue** [comment]
@BobLd Sorry, my current network environment is temporarily unable to push code to github, if I can push code later, I will be happy to submit PR

**Comment by BobLd** [comment]
@JansXue no worries, I'll try to look into that when I have time (happy for someone else to look into that too)

**Comment by BobLd** [comment]
Closing issue as fixed in #763
