### ISSUE TITLE
How to extract table rows from pdf using PdfPig

### ISSUE THREAD

**Issue by teamsdeveloper** [UglyToad/PdfPig#696]
I have a pdf file with some questions and answers like below image:

![image](https://github.com/UglyToad/PdfPig/assets/91174798/28444a39-544f-467f-a368-b003368ddaea)

I want to extract questions and answers in pdf tile.

Please help me.

**Comment by changetocoding** [comment]
Tables are not directly supported but you can use [Tabula Sharp](https://github.com/BobLd/tabula-sharp) or [Camelot Sharp](https://github.com/BobLd/camelot-sharp). As of 2023 Tabula-sharp is the most complete port [source](https://github.com/BobLd/tabula-sharp/discussions/27)
