### ISSUE TITLE
Unescaped form field text leads to invalid PDF

### ISSUE THREAD

**Issue by listm** [UglyToad/PdfPig#730]
Hello!
When opening an existing PDF (containing filled form fields) and building the document using PdfPig, just like in the following code piece, the PDF gets invalid with specific form field values, because apparently the value needs to be escaped.
Specifically, when the form field value contains `(` (e.g. `(` as in the example below, or also `Test value (`) the PDF will be broken, when the bracket gets closed within the form field value text (e.g. `()`), it will be ok.

```csharp
using UglyToad.PdfPig.PdfDocument inputDocument = UglyToad.PdfPig.PdfDocument.Open(pdfStream);
PdfDocumentBuilder pdfDocumentBuilder = new()
{
    ArchiveStandard = PdfAStandard.A2A,
    IncludeDocumentInformation = true,
};
pdfDocumentBuilder.AddPage(inputDocument, 1);
var result = pdfDocumentBuilder.Build();
```
---------------------

Closing round bracket - `.../Type /Annot /V (()) >>...` - OK
```pdf
108 0 obj
<</AP <</N 107 0 R >>/DA (/F1 12 Tf) /F 4 /FT /Tx /Ff 12582913 /MK <<>>/P 5 0 R /Rect [ 25.8907 178.502 424.782 193.622 ] /Subtype /Widget /T (4207_Diagnose_Verdachtsdiagnose) /Type /Annot /V (()) >>
endobj
```

![image](https://github.com/UglyToad/PdfPig/assets/2329483/6a8c988b-a8bf-4d48-bf99-5e105897149b)

--------------------------

Only opening round bracket - `.../Type /Annot /V (() >>...` - Invalid
```pdf
108 0 obj
<</AP <</N 107 0 R >>/DA (/F1 12 Tf) /F 4 /FT /Tx /Ff 12582913 /MK <<>>/P 5 0 R /Rect [ 25.8907 178.502 424.782 193.622 ] /Subtype /Widget /T (4207_Diagnose_Verdachtsdiagnose) /Type /Annot /V (() >>
endobj
```

![image](https://github.com/UglyToad/PdfPig/assets/2329483/839fe489-7cc3-4c4e-8ccd-dc2343e02da1)

------------------

I don't know much about the PDF standard, but according to [this Stackoverflow answer](https://stackoverflow.com/a/559557/1380748), brackets and backslackes need to be escaped. So, in assumption of PdfPig not escaping, I tried to fill the form value with `\(` (in a step before PdfPig is involved), which resulted in `/Type /Annot /V (\() >>`, but this did not work as well, as the `\(` gets rendered directly as text, which I find very confusing. So there is probably an other way of escaping. I can attach example files if this helps.

**Comment by EliotJones** [comment]
This should be fixed in the latest nightly builds

**Comment by listm** [comment]
@EliotJones thank you! Works now for me - I can confirm that the issue is fixed.
