### ISSUE TITLE
System.NotImplementedException for verticle font

### ISSUE THREAD

**Issue by simon3218** [UglyToad/PdfPig#75]
When I execute the program, I get a System.NotImplementedException: 'Vertical fonts are currently unsupported,
Please submit a pull request or issue with an example file.' message, so I provided a sample pdf.

Vertical fonts are currently unsupported, please submit a pull request or issue with an example file.
   於 UglyToad.PdfPig.Graphics.ContentStreamProcessor.ShowText(IInputBytes bytes) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs: 行 186
   於 UglyToad.PdfPig.Graphics.Operations.TextShowing.ShowText.Run(IOperationContext operationContext) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Graphics\Operations\TextShowing\ShowText.cs: 行 68
   於 UglyToad.PdfPig.Graphics.ContentStreamProcessor.ProcessOperations(IReadOnlyList`1 operations) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs: 行 111
   於 UglyToad.PdfPig.Graphics.ContentStreamProcessor.Process(IReadOnlyList`1 operations) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Graphics\ContentStreamProcessor.cs: 行 102
   於 UglyToad.PdfPig.Parser.PageFactory.GetContent(IReadOnlyList`1 contentBytes, CropBox cropBox, UserSpaceUnit userSpaceUnit, PageRotationDegrees rotation, Boolean isLenientParsing) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Parser\PageFactory.cs: 行 129
   於 UglyToad.PdfPig.Parser.PageFactory.Create(Int32 number, DictionaryToken dictionary, PageTreeMembers pageTreeMembers, Boolean isLenientParsing) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Parser\PageFactory.cs: 行 112
   於 UglyToad.PdfPig.Content.Pages.GetPage(Int32 pageNumber) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\Content\Pages.cs: 行 66
   於 UglyToad.PdfPig.PdfDocument.GetPage(Int32 pageNumber) 於 F:\IISC\My Lab\PdfPig-master\src\UglyToad.PdfPig\PdfDocument.cs: 行 159
   於 DocumentLayoutAnalysis.ImageTest.Run(String path) 於 F:\IISC\My Lab\DocumentLayoutAnalysis-master\DocumentLayoutAnalysis\DocumentLayoutAnalysis\ImageTest.cs: 行 25

my environment is :
OS : windows 10
VS 2017 C#
.NET Framework 4.6.1
pdfpig version : 0.0.9.0

[vertical_sample01.pdf](https://github.com/UglyToad/PdfPig/files/3737355/vertical_sample01.pdf)

**Comment by simon3218** [comment]
I tested it, but the situation has not improved, and even the function of the horizontal text box has failed. I attached another test file and result file.

[test.pdf](https://github.com/UglyToad/PdfPig/files/3747366/test.pdf)
![result](https://user-images.githubusercontent.com/31232099/67153654-c2d84580-f31f-11e9-8af7-6ddac9d31b01.png)

**Comment by EliotJones** [comment]
It looks like here retrieving the glyph height is currently unsupported. Unfortunately I'm away on holiday for the next few weeks but in the meantime it might be best to hard-code a height when the height of a glyph is returned as zero.

I'll see what can be done to retrieve the bounding boxes fully when I get back.

**Comment by simon3218** [comment]
Ok, waiting for you to come back.

**Comment by EliotJones** [comment]
Sorry it has taken so long to follow up on this. It should work in the version attached to this comment. Please give it a try and let me know how you get on.

[PdfPig.0.0.9.91.zip](https://github.com/UglyToad/PdfPig/files/3927483/PdfPig.0.0.9.91.zip)

**Comment by EliotJones** [comment]
I think this should be working now, feel free to re-open with some additional details if not.
