### ISSUE TITLE
Codecov coverage data seems outdated

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#755]
It seems that the code coverage numbers available on https://app.codecov.io/gh/UglyToad/PdfPig are outdate, as the latest commit available is as of 2 years ago:
![image](https://github.com/UglyToad/PdfPig/assets/38405645/9570f502-e095-4c1e-a4fd-cee0b66a324b)

Also, the Codecov NuGet package is deprecated:
![image](https://github.com/UglyToad/PdfPig/assets/38405645/c7350beb-bd92-4a0f-b24d-b475f9f79502)

@EliotJones do you remember how it is supposed to work? How is the codecov updated? Is it thourg a GitHub Action? Happy to look into that but I'd rather have some direction first

**Comment by EliotJones** [comment]
I don't remember to be honest, I think it probably was in the build action. I'm in favour of removing it really. I think integration tests provide a lot more value than the unit tests in most instances so I'm not too concerned about raw coverage %

**Comment by BobLd** [comment]
I agree, will try to find time to take care of that

**Comment by Numpsy** [comment]
Was just having a look at the deps after seeing #771 - if there is no interest in the coverage, would there be interest in a PR of https://github.com/Numpsy/PdfPig/commit/f1c316185d8cdbbb265fea9523d42f27cb6fb7bd or something to remove the dependencies?

**Comment by BobLd** [comment]
@Numpsy yes definitely! Feel free to open a PR, I'll review it shortly
