### ISSUE TITLE
PdfPig freezes on this document

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#76]
Hi Eliot,
While you are fixing the other issues, I thought I will add one more :-)

For some reason PdfPig cannot open the file below. It freezes on PdfDocument.Open(). I'm guessing it's due to the comments/annotations in there?
(Tested with Nuget package version 0.0.9, using .Net 4.5)

https://drive.google.com/open?id=1cU4ua-DjpPODOur91AzCDNXwN6w3r9-s

Thank you!

**Comment by EliotJones** [comment]
This was an interesting one, it got stuck when lenient parsing was set to `true` but not when using `false`. I've made a slightly hacky fix for this which fixes the underlying problem but that area of code is a bit of a mess and could do with cleaning up in future.

**Comment by vadik299** [comment]
Thank you Eliot, it works now!
