### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by DanMcNamee42** [UglyToad/PdfPig#771]
I was investigating using this package for use on a work project, and part of our due diligence before using packages is to run the package through a scan for vulnerabilities.  Our scan found multiple security vulnerabilities with the old versions of .NetCore and Newtonsoft.Json that should be fixed by updating the packages to the current versions.

I like the package, it does exactly what we need, but with the vulnerabilities, I won't be able to get it approved.  Any chance of getting the packages you are using updated to address the vulnerabilities?

Thanks!

**Comment by Numpsy** [comment]
When you say 'the package', so you mean the PdfPig nuget package or something else in the repo? (the main lib seems to only depend on System.ValueTuple, and then only on .NET 4.x, though adding a .NET 4.7.1 target might remove that for 4.7.1+ consumers)

**Comment by Numpsy** [comment]
There are references to .NET Standard.Library 1.6.1 from the tests though:
![image](https://github.com/UglyToad/PdfPig/assets/1178570/3523c3da-896d-4d65-9071-47d786386db3)

which does cause complaints from [certain tooling](https://github.com/RicoSuter/NSwag/pull/4716#issuecomment-1928068824).

**Comment by DanMcNamee42** [comment]
Sorry I wasn't clear.  It's with NuGet packages that are included in PdfPig.  They could be packages that are pulling in other dependencies that are out of date.  Looking at the NuGet packages that are in PdfPig now, all of them are out of date, with CodeCov being deprecated and no longer maintained.  Possibly updating the NuGet packages will update the dependencies..

**Comment by Numpsy** [comment]
there's already a discussion about the coverage thing in #755

**Comment by DanMcNamee42** [comment]
Thank you!  Hopefully there will be a discussion about updating the other packages as well.

**Comment by Numpsy** [comment]
The dependencies in the test project have been updated and minimzed now, which has removed transitive references to a load of old stuff, though the test project itself still runs against .NET Core 2.1 as well as 6.0

**Comment by DanMcNamee42** [comment]
Thank you!

**Comment by DanMcNamee42** [comment]
It all looks great now.  Thank you!
