### ISSUE TITLE
No spaces between words

### ISSUE THREAD

**Issue by securigy** [UglyToad/PdfPig#777]
I have a file (attached) and when I try to extract text from it, it "swallows" all the spaces:

    `using (PdfDocument document = PdfDocument.Open(fileStream))
    {

            foreach (Page page in document.GetPages())
            {
                 docText += page.Text;
            }
    }
    `
When I view the page.Text in VS2022, it looks like that - definitely wrong. The spaces are all gone.
Anybody know what's wrong?

[Cancer_Prevention_With_Natural_Compounds.pdf](https://github.com/UglyToad/PdfPig/files/14202483/Cancer_Prevention_With_Natural_Compounds.pdf)

`CancerPreventionWithNaturalCompoundsNorleenaP.Gullett,aA.R.M.RuhulAmin,bSoleyBayraktar,cJohnM.Pezzuto,dDongM.Shin,bFadloR.Khuri,bBharatB.Aggarwal,eYoung-JoonSurh,fandOmerKucukbBotanicalandnutritionalcompoundshavebeenusedforthetreatmentofcancerthroughouthistory.Thesecompoundsalsomaybeusefulinthepreventionofcancer.Populationstudiessuggestthatareducedriskofcancerisassociatedwithhighconsumptionofvegetablesandfruits.Thus,thecancerchemopreventivepotentialofnaturallyoccurringphytochemicalsisofgreatinterest.Therearenumerousreportsofcancerchemopreventiveactivityofdi
`

**Comment by BobLd** [comment]
@securigy can you try extracing the text using `ContentOrderTextExtractor.GetText(...)` and see if that helps?

See https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.DocumentLayoutAnalysis/TextExtractor/ContentOrderTextExtractor.cs

**Comment by securigy** [comment]
I actually noticed that the problem I described exist with the particular document I attached in my original post. Not sure why - it might be a special PDF format (?). I will definitely try your suggestion and let you know. Thank you.

**Comment by securigy** [comment]
I tried your suggestion, and it worked beautifully. It also split the text to paragraphs, something I was looking to achieve for a while. It will allow you to change the segmentation algo and make text segments based on the paragraphs (being IMO the smallest reasonable semantic unit) instead of sentences.

I am daring to ask: is there any way to parse tables?  (at the level that will allow to identify a row with its cell)

**Comment by BobLd** [comment]
Amazing, very happy that worked!

You might to also have a look at the Document Layout Analysis part of the wiki.

Regarding the table extraction, your best chance is to use Tabula sharp (https://github.com/BobLd/tabula-sharp). Results might be not consistent though.

Another library that's not finished is Camelot sharp

**Comment by securigy** [comment]
So, I looked at Tabula and Camelot. 
Tabula: it looked good to me until I looked at the list of issues: some of them are irrelevant to me (Japanese) but some look critical - like merged text from row cells or incorrect answers if text is missing in the cell... The question is: is it just edge case phenomena or happens all the time? I need to segment large volumes of data and table would be a segment where I take each cell value and prefix it with a column name. Then I concatenate the prefixed cell values in a row into 1 string. So how much problem should I expect provided that's all I need to do? Difficult to judge the "no consistent" thing.

**Comment by BobLd** [comment]
@securigy these two C# libraries are ports from other libraries:
- Tabula https://github.com/tabulapdf/tabula-java (https://tabula.technology/)
- Camelot https://github.com/camelot-dev/camelot

Both libraries are "rule based" and won't work for every cases.

If you want a different approach, you will need to loowant to look into machine learning. One example of such model is Microsoft's https://github.com/microsoft/table-transformer (untested)

You might want to read more about table extraction here:
https://github.com/BobLd/DocumentLayoutAnalysis/blob/master/README.md#table
