### ISSUE TITLE
Broken bookmarks are outputted if title contains non-ASCII characters.

### ISSUE THREAD

**Issue by filzrev** [UglyToad/PdfPig#789]
**Describe the bug**
When bookmark title contains some non-ASCII characters.
Bookmark is not outputted correctly.

**To Reproduce**
I've created unit tests that cause problems.

https://github.com/filzrev/PdfPig/blob/c2b9d43ef71f61ecac0bec0ef05d3767965d7912/src/UglyToad.PdfPig.Tests/Integration/NonAsciiCharactorsBookmarksTests.cs

**Comment by BobLd** [comment]
@filzrev thanks very much for providing the tests, I've created a fix PR
