### ISSUE TITLE
On the main GitHub page, please clearly state that form fields cannot be populated

### ISSUE THREAD

**Issue by PermanentNovice** [UglyToad/PdfPig#797]
It was frustrating to set up a project only to discover that form fields are read-only. In the Forms section of the main GitHub page, please make it clear that we cannot use PdfPig to populate Acroforms. Those who need that functionality would immediately know they should look elsewhere.

**Comment by davebrokit** [comment]
Wiki has been updated here: https://github.com/UglyToad/PdfPig/wiki

**Comment by PermanentNovice** [comment]
I meant the main page at https://github.com/UglyToad/PdfPig under the “Forms” heading, but obviously your change to the wiki will help as well.

Thanks.

**Comment by davebrokit** [comment]
That's been changed. See https://github.com/UglyToad/PdfPig?tab=readme-ov-file#forms-0010

Also a forms section has been added to the wiki. It'll be great if you can spare a few minutes and checkover/add to it (as I haven't used it that much and it seems you tried it out).

https://github.com/UglyToad/PdfPig/wiki/Forms-(AcroForms)

Can you also close this issue

**Comment by PermanentNovice** [comment]
Closing this issue. Thanks.
