### ISSUE TITLE
Exception when getting annotations

### ISSUE THREAD

**Issue by mjwsteenbergen** [UglyToad/PdfPig#81]
Thank you for creating this wonderful library. 

However, when trying to extract Annotations from some pdf's I run into an exception:

`Could not find the object with reference: 423 0`

StackTrace:
<details>
    at UglyToad.PdfPig.Tokenization.Scanner.PdfTokenScanner.Get(IndirectReference reference)

   at UglyToad.PdfPig.Parser.Parts.DirectObjectFinder.TryGet[T](IToken token, IPdfTokenScanner scanner, T& tokenResult)

   at UglyToad.PdfPig.Annotations.AnnotationProvider.GetAnnotations()+MoveNext()

   at Annostract.AnnotationExtractor.Extract(String fpath) in AnnotationExtractor.cs:line 23
</details>

The following code should trigger it.
```
using (PdfDocument document = PdfDocument.Open(fpath))
            {
                foreach (var page in document.Pages())
                {
                        foreach (var annotation in page.ExperimentalAccess.GetAnnotations())
                        {}
                }
            }
```

[with the following pdf](https://github.com/UglyToad/PdfPig/files/3797918/test.pdf)

if I can be of any more help, please let me know

**Comment by EliotJones** [comment]
Sorry to hear you've encountered this issue. I'm currently away from my computer travelling so I won't be able to get round to this for maybe a couple of weeks, apologies for the delay.

**Comment by EliotJones** [comment]
Just an update, I'll be back in the country and working on issues again from 25th November, sorry it has taken so long.

**Comment by EliotJones** [comment]
It looks like this is now working on the latest master code, please try the attached NuGet package and let me know if it fixes the problem. Hopefully an official NuGet release for the next version containing this fix will be out before Christmas.

[PdfPig.0.0.9.73.zip](https://github.com/UglyToad/PdfPig/files/3886603/PdfPig.0.0.9.73.zip)

**Comment by mjwsteenbergen** [comment]
Thank you for all your work and apologies for not replying sooner! 
The latest nuget version resolves this issue. 
Thanks again!
