### ISSUE TITLE
[Proposal] Add a getting started notebook

### ISSUE THREAD

**Issue by cordasfilip** [UglyToad/PdfPig#811]
Hi I have been playing around with PdfPig, it's an excellent library  
Since I have been playing around with it, I created a small notebook to view the results that some else that starting might find useful. https://gist.github.com/cordasfilip/c6d2510b358323dc2f71c843460cbcdf 

here is the document I used to test it (it's some Microsoft demo pdf) you can use any document in it you want 
[Benefit_Options.pdf](https://github.com/UglyToad/PdfPig/files/14795827/Benefit_Options.pdf)

I think it's a ok place to start because it has document preview. I could also make a code space for this on github so people can test it really quickly.
If you have any questions, please ask.

**Comment by davebrokit** [comment]
Great idea. There is a wiki here: https://github.com/UglyToad/PdfPig/wiki.

I've edited the wiki to include your gist link. 

p.s. great idea with using PdfDocumentBuilder to create a pdf with the bounding boxes draw. You learn something new each day 👍

**Comment by cordasfilip** [comment]
@davebrokit Great, as I said use it however you wish just wanted to help as much as I can.

**Comment by davebrokit** [comment]
Brill Thanks. One of your examples has also been added to the Readme.md. Feel free to close the issue if you're satifised. If you have other examples please send them my way and I can update the wiki

**Comment by cordasfilip** [comment]
@davebrokit will close it, and will try to make more examples maybe make a pr as well with it.
