### ISSUE TITLE
Document not decrypted properly

### ISSUE THREAD

**Issue by BobLd** [UglyToad/PdfPig#83]
It appears [this](https://www.adobe.com/content/dam/acom/en/devnet/font/pdfs/5088.FontNames.pdf) document is not decrypted properly.

For example:
- `Author = ">«5Iou×\tJÎö\u0011×ÜÕü¶j{oÖ\u008eH\u009a°s\u0091o"`
- `CreationDate = ";õk\u00123l¢^\f\u009d«O\u0096\u008b\u0094ë"`
- `Title = "9 4_*\u001bò\u0001UÅý^îÊÔ©\u0087|"`

Letters and words are extracted correctly.

**Comment by EliotJones** [comment]
Just a quick update in case you were wondering about the lack of response, I'm getting back from my travels on the 25th of November and will start working through the new issues (and PR) soon after, apologies for the delay.

**Comment by EliotJones** [comment]
This should be fixed now, it looks like Hex tokens weren't being decrypted when they formed the keys of dictionary entries.

**Comment by BobLd** [comment]
Hi Eliot, 

Thanks for your help, it is now properly decrypted!
- `Author = "Adobe Developer Technologies"`
- `CreationDate = "D:19991206111237"`
- `Title = "Font Naming Issues"`
