### ISSUE TITLE
Copy existing page to PdfDocumentBuilder without it's text

### ISSUE THREAD

**Issue by gusneves** [UglyToad/PdfPig#847]
I need to add OCR text to several existing pdf. Many of them are scanned and don't have any embedded text, however I need to address the case where the file already contains the text, or else the final file will have duplicated text.

Is there a way to add the page to the builder without it's text? Or simply set the page's `Text` property to `""`?

**Comment by mayurjansari** [comment]
may be you can use ` PdfTextRemover.RemoveText(ocrFilePath3).Save(noTextFileName);`

**Comment by EliotJones** [comment]
As mayur suggests the `PdfTextRemover` should work for this use case.
