### ISSUE TITLE
TryGetForm does not support field partial names with a "."

### ISSUE THREAD

**Issue by vanillaFriday** [UglyToad/PdfPig#848]
PDF-XChange Editor offers a very handy possibility to "Create Multiple Copies..." of any form. The copies have the Syntax [field partial name].[vertical counter].[horizontal counter]

When loading such a document, GetAcroForm does not copy the fields with one or two "." in the name to the acroDictionary. A test pdf with those fields is attachted.

- one ".": is parses the partial name to what is before the "."
- two ".": it does not find the field at all

Changing the "." to "_" fixes the problem.

Please add support for fields with a single or multiple "." in the partial name.

[test_doc.pdf](https://github.com/user-attachments/files/15808877/test_doc.pdf)

**Comment by BobLd** [comment]
@vanillaFriday I'm working on it. Can you tell me which property/field should have [field partial name].[vertical counter].[horizontal counter]?

**Comment by vanillaFriday** [comment]
@BobLd  it should be the AcroFieldBase.Information.PartialName property. I currently have no adobe reader avaible on this maschine. It's named "Field Name" in XChange.

**Comment by BobLd** [comment]
@vanillaFriday this is what I see in your sample doc
![image](https://github.com/UglyToad/PdfPig/assets/38405645/106b6f0b-f75d-4e33-a6e4-89eb212b6825)

Using the Winking Pdf Anaylzer app (not related to PdfPig), it seems the values are the same.
![image](https://github.com/UglyToad/PdfPig/assets/38405645/1b1b8db6-e63b-474c-9d43-9a0c26117129)
![image](https://github.com/UglyToad/PdfPig/assets/38405645/c710a37e-de19-4f41-9063-08ace1ff1f4b)

Either Winking Pdf Anaylzer (quite possible given how pdf work!) has the same problem as PdfPig, or the information is missing in your pdf.

Can you double check?

**Comment by vanillaFriday** [comment]
@BobLd I found a similar question/problem here with a appropriate answer (different project):
[https://github.com/empira/PDFsharp/issues/34](url)

So maybe PDF XChange is creating childs and that's the reason for the "."? It looks as follows on my screen:
![grafik](https://github.com/UglyToad/PdfPig/assets/139131697/88a7f01e-906f-4e38-a128-15b01b98dc3f)

**Comment by BobLd** [comment]
@vanillaFriday they are indeed children. If you want to see the reference you have on screen, you might want to use something like

```csharp
public void Issue848()
{
	using (var document = PdfDocument.Open(IntegrationHelpers.GetDocumentPath("test_doc_issue_848"), ParsingOptions.LenientParsingOff))
	{
		document.TryGetForm(out var form);

		foreach (var field in form.Fields)
		{
			var str = GetText(field).ToArray();
		}
	}
}

private static IEnumerable<string> GetText(AcroFieldBase acro, string text = null)
{
	if (text is null)
	{
		text = acro.Information.PartialName;
	}
	else
	{
		text += "." + acro.Information.PartialName;
	}

	if (acro is AcroNonTerminalField nonTerminal)
	{
		foreach (var child in nonTerminal.Children)
		{
			foreach (var t in GetText(child, text))
			{
				yield return t;
			}
		}
	}
	else if (acro.Information.Parent.HasValue)
	{
	   yield return text; // final
	}
}
```

Result for the first one:
![image](https://github.com/UglyToad/PdfPig/assets/38405645/1d406aa6-75af-457c-923b-dc010dd64ffc)
