### ISSUE TITLE
Errors in examples on "readme.md" ?

### ISSUE THREAD

**Issue by AFract** [UglyToad/PdfPig#851]
Hello, 

I am discovering the PdfPig library, which seems very nice, but I found some confusing things in your examples, and especially the "Advanced Document Extraction" one of the main readme page:

- The `foreach (var word in page.GetWords())` seems totally useless (and monstruously increase execution time as it is around the whole treatment)
- The `pageBuilder.AddText(block.ReadingOrder.ToString(), 8, bbox, font);` does not work as is, since "bbox" parameter is apparently expected to be a point.

I could have done a PR to improve this but since I'm new with the library, I think it's better to explain it and let you fix it the best way.

Thank you

**Comment by davebrokit** [comment]
Thanks! PR raised to fix it. Let me know if you spot any other issues in the documentation.
