### ISSUE TITLE
Width/Height/Text not properly extracted for type3 font

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#86]
Hi, in this document the text inside the table is not showing up properly - all width and height is 0 and the text is gibberish (no toUnicode table?).

https://drive.google.com/file/d/1j_W3o6YZgwWadHJ9RnHrdOSPfNhULLL3/view?usp=sharing

```
            using (PdfDocument document = PdfDocument.Open(@"Type3_Font_issue.pdf"))
            {

                var page = document.GetPage(1);

                for (int j = 0; j < page.Letters.Count; j++)
                {
                    Letter l = page.Letters[j];

                    var height = (float)Math.Abs(page.ExperimentalAccess.GetPointSize(l));

                    if (height == 0)
                    {
                        Console.WriteLine(l.Value);
                    }
                }
            }
```

**Comment by EliotJones** [comment]
It looks like the problem with gibberish text is indeed due to the missing `ToUnicode` table, copying the contents in both Adobe Reader and Chrome PDF viewers I get:

```
Signature of Contractor’s Rig Manager
V. 1.1
²³µ´
¶·¸¹º»·¼½¹
µ¾Á¿À ÁÁÂÀ
¼Ã¶ ÇÇÄÄÄÄÅÅÆÈÈÉÊÉÅ
²ÁË¿À
¼Ïº ½¼Í·¸Ì¶»»ÎÎ ÒÄÄÆÆÆÉÕÐÖÑÓÔÔÔ
ÆÄÐÉÆÕ
ØÄÙ×
ÜÛ³µÚ
ÄÄÅÆÆÆÉÕÖÔÔÔ
```

For the table contents. 

It does look like the width is getting incorrectly set to 0 by PdfPig though, which should be fixed.

**Comment by huzhiguan** [comment]
Hi, I'm probably hitting a similar issue with this file: [Link](https://drive.google.com/file/d/1Eak3Mme9gdRZG__kE4VWwncIm_p2kucw/view?usp=sharing)
The heights of many letters in it are 0. The other pdf parsers I tested with can correctly pick up the height. I tried to track the issue and it seems like PdfPig was not able to get the `glyphIndex` for those letters. Let me know if you need more details. Thanks!

**Comment by EliotJones** [comment]
Hi,

This was actually a slightly different issue, since it relates to TrueType rather than Type3 fonts, but I've had a look into it and it was actually a fairly major problem with how TrueType bounding boxes were calculated. 

I've now pushed a commit which fixes the issue for this document.

**Comment by huzhiguan** [comment]
> I've now pushed a commit which fixes the issue for this document.

I just tested it out and it works great! It also fixes a few other ones that had the same issue. Thanks a lot!
