### ISSUE TITLE
Letter color doesn't look right

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#89]
Hi, for this document:

https://drive.google.com/open?id=1mnQQByi8gCdnhZysUHfFdAk7ZUcWN87X

I'm not sure I'm getting Color correctly. All the letters are white, even those that don't look white in Adobe Reader.
E.g. for word "License" (in the top left corner) I'm getting color "Grey: 1", which I believe means white?
Is that a bug or I'm getting color incorrectly?

            using (PdfDocument document = PdfDocument.Open(@"C:\all_white_color.pdf"))
            {
                var page = document.GetPage(1);

                foreach (var word in page.GetWords())
                {
                    if (word.Text.Contains("License"))
                    {
                        var letters = word.Letters;
                        Console.WriteLine(letters[0].Color);
                    }
                }
            }

Thank you!

**Comment by EliotJones** [comment]
This was due to an incomplete implementation of the full Color Spaces specification in the library. I've added support for the specific Color Space used in this document (`/Separation`) but values may still be incorrect for other advanced Color Spaces.

**Comment by vadik299** [comment]
Hmm. Instead of Grey:1 it now shows CMYK: (0, 0, 0, 0)
But that's still white color. These letters look black in Adobe Reader.

**Comment by EliotJones** [comment]
Doh! I forgot CMYK was backwards to literally every other color type 😆 

I'll take another look.

**Comment by vadik299** [comment]
Works good now. Thank you Eliot!
