### ISSUE TITLE
Page rotation 360

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#90]
Hi,
For this document:
https://drive.google.com/open?id=1pk0CmBtGlBZ87_pOTrbKb8XPwl9Zf7Ee

I'm getting error on GetPage() call:
System.ArgumentOutOfRangeException: 'Rotation must be 0, 90, 180 or 270. Got: 360.
Parameter name: rotation'

            using (PdfDocument document = PdfDocument.Open(@"C:\rotation360.pdf"))
            {
                var page = document.GetPage(1);
            }

Thank you!

**Comment by EliotJones** [comment]
Hi, thanks for the issue report, I've just pushed a change which will clamp rotations to the range 0 - 270 (treating 360 as 0, 450 as 90, etc).

It looks like this document also has the same issue as #86, the text inserted into table cells uses a Type3 font which doesn't include Unicode values so the text is garbled.

If you hadn't already it's worth running these documents through an OCR just to check you can access the content correctly once it has been OCRed.

**Comment by vadik299** [comment]
Eliot, thank you for fixing it so quick! Works well now!

Yes, the document seems to have a few different problems. I just thought it's better to keep each one as a separate issue.
