### ISSUE TITLE
Parsing indirect objects does not support missing or garbage-prepended endobj or endstream

### ISSUE THREAD

**Issue by Greybird** [UglyToad/PdfPig#900]
In some files, `endobj` is not present before a new object starts:
```
1 0 obj
<</Type /XRef>>
2 0 obj
```
or, sometimes, typically with `startxref` or `xref`:
```
1 0 obj
<</Type /XRef>>
xref
```

Sometimes, `endobj `is prepended with garbage:
```
1 0 obj
<</Type /XRef>>
>>endobj
2 0 obj
```

It can also happen that `endstream `is missing:
```
1 0 obj
<</Length 4>>
stream
aaaa
endobj
```
Sometimes, `endstream` is prepended with garbage:
```
1 0 obj
<</Length 4>>
stream
aaaa
>>endstream
endobj
```

In these cases, the parsing fails, often with messages similar to:
```
Encountered a start object 'obj' operator before the end of the previous object.
```

**Comment by Greybird** [comment]
The checks seem to be stuck somehow. Locally I don't encounter any issues...

**Comment by BobLd** [comment]
I just restarted the tests, just in case

**Comment by Greybird** [comment]
Thanks, If they block against, I'll try to ensure I use the exact same test settings as the pipeline locally.

**Comment by Greybird** [comment]
I found the issue.
While compilation is done in release mode, tests recompile in Debug, as `-c Release` is not set in the test command line.
In this case, the `Debug.Assert` is showing a popup when run under `dotnet test` (it was not under Resharper, which I used locally.
I propose to switch running tests in Release mode, as per my last addition to this PR.

**Comment by BobLd** [comment]
Well spotted for the tests not running in Release mode. I know @EliotJones experienced issues with these Asserts in tests - I'm sure he'll be interested by that
