### ISSUE TITLE
Opening pdf file takes forever

### ISSUE THREAD

**Issue by vlko** [UglyToad/PdfPig#904]
### Issue Description:
Loading one of our pdf file hands forever.
### Exception Details:
No exception, just PdfDocument.Open never ends
### Attached Document:
[hang_document.pdf](https://github.com/user-attachments/files/16907189/hang_document.pdf)
### Steps to Reproduce:
Open document with PdfDocument.Open 
### Sample Code to Reproduce the Issue:
[PdfPigHangs.zip](https://github.com/user-attachments/files/16907201/PdfPigHangs.zip)

**Comment by BobLd** [comment]
I might be wrong here but it seems to be an `xref0` that @Greybird was talking about...

**Comment by Greybird** [comment]
@BobLd, @vlko , you can try this branch of mine I wrote: https://github.com/Greybird/PdfPig/tree/feature/xref0
I'm think it could be done better at token parsing level, rather than handling the token afterwards using a Regex, but this can at least help confirm the issue lies with the missing space.

**Comment by BobLd** [comment]
@Greybird thanks a lot for that. It seems your approach is correct.

The only change I'd like to see is to drop the use of Regex and use `StartsWith()`. My understanding is that the logic would not be impacted.

```
[...]
               else if (isLenientParsing)
               {
                   if (operatorToken.Data.StartsWith(OperatorToken.Xref.Data))
                   {
                       scanner.Seek(scanner.CurrentPosition - operatorToken.Data.Length + 4);
                       scanner.MoveNext();
                   }
                   else
                   {
                       throw new PdfDocumentFormatException($"Unexpected operator in xref position: {operatorToken}.");
                   }
               }
[...]
```

If you are willing to, happy for you to create a PR.

Thanks again for your great contributions! You fixed many long standing issues!

**Comment by Greybird** [comment]
Great, I'll propose a PR tomorrow integrating your change suggestion!

**Comment by BobLd** [comment]
@vlko please do not hesitate to re-open the issue if need be

**Comment by vlko** [comment]
Thanks, I can confirm problem is fixed. I tested with Nuget build 0.1.9-alpha-20240910-4845f.
