### ISSUE TITLE
Letter consists of two characters

### ISSUE THREAD

**Issue by thommie-echo** [UglyToad/PdfPig#921]
[Schiphol HY.pdf](https://github.com/user-attachments/files/17363496/Schiphol.HY.pdf)

Using the below code and the above document you get a letter which has unicode 130 and the Value is "fi". I wasn't expecting the Letter.Value to ever be more than one character but based on the CMAP and my limited knowledge it appears this might be intended behaviour.

Is there anyone that knows whether this is a bug or whether it should always return "fi"?

```
using (PdfDocument document = PdfDocument.Open(path))
{
    Content.Page p = document.GetPage(1);
    Content.Letter l = p.Letters[476];
}

**Comment by BobLd** [comment]
@thommie-echo yes this is expected, and you can even have more than 2 characters (e.g. with emogies) in a 'Letter'.

In your case, you might want to look at the following to split the "fi" in 2

https://learn.microsoft.com/en-us/dotnet/api/system.string.normalize?view=net-8.0
