### ISSUE TITLE
PdfDocument.Open() can read encrypted file with any string as password?

### ISSUE THREAD

**Issue by fphcare-tomasz** [UglyToad/PdfPig#937]
I testing reading of the PDF content, that is protected for modifications (copy content is not allowed) and expect to provide a password to the Open method, however it seems I can pass any, literally any string to decrypt a file I know the password for is set?

rudimentary code sample / check

        public bool CanReadFileContent(Stream fileStream, string password)
        {
            try
            {
                using var document = PdfDocument.Open(fileStream, new ParsingOptions { Password = password });
                Console.WriteLine("Is Encrypted: " + document.IsEncrypted); **// prints true, as expected**

                var metadata = document.Information;
                Console.WriteLine("Title: " + metadata.Title); 
                var pages = document.GetPages();
                ...
                Console.WriteLine("Pages: " + pages.Count());
                Console.WriteLine("Words Page 1: " + wordsPageOne.Count());
                Console.WriteLine("Words 1 Page 1: " + wordsPageOne.FirstOrDefault());
                return true;
            }
            catch (PdfDocumentEncryptedException ...)
            {
              ...
            }
            catch (Exception ...)
            {
            ...
            }
        }     
      
So lets say I have a PDF encrypted with password "supersecret" (I have been provided the correct password with the file), 

and I can successfully execute and get "true"
      
      var canReadShouldBeAbleTo = CanReadFileContent(fileStream, "supersecret")
      
      (all console writeline execute as expected, function returns true)
      
and I can successfully execute and get "true" 
      
       var canReadButShouldNot = CanReadFileContent(fileStream, "nonsenseIrandomlytypedin");
       
(all console writeline execute - expect to fail and exit early from function after around "Is Encrypted")
       
PdfPig nuget version installed in c# project: 0.1.9.
Project targeting .NET 8.

**Comment by cremor** [comment]
What happens if you don't pass any passwort at all (remove the whole `ParsingOptions` parameter). I suspect it will behave the same.

If the PDF is only protected against modification, then reading it doesn't need a password. The setting that prevents copying from a PDF is only enforced by the PDF reader application, and PdfPig simply doesn't enforce it 😄

**Comment by BobLd** [comment]
@fphcare-tomasz I'm closing the issue as it looks like you don't have the issue anymore. Feel free to reopen it if need be

**Comment by fphcare-tomasz** [comment]
"_...it looks like you don't have the issue anymore_" is not quite true, but I am not getting anywhere on here, so sure, lets close this
