### ISSUE TITLE
End users having issues

### ISSUE THREAD

**Issue by kareemsulthan07** [UglyToad/PdfPig#938]
In my project I have added pdfpig nuget package along with its dependencies. Everything was working fine until I recently updated its dependencies to their latest version. Now end users are getting these errors. 

![image](https://github.com/user-attachments/assets/e518f38d-e4af-418d-951e-3995d786e6de)

![image](https://github.com/user-attachments/assets/a48a2f8b-6290-461a-aa45-da4bce2e87e6)

**And, version details :** 
target framework : .net framework 4.7.2
pdfpig version : 0.1.9

**dependencies**
microsoft.bcl.hashcode : 6.0.0
system.memory : 4.6.0
system.runtime.compilerservices.unsafe : 6.1.0

**Comment by BobLd** [comment]
@kareemsulthan07 can you check you don't have library conflicts in the project where you use PdfPig?

For example PdfPig should target `System.Memory` Version=4.5.5

**Comment by kareemsulthan07** [comment]
I downgraded `System.Memory` version from 4.6.0 to 4.5.5 across all projects in my solution. Now it is giving this error.
![image](https://github.com/user-attachments/assets/f7884270-be9b-4bf9-9b68-c08500ae6175)

**Comment by BobLd** [comment]
You will need to do the same thing for all dependencies. Closing this issue as not related to PdfPig.
