### ISSUE TITLE
unicode to ASCII "Translation"

### ISSUE THREAD

**Issue by smiles3983** [UglyToad/PdfPig#94]
The PDF's I have contain unicode characters.  When I extract the text, it appears the characters are being converted to ascii, which is fine, but the issue is that the conversion seems to be a 1-1 instead of a translation.  I need an é should convert to an e, not something crazy like â€“

**Comment by EliotJones** [comment]
Hi, sorry to hear you're running into this issue.

It's probably related to the font type the PDF file is using. In general the library supports Unicode text, for example https://github.com/UglyToad/PdfPig/blob/master/src/UglyToad.PdfPig.Tests/Integration/OldGutnishTests.cs#L33 but there are many different ways the PDF specification handles encoding information depending on the font.

Would you be able to share a file that displays this issue at all please? It's very difficult to fix these issues without a test case to work off.

**Comment by EliotJones** [comment]
I'm going to close this for now but if you happen to come across and example feel free to re-open.
