### ISSUE TITLE
Letter text contains Unicode values

### ISSUE THREAD

**Issue by vadik299** [UglyToad/PdfPig#95]
Hi, 
This issue might be similar to #94. I'm not sure if I'm doing something wrong, but I can't figure out how to fix it. Would appreciate any guidance.

This document contains Euro symbols:
https://drive.google.com/open?id=1KQZx_79dAFzyr7pw__HNtZvAQLJEvq66

When I read it using PdfBox I'm getting string containing "€"
In PdfPig I'm getting "\u0080", which is probably same thing, but in Unicode. Shouldn't it be in UTF8? Or am I not using it right? Could you suggest a way to convert it?

Here's the code to reproduce:

            using (PdfDocument document = PdfDocument.Open(@"C:\euro.pdf"))
            {
                var page = document.GetPage(1);

                var euro = page.Letters[515];
                string shouldBeEuroSign = euro.Value; //should be €
            }

**Comment by EliotJones** [comment]
This seemed to be a corner case related to Type 1 fonts which should now be fixed, please give it a go and let me know.

**Comment by vadik299** [comment]
Works beautifully. Thank you!
